sucrase -> swc
backstage/backstage pull request #10394
Opened 2022-03-23 12:14 UTC by benjdlambert

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-06-22 10:13 UTC, Rugvip commented
Very much want to get this shipped. I do believe we may have a dependency on https://github.com/swc-project/jest/issues/59 or similar solution, refactoring all existing mocks would be a huge pain for some existing projects (like our own internal one). Best action to move this PR forward right now I'd say is to clean up the modifications to all existing packages so that we see the minimum requirements. If there are other test improvements to be done I'd say ship those as separate PRs so we can keep this focused on the swc switch.

2022-06-23 12:19 UTC, camilaibs approved these changes
Approved changes in files maintained by @backstage/techdocs-core .

2022-08-15 05:19 UTC, jrwpatterson commented
Any update on this?

2022-08-16 08:27 UTC, benjdlambert commented
@jrwpatterson haven't had chance to get around to fixing this up yet. An update would be that we want to try and make the test changes disappear so that the current test suite works without modifications, and that's going to require some digging as to why the `mock*` `const` declarations don't get hoisted and have to be declared in a different way. We ideally want this to be as transparent as possible, so that we don't ship a breaking change in the CLI just because we've changed the build tooling. If you want to dig around and try and work out what's going on, please feel free. Might have some time at the end of this week to carry on digging, but the issue that @rugvip mentioned earlier is probably a good place to start looking as to what is going on here.

2022-08-19 01:23 UTC, jrwpatterson commented
@benjdlambert I'll give it a go maybe next week this is causing a few problems for us. things like the tests for some other projects are un able to be used and the esm transforms I would like to use SWCJest too for...

we are using a monorepo with some dependent services in  nest and the esm  is breaking the tests and I guess we could pull the project out but then if this branch is on its way in (fingers crossed!) we can do it once and in the short term have two test commands. 

for some reason sucrase's test command is pulling type errors out of no where so they aren't displayed on the IDE or during builds just tests...

2022-08-19 18:18 UTC, benjdlambert commented
@jrwpatterson little bit more of an update is that we had some hack time on this recently, and think we're in a good place with this now. Looks like that errors with the test suite that we're brought up by this are because of the forgiving nature of `sucrase` and it's not really how it should work, so we're going to include some advice on what to do if your tests suites fail after upgrading, but looking to try and get this in before the pre-release next week if possible.

2022-08-23 08:17 UTC, Rugvip requested changes
🔜

2022-08-23 08:17 UTC, Rugvip commented on packages/cli/src/lib/bundler/config.ts
> +    );
How come this is not used in dev? Best to have a comment explaining that

2022-08-23 08:17 UTC, Rugvip commented on .changeset/rotten-books-crash.md
> +Removing dependency on `react-hot-loader`, the we ship `swc` and `React Refresh` out of the box now with the `cli`
```suggestion
Removed the dependency and setup of `react-hot-loader`, since the `@backstage/cli` now uses `swc` with `React Refresh` instead.
```

2022-08-23 08:17 UTC, Rugvip commented on packages/cli/src/lib/bundler/transforms.ts
> +          loader: require.resolve('esbuild-loader'),
How come we use ESBuild here?

2022-08-23 08:17 UTC, Rugvip commented on storybook/.storybook/main.js
> +            jsc: {
Might as well set target here as well right? Just making it a bit smaller and faster

2022-08-23 10:22 UTC, merged