chore: update getDocumentText function to also return the displayName…
backstage/backstage pull request #10815
Opened 2022-04-13 14:53 UTC by djamaile

… if the entity is of type group

Signed-off-by: djamaile <rdjamaile@gmail.com>

## Hey, I just made a Pull Request!

Currently when searching, users have their display name under their actual name. I thought it would be nice to also have this automatically for groups. 

#### :heavy_check_mark: Checklist

- [ x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-04-14 07:58 UTC, emmaindal requested changes
Wops my bad, linked to the wrong file on Discord. The [`DefaultCatalogCollator`](https://github.com/backstage/backstage/blob/16a40ac4c058e774981dc7866491f589f1d1d5c6/plugins/catalog-backend/src/search/DefaultCatalogCollator.ts#L41) is deprecated, and replaced with [`DefaultCatalogCollatorFactory`](https://github.com/backstage/backstage/blob/16a40ac4c058e774981dc7866491f589f1d1d5c6/plugins/catalog-backend/src/search/DefaultCatalogCollatorFactory.ts), so just move your changes there! 💯

2022-04-14 08:18 UTC, djamaile commented
@emmaindal seems like that function already has what I had in mine. It seems only that the `isGroupEntity` has the wrong return type, but it shouldn't have impact functionality. So, I am fine with also closing this PR. 

The reason I wanted this is because groups are not showing with their display name under their name in the search results. I wonder what is going on, but this function and all the test cases seem to work.

2022-04-14 08:22 UTC, emmaindal commented
> @emmaindal seems like that function already has what I had in mind. It seems only that the `isGroupEntity` has the wrong return type, but it shouldn't have impact functionality. So, I am fine with also closing this PR.
> 
> The reason I wanted this is because groups are not showing up with their display name under their name in the search results. I wonder what is going on, but this function and all the test cases seem to work.

@djamaile I see, I think its nice to get that return type fixed anyways so let's do that!  But you say that it doesn't work for you, and you do use the new collator factory in your app?

2022-04-14 08:28 UTC, djamaile commented
@emmaindal yeah importing `DefaultCatalogCollatorFactory` from `catalog-backend`, where `catalog-backend` is set 1.0.0 version.

2022-05-02 09:49 UTC, benjdlambert approved these changes
Looks good to me, @emmaindal can we merge this? :pray:

2022-05-05 13:33 UTC, emmaindal approved these changes
💯

2022-05-05 13:36 UTC, freben approved these changes

2022-05-05 13:36 UTC, merged