Copy favicons from microsite
backstage/backstage pull request #1115
Opened 2020-06-03 04:08 UTC by burgwyn

## Update Favicon

Addresses #1071 with assets from the [microsite](https://github.com/spotify/backstage-microsite/pull/163)

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

2020-06-03 08:00 UTC, stefanalund commented
Thanks for the PR! I think there is something missing, because I don't see the favicon in my browser tab:

![Screenshot 2020-06-03 at 09 45 32](https://user-images.githubusercontent.com/190856/83611322-1cc10f00-a581-11ea-8cc1-b49265b449ec.png)

2020-06-03 13:14 UTC, shmidt-i requested changes

2020-06-03 13:14 UTC, shmidt-i commented on packages/app/public/favicon.svg
> +        path {
This is going to affect **all** `path` elements in the document, we don't want that. Instead, use `withStyles` from the `@material-ui/core` and also then you are able to read `theme.palette.type` which would be `light` or `dark` based on the current theme used.

2020-06-03 13:30 UTC, shmidt-i commented on packages/app/public/favicon.svg
> +        path {
Sorry, misread the context, disregard the material-ui part. Anyway we need to make this more modular, at least like a className

2020-06-08 18:26 UTC, stefanalund commented
Rebased on `master` and now we are getting closer:

![Screenshot 2020-06-08 at 20 23 06](https://user-images.githubusercontent.com/190856/84066426-31a90280-a9c6-11ea-955a-1c79052a4124.png)
![Screenshot 2020-06-08 at 20 23 14](https://user-images.githubusercontent.com/190856/84066430-32419900-a9c6-11ea-9daa-eb21d2b94314.png)

I believe the SVG version of the favicon is not used because of the same issue as https://github.com/spotify/backstage/issues/1202.

2020-07-01 14:59 UTC, freben approved these changes
Let's merge and tweak! Thank you for your contribution!

2020-07-01 15:00 UTC, shmidt-i approved these changes
Let's fix it in a separate PR!

2020-07-01 15:01 UTC, merged