chore(cli): forbid path imports to other packages/plugins
backstage/backstage pull request #1246
Opened 2020-06-11 09:49 UTC by freben

prevents accidental

```ts
import x from '../../../packages/core/x"
```

2020-06-11 09:50 UTC, Rugvip requested changes
This is provided by `'plugin:monorepo/recommended'`

2020-06-11 09:51 UTC, Nek approved these changes
💎

2020-06-11 09:51 UTC, Rugvip commented
Or maybe it's not, but I'm pretty sure this is not possible in the frontend :grin:

Let's dig a bit

2020-06-11 09:55 UTC, Rugvip commented
Ah it's allowed in the frontend too, but perhaps go with `**/src/**` instead and add an exception for `/dev/**`? This doesn't prevent `../../auth-backend/src/...`

2020-06-11 10:02 UTC, Rugvip commented
Ah the pattern `**/../**/*/src/**` should catch everything I think? As in "if you're going backwards, you can't go into the `src/` dir of something else". That way we don't block packages from importing their own src dir

2020-06-11 10:04 UTC, freben commented
but then you still want an exception for dev, right? not sure if that's possible 🤔

2020-06-11 10:09 UTC, Rugvip commented
Ah yeah it would have to be anything but `..` allowed in the `*` before `/src`, not sure if that's possible.

2020-06-11 10:10 UTC, Rugvip commented
This is supposed to be caught by https://github.com/azz/eslint-plugin-monorepo btw, as I understand the docs anyway.

2020-06-11 12:39 UTC, freben commented
@Rugvip i seem to not be able to trigger that rule ... it lets me import across modules freely.

2020-06-15 11:36 UTC, freben commented
Closed for now. We'll perhaps look into making sure `plugin:monorepo` does its thing properly at a later point instead.

2020-06-15 11:36 UTC, closed without merging