OpenApiRefProcessor: add basepath support for $ref
backstage/backstage pull request #12814
Opened 2022-07-25 07:41 UTC by mfrinnstrom

## Hey, I just made a Pull Request!

There was an error reported in https://github.com/backstage/backstage/issues/12687. I'm not sure if this fixes that issue since I don't have all the details yet but this seems like a case that should be supported anyway.

This adds a `openapi/ref-basepath` annotation that allows you to specify from what base path all `$ref` instances should be resolved instead of them always being resolved from the `catalog-info.yaml` file location.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-07-25 08:45 UTC, benjdlambert commented
I'm not sure that an annotation is the best place for this to be honest, feeling like it could be more beneficial to supply a function to the `Processor` that can resolve this for you using whatever method you want. Need to think about this a little bit more. Will get back to you. 🙏

2022-07-25 09:15 UTC, mfrinnstrom commented
@benjdlambert I'm more than happy to do this in another way if possible. 

The problem as I see it is that the information that I would need is the path in `definition` field but by the time the `OpenApiRefProcessor` gets called that has already been replaces by the `$text` resolver. 

I tried to see if I could write a wrapper for that that somehow stores the path temporarily but there wasn't enough information available to the resolver to determine if we are working on the `definition` key or not. 

Then I tried to see if I could handle it by wrapping the `PlaceholderProcessor` but that is not possible, for good reasons, I believe.

That left me with the annotation to at least be able to support this use case right now. The `OpenApiRefProcessor` is also opt-in so not everybody will have to handle this for their OpenAPI spec to work. If they have everything in one file then they don't need to touch this at all.

 I hope that makes sense and, as I said, if I have missed something that would allow me to this without the annotation I'm more than happy to do that.

```yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: vehicle-search
  description: Vehicle Search
  annotations:
    openapi/ref-basepath: ./spec
spec:
  type: openapi
  lifecycle: production
  owner: vehicle-search-team
  definition:
    $text: ./spec/openapi.yaml # I would need access to this value to do this without the annotation
```

2022-07-29 11:56 UTC, benjdlambert commented
Sorry for the delay! Yep, @mfrinnstrom this ability has come up before actually, I wonder if it's possible for us to maybe forward some of this metadata from the unfurled stuff from the Placeholder processor. Going to want some more eyes from @backstage/maintainers for this I think after they're back from vacation to see if we can't come up with something a little better than an annotation.

2022-07-29 22:39 UTC, niallmccullagh commented
Feels somewhat similar to the [backstage.io/techdocs-ref](https://backstage.io/docs/features/software-catalog/well-known-annotations#backstageiotechdocs-ref) annotation.

2022-07-30 09:03 UTC, benjdlambert commented
@niallmccullagh I agree for the most part, but the difference between them is we actually do have the `basepath` already declared in the file once in this case as it's used for `$text` replacer. Would be a shame to have to duplicate it was all I was thinking.

2022-08-05 06:23 UTC, mfrinnstrom commented
@benjdlambert I realized that we do have the URL for the `catalog-info.yaml` file. Would it be a more acceptable solution to just reread that and have some logic check if `$text` is the only key in the `spec` field and in that case process that?

2022-08-05 08:26 UTC, benjdlambert commented
Hmm - seems a little unfortunate to have to re-read grab the contents again, but maybe that's getting warmer :pray: The other folks are back monday, so we will have a chat.

2022-08-08 11:57 UTC, Rugvip commented
Really feels unfortunate to have to add annotations for this tbh, the information is already there. It's also risky to try to fetch the source entity again, as that might not be reachable or have the shape that one would expect.

I'm thinking the best way forward here might actually be to deprecate the `OpenApiRefProcessor` and instead package it up as a custom resolver for the [PlaceholderProcessor](https://github.com/backstage/backstage/blob/5b830da1b13a6318626763f7632096d37d08da16/plugins/catalog-backend/src/modules/core/PlaceholderProcessor.ts#L55)? Probably either as a decoration of the built-in `$text` resolver, or making it an additional `$openapi` resolver. That was we're hooking into the fetching logic and we know the URLs and paths that are involved.

2022-08-08 12:08 UTC, mfrinnstrom commented
@Rugvip that is fine. The processor was just a quick initial take on this that supported the use-case that I have had before. 

Do you have any preference on the `$openapi` resolver vs `$text` decorator? I'm thinking it might be better with a separate `$openapi` resolver to make sure that it will never interfere with any other `$text` fields. You can also be more specific when you want to use it as well then.

2022-08-08 18:34 UTC, Rugvip commented
Yep thinking `$openapi` first and see if that makes sense.

2022-08-10 05:29 UTC, mfrinnstrom commented
@Rugvip I switched it to a custom resolver now. I did copy some helpers from the `PlaceholderProcessor` since the weren't exported. Not sure how you want to handle that. Should they be exported instead?

I have tested it against my example repo [here](https://github.com/mfrinnstrom/backstage-openapi-ref-example) and those work as they should. The basepath one doesn't work with the current processor so that is an improvement at least 🙂

2022-08-11 09:53 UTC, Rugvip requested changes
Nice, I think it looks good! 👍 

Let's not worry about the copied helpers, they're pretty slim and light on logic.

Something up with the `yarn.lock` though, are you getting those changes when running `yarn install`? In that case, perhaps try a rebase on latest master, I'm not seeing the changes there.

2022-08-11 10:32 UTC, mfrinnstrom commented
Not sure where that change to `yarn.lock` came from. I rebased and now it is gone.

2022-08-11 11:13 UTC, Rugvip approved these changes
Nice, let's :shipit: 🎉

2022-08-11 11:13 UTC, merged

2022-09-23 19:26 UTC, asotog commented
Is this change on npm ? I upgraded our backstage today but still not working, this part of our api catalog yaml:

```
 annotations:
    openapi/ref-basepath: https://bitbucket.org/...

...

 definition:
    $openapi: https://bitbucket.org/....openapi.yaml

```

2022-09-23 20:23 UTC, asotog commented
ignore my previous comment, had to follow the plugin documentation https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-openapi