Cfaccess jwt pass
backstage/backstage pull request #13237
Opened 2022-08-19 01:33 UTC by tylerd-canva

## Hey, I just made a Pull Request!

This is a follow up to https://github.com/backstage/backstage/pull/12234. It's a small change so I'd just open a PR directly to get feedback.

The change adds the request JWT to the `CloudflareAccessResult` so that it can then be accessed by the `authHandler()` and `signIn` `resolver()` functions. My use case for this is so that I can make calls to enrich the User's `ProfileInfo` and related entities on behalf of the user using their own JWT.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-08-19 01:36 UTC, tylerd-canva commented
cc @renlord as the author of the Cloudflare Access provider

2022-08-19 07:29 UTC, freben reviewed
Looks good to me. @Rugvip any security or practical concerns with having this cached?

2022-08-19 07:56 UTC, Rugvip requested changes
Makes sense, thanks! 👍 

A couple of nits, and just to double check, the profile fetching you want to do is different from the existing identity profile fetch right?

2022-08-19 07:56 UTC, Rugvip commented on plugins/auth-backend/src/providers/cloudflare-access/provider.ts
> +  jwt: string;
I'm thinking I'd prefer `token` here, or `accessToken`/`idToken` if that is what it is. JWT is a bit of an implementation detail.

2022-08-19 07:56 UTC, Rugvip commented on plugins/auth-backend/src/providers/cloudflare-access/provider.ts
> +        jwt,
This is cached for the full duration of the token, which can cause some races towards the end of the expiration. In this case I think perhaps the best solution might be to not cache the token at all, but add the token to the returned object. Both on line 284 and 266.

2022-08-21 22:35 UTC, tylerd-canva commented
Thanks for the review! Fixing it up now.

> the profile fetching you want to do is different from the existing identity profile fetch right?

Yes, it's a separate internal service.

2022-08-22 03:38 UTC, renlord commented
> cc @renlord as the author of the Cloudflare Access provider

LGTM 👍

2022-08-23 00:51 UTC, tylerd-canva commented on plugins/auth-backend/src/providers/cloudflare-access/provider.test.ts
> +      expect(result).toEqual(
It's a bit awkward to put expectations in these test fixtures, but I wasn't sure of a cleaner way to accomplish this type of verification. Open to any suggestions :)

2022-08-23 11:45 UTC, freben approved these changes
Thanks!

2022-08-23 11:45 UTC, merged

2022-08-26 15:17 UTC, suuus commented
Thanks for your contribution @tylerd-canva 🙌 Please let me know if you’d like some help to contribute further.