Updated FAQ with correct link
backstage/backstage pull request #1323
Opened 2020-06-16 20:54 UTC by nikkibeesetti

“Will Spotify’s internal plugins be open sourced, too?” had an incorrect link, and I added the correct one.

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

2020-06-17 08:26 UTC, stefanalund requested changes
@nikkibeesetti this link is also incorrect. It misses a /backstage

2020-06-22 16:33 UTC, nikkibeesetti reviewed
reviewed

2020-06-22 20:03 UTC, stefanalund approved these changes
I fixed the links myself.

2020-06-22 20:33 UTC, fengypants commented on docs/FAQ.md
> +[a plugin](https://github.com/spotify/backstage/faq#what-is-a-plugin-in-backstage).
I don't think …/spotify/backstage/… works either. Think it has to be this:
https://github.com/spotify/backstage/blob/master/docs/FAQ.md#what-is-a-plugin-in-backstage

2020-06-22 20:35 UTC, fengypants commented on docs/FAQ.md
> +[Plugins](https://github.com/spotify/backstage/faq#what-is-a-plugin-in-backstage) are the
Same here — link should be:
https://github.com/spotify/backstage/blob/master/docs/FAQ.md#what-is-a-plugin-in-backstage

2020-06-22 20:36 UTC, fengypants commented on docs/FAQ.md
> +By far, our most-used plugin is our TechDocs plugin, which we use for creating technical documentation. Our philosophy at Spotify is to treat "docs like code", where you write documentation using the
This link should be:
https://github.com/spotify/backstage/blob/master/docs/FAQ.md#will-spotifys-internal-plugins-be-open-sourced-too

2020-06-22 20:40 UTC, Rugvip commented
Or have the links be `/docs/FAQ.md#...`, it's shorter and will work better in editors and different branches.

2020-06-22 20:57 UTC, fengypants commented
The shorter format works for me! Let's just make sure to update all **three** links with this PR.

2020-06-25 19:20 UTC, closed without merging