create-app: add `EntityLinksCard` to the System `EntityPage`
backstage/backstage pull request #13269
Opened 2022-08-21 20:53 UTC by GoFightNguyen

Signed-off-by: Jason Nguyen <jsn.dev@outlook.com>

## Hey, I just made a Pull Request!

![image](https://user-images.githubusercontent.com/6308176/185810464-0f8a9d46-0284-430f-8c62-7224622cbbef.png)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-08-21 20:58 UTC, GoFightNguyen commented
[A little context from discord](https://discord.com/channels/687207715902193673/923144214580191282/1009219322675220580)
I figured this PR can remove any ambiguity as to why the System's page does not include links.

2022-08-22 09:09 UTC, jhaals requested changes
Thanks for the PR! I have suggested some minor adjustments and pointers for existing users that would like to apply this change themselves.

2022-08-22 09:09 UTC, jhaals commented on .changeset/young-trees-rescue.md
> +Add `EntityLinksCard` to the system `EntityPage`.
```suggestion
Added `EntityLinksCard` to the system `EntityPage`.

For an existing installation where you want to display the links card for entity pages of kind `system` you should make the following adjustment to `packages/app/src/components/catalog/EntityPage.tsx`
```

2022-08-22 09:09 UTC, jhaals commented on .changeset/young-trees-rescue.md
> +'@backstage/create-app': minor
```suggestion
'@backstage/create-app': patch
```

2022-08-22 15:32 UTC, GoFightNguyen commented
Thanks @jhaals, I applied these changes and squashed them into the first commit

2022-08-23 09:30 UTC, jhaals approved these changes
Nice work! Thanks 👍

2022-08-23 09:30 UTC, merged