catalog-ms-graph: fixes #13298, ignored userExpand and groupExpand parameters
backstage/backstage pull request #13299
Opened 2022-08-23 08:40 UTC by gtestault

## Hey, I just made a Pull Request!

fixes #13298

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-08-23 09:43 UTC, jhaals requested changes
Thanks for the fix! Needs a slight formatting change for the changeset.

2022-08-23 09:43 UTC, jhaals commented on .changeset/afraid-radios-boil.md
> +Fixed bug in MicrosoftGraphEntityProvider ignores userExpand and groupExpand configuration parameters
```suggestion
Fixed a bug in the `MicrosoftGraphEntityProvider` that ignored the `userExpand` and `groupExpand` configuration parameters
```

2022-08-24 08:36 UTC, jhaals approved these changes

2022-08-24 08:36 UTC, merged

2022-08-24 08:36 UTC, jhaals commented
Thanks!

2022-08-26 15:17 UTC, suuus commented
Congrats on your first PR merged @gtestault! Happy to count you as a contributor.