Local SSL tutorial
backstage/backstage pull request #13363
Opened 2022-08-25 23:10 UTC by nmarinel

## Hey, I just made a Pull Request!

No code, just a contrib doc :). This was suggested after some discussion in the `auth` Discord channel about how to enable TLS for local testing.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-08-26 11:30 UTC, jhaals commented
Thanks for the suggestion! Perhaps these docs could be simplified by using https://github.com/FiloSottile/mkcert instead. That should remove both the generation step and possibly the need for the node environment variable as well.

2022-08-26 19:27 UTC, nmarinel commented
@jhaals mkcert is a pretty neat tool, thanks for sharing that. I'll admit I struggled with it a bit running Windows/WSL(I first tried installing it in WSL, which Windows doesn't recognize as a CA store), but the problems weren't anything we wouldn't expect the average dev to work through. I've updated the instructions to use mkcert instead of openssl.

One unfortunate note, it looks like the [node environment variable is needed even with mkcert](https://github.com/FiloSottile/mkcert#using-the-root-with-nodejs).

2022-08-30 11:18 UTC, benjdlambert commented
You could also maybe introduce some docs for the #13338 that's also introducing the webpack config for enabling https for the frontend locally too once that's merged? Just thinking that it would be good to align these.

2022-09-06 21:35 UTC, nmarinel commented
Good call, @benjdlambert. I've updated the instructions for the frontend to reflect the updated config. Also I realized you can use `$file` instead of copying the contents of the file, so that deserved to be included :). 

LMK what you think.

2022-09-21 14:37 UTC, jhaals requested changes
Sorry for the wait time! This has for some reason dropped out of my review inbox. One small comment but otherwise looking good :)

2022-09-21 14:37 UTC, jhaals commented on contrib/docs/tutorials/enable-ssl-self-signed.md
> +1. Start the backend with `NODE_EXTRA_CA_CERTS=/absolute/path/to/cert.pem yarn start-backend`
is this needed if you use mkcert as it installs the certificate in the trust store? Would you be able to verify if it works without it? 🙏

2022-09-22 07:21 UTC, jhaals approved these changes
I just realised that you already tried without the environment variable, thanks!

2022-09-22 07:21 UTC, merged