scaffolder: update to `react-jsonschema-form` `v5`
backstage/backstage pull request #13428
Opened 2022-08-30 12:10 UTC by benjdlambert

2022-08-30 12:11 UTC, benjdlambert commented
Need to work through the typescript issues here too, but just opened this so that theres progress on it.

2022-09-29 21:44 UTC, benjdlambert commented
As discussed before - this is gonna ship rjsfv5 + rjsfv3 together for now, and the breaking changes will be encapsulated behind the `/next` scaffolder for now. Maybe we can also come up with a way to introduce these changes in a less breaking way too. But want to get this in so that we can have them in parallel :)

2022-10-11 10:18 UTC, Rugvip requested changes
🎉 , some small things

2022-10-11 10:18 UTC, Rugvip commented on plugins/scaffolder/src/next/TemplateWizardPage/Stepper/Stepper.tsx
> +      return i.__errors?.length! > 0 ?? false;
```suggestion
     i.__errors?.length
```

Missing the explicit `> 0` check is a bit meh, but feeling it's worth it here

2022-10-11 10:51 UTC, Rugvip approved these changes

2022-10-11 12:03 UTC, merged