[Blog] FYI - Plugin Analytics API
backstage/backstage pull request #13511
Opened 2022-09-02 14:50 UTC by iamEAP

## What/Why

Have been in a number of conversations with adopters who had no idea the API existed.  So let's make some noise!

2022-09-02 15:05 UTC, ewhite1997 commented on microsite/blog/2022-09-08-fyi-plugin-analytics-api.md
> +**TL;DR** If you didn't know, now you now: the Backstage plugin analytics API is here to help you understand how developers in your organization are using Backstage.
small typo: "now you now" should be "now you know"

2022-09-07 12:30 UTC, Rugvip requested changes
🔊 🔊 🔊 🔊 🔊 

Gotta add the truncation, but rest is just opinions and good to go whenever you wanna :shipit:  :grin:

2022-09-07 12:30 UTC, Rugvip commented on microsite/blog/2022-09-08-fyi-plugin-analytics-api.md
> +
This needs a fold (`<!--truncate-->`) somewhere, and prefereably some art above that as well. Otherwise it'll take up the full space.

2022-09-07 12:30 UTC, Rugvip commented on microsite/blog/2022-09-08-fyi-plugin-analytics-api.md
> +];
Quite a lot of code for a blog post, and stuff that needs to be updates as well. Perhaps there are some instructions we can link to instead?

2022-09-07 16:12 UTC, Rugvip approved these changes

2022-09-08 15:11 UTC, merged