Feature/optimise GitHub access tokens
backstage/backstage pull request #13542
Opened 2022-09-05 22:29 UTC by afscrome

## Hey, I just made a Pull Request!

Fixes #13481.  
* Do Allowed Installation Owner check before happen before making a call to `/app/installations`
* Move call to `/app/installations` to be within the cacheable section

TODO:
* [ ] Add missing tests around caching
* [ ] Try and optimise caching so we don't need to cache a unique token per app/repo combo.  It should be 
* [ ] Optimise cache expiration to allow tokens to last longer than 10 minutes. 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-09-08 09:27 UTC, afscrome commented
@benjdlambert  Any chance you'll be able to take a look at this PR today?  I'll be on holiday next week, so would be good to get this done before then.

There's currently one failing check with review dog not liking the spelling of `url`, which I think is a false positive.

2022-09-08 11:09 UTC, freben commented
Vale probably wants it to be uppercase URL.

2022-09-08 11:57 UTC, afscrome commented
Bingo @freben.  Thanks.

2022-09-08 12:18 UTC, jhaals requested changes
Thanks for looking into this!
Some minor tweaks but otherwise looking good 👍

2022-09-08 12:18 UTC, jhaals commented on .changeset/sweet-grapes-explain.md
> +'@backstage/integration': minor
Looks like this is a bugfix so let's make this a `patch`

2022-09-08 12:18 UTC, jhaals commented on packages/integration/src/github/SingleInstanceGithubCredentialsProvider.ts
> +    let ownerData = this.tokenCache.get(owner);
It's a bit tricky to know what ownerData actually is, perhaps something like this?
```suggestion
    let existingInstallationData = this.tokenCache.get(owner);
```

2022-09-09 11:10 UTC, jhaals approved these changes
Thanks @afscrome 🥇

2022-09-09 11:11 UTC, merged