Feature/pass select attr to msgraph user import
backstage/backstage pull request #13553
Opened 2022-09-06 09:13 UTC by lsiric

## Hey, I just made a Pull Request!

Microsoft Graph Import supports importing users and groups. Groups import supports passing a `$select` parameter to the query, while the Users import does not.

This pull request adds a `$select` parameter to the User import query. Underlying methods already support it, so the implementation only includes passing the string array attribute to the `getUsers` method. 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-09-07 12:23 UTC, Rugvip requested changes
Nice, thank you! 👍 

Closes #9796 right @pjungermann?

2022-09-07 12:23 UTC, Rugvip commented on .changeset/cuddly-clocks-dance.md
> +'@backstage/plugin-catalog-backend-module-msgraph': minor
```suggestion
'@backstage/plugin-catalog-backend-module-msgraph': patch
```

Not a breaking change right? can make it a patch as we're on 0.x

2022-09-09 14:17 UTC, pjungermann commented
@Rugvip thought I already replied here 😅 

It solves half of the issue as this PR only adds select for user and group would still be open.

@lsiric maybe you can consider including support for group as well to close the issue completely. If you cannot it is no problem either.

2022-09-09 19:06 UTC, lsiric commented
@pjungermann iit seems `groupSelect` is already implemented? 

`plugins/catalog-backend-module-msgraph/src/microsoftGraph/read.ts` 

```
  options?: {
    queryMode?: 'basic' | 'advanced';
    groupExpand?: string;
    groupFilter?: string;
    groupSearch?: string;
    groupSelect?: string[];
    groupTransformer?: GroupTransformer;
    organizationTransformer?: OrganizationTransformer;
  },
```

and the same `groupSelect` is being passed down below to the `getGroups` method : 

```
  for await (const group of client.getGroups(
    {
      expand: options?.groupExpand,
      search: options?.groupSearch,
      filter: options?.groupFilter,
      select: options?.groupSelect,
    },
    options?.queryMode,
  )) {
```

2022-09-09 19:11 UTC, pjungermann commented
ah, perfect. Seems like I just forgot about that 😅

Great, then this will close the issue completely in its form.

Change looks good to me, too. 👍

2022-09-13 08:49 UTC, Rugvip approved these changes
Nice! 👍 

Alright, let's :shipit:

2022-09-13 08:49 UTC, merged