exported KubernetesContainerRunner, KubernetesContainerRunnerOptions,…
backstage/backstage pull request #13676
Opened 2022-09-14 08:22 UTC by matteosilv

In my previous PR I forgot to export public symbols and generate api-report.md

ref: https://github.com/backstage/backstage/pull/12839

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-09-14 15:23 UTC, matteosilv commented
Can somebody help me understend why e2e tests are failing after I uploaded the api-report.md?

2022-09-19 12:35 UTC, jhaals requested changes
Thanks for the PR!
We had some build issues last week and had to force push to the mater branch in order to clear up the issues. Rebase your PR on master and it should hopefully clear up 🤞

2022-09-20 11:14 UTC, matteosilv commented
> Thanks for the PR! We had some build issues last week and had to force push to the mater branch in order to clear up the issues. Rebase your PR on master and it should hopefully clear up 🤞

Guys I added @types/js-yaml and @types/request to the backend-common package.json, it fixed a couple of workflows but still some e2e tests are failing because of js-yaml and I don't have any other ideas to fix it. Can you give me a hand?

2022-09-20 11:50 UTC, jhaals requested changes
Thanks for the PR! Some minor tweaks needed to the API which probably removes the need for those additional dependencies as well :)

2022-09-20 11:50 UTC, jhaals commented on packages/backend-common/api-report.md
> +  runContainer(options: RunContainerOptions): Promise<void>;
This should be the only method that should be made public right?
Would be nice to slim down the API surface of what we export :)

2022-09-21 11:41 UTC, jhaals requested changes
Thanks for the fixes! Some minor fixes left and then I think we're good to go :)

2022-09-21 11:41 UTC, jhaals commented on packages/backend-common/api-report.md
> +export type MountBaseOptions = {
```suggestion
export type KubernetesContainerRunnerMountBase = {
```

2022-09-21 11:41 UTC, jhaals commented on .changeset/kind-walls-share.md
> +exported KubernetesContainerRunner, KubernetesContainerRunnerOptions, MountBaseOptions
```suggestion
exported `KubernetesContainerRunner`, `KubernetesContainerRunnerOptions` and `KubernetesContainerRunnerMountBase`
```

2022-09-23 07:59 UTC, jhaals requested changes
Hi @matteosilv!

It looks like this is due to an underlying issue in the Kubernetes client library for javascript. There's currently an open issue in https://github.com/kubernetes-client/javascript/issues/883 describing the problem. I don't think we want to add these dependencies in the create-app template as it's likely that it might cause issues for users later.
Could we wait with this until we have gotten an update from the kubernetes folks? Most likely this is a mistake that should be reverted.

2022-09-23 09:54 UTC, matteosilv commented
> Hi @matteosilv!
> 
> It looks like this is due to an underlying issue in the Kubernetes client library for javascript. There's currently an open issue in [kubernetes-client/javascript#883](https://github.com/kubernetes-client/javascript/issues/883) describing the problem. I don't think we want to add these dependencies in the create-app template as it's likely that it might cause issues for users later. Could we wait with this until we have gotten an update from the kubernetes folks? Most likely this is a mistake that should be reverted.

Absolutely! It seemed a little odd to me too

2022-10-05 10:18 UTC, matteosilv commented
Don't know what changed, but taking in recent master branch commits seems to have fixed the issue. I just removed the edits to the create-app `package.json.hbs` template, because I want to be sure they are actually needed, before issuing an un-needed patch version for a module

2022-10-14 13:12 UTC, matteosilv commented
Something is moving 😄 https://github.com/kubernetes-client/javascript/pull/890

2022-10-23 15:03 UTC, danmontgomery commented
https://github.com/kubernetes-client/javascript/pull/890 was merged so this should be addressed with next release

2022-10-24 08:19 UTC, matteosilv commented
> [kubernetes-client/javascript#890](https://github.com/kubernetes-client/javascript/pull/890) was merged so this should be addressed with next release

We need to wait for 0.17.2 and merge after then! Thanks!

2022-11-09 10:50 UTC, matteosilv commented
Just wanted to re-open this as we are waiting for javascript kubernetes client  0.17.2 to come out

2022-11-17 09:20 UTC, matteosilv commented
There is still no date for 0.17.2...

2022-11-23 14:14 UTC, matteosilv commented
This request is stuck since September.... Do we have any alternative to merge it in, without relying on Kubernetes javascript client being updated?

2022-11-24 14:35 UTC, matteosilv commented
> Hi @matteosilv! Yeah it's taking a looong time 😩 I asked around and got news that we have pinned the version to 0.17.0 for now which means we shouldn't need those additional dependencies. Could you try rebasing and removing the dependencies. Hopefully it should work! 🤞

Ok trying force pushing the initial commit from scratch

2022-11-24 15:10 UTC, matteosilv commented
yeaaaaaahhhh all checks passed. Guess we can finally merge 😄

2022-11-25 09:56 UTC, jhaals approved these changes
@matteosilv thank you for keeping this work alive 👏 🏅

2022-11-25 09:56 UTC, merged

2022-12-20 15:50 UTC, matteosilv commented
@danmontgomery the KubernetesContainerRunner is finally released with backstage v1.9.0, package backend-common 0.17.0