[Catalog] Allow placeholder value to be any type
backstage/backstage pull request #13690
Opened 2022-09-15 13:39 UTC by taras

## Hey, I just made a Pull Request!

Related #13288

I figured out how to use PlaceholderProcessor to prevent duplication in templates. In the process, we discovered that the processor only allowed the value to be a string. This is too restrictive in cases when you want to use the placeholder; that's an arbitrary function that returns a value.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-09-20 13:52 UTC, jhaals requested changes
Thanks for the proposal!
Overall I think we should be template other things than string.
However I'm not sure about the documentation section as it's very long which might lead to information overload. This is an advanced use case and I'm not sure that it would be very nice/common to extend templates like this. I would actually suggest that we do not put this example in the docs until we have figured of the patterns for reusable templates.

2022-09-20 13:52 UTC, jhaals commented on plugins/catalog-backend/src/modules/core/PlaceholderProcessor.ts
> +      // if (typeof resolverValue !== 'string') {
Some leftover here right?

2022-09-20 14:15 UTC, taras commented
> However I'm not sure about the documentation section as it's very long which might lead to information overload. This is an advanced use case and I'm not sure that it would be very nice/common to extend templates like this. I would actually suggest that we do not put this example in the docs until we have figured of the patterns for reusable templates.

Yeah, I can just leave it in this PR as description for someone who wants to try using it.

2022-09-20 14:26 UTC, taras commented on plugins/catalog-backend/src/modules/core/PlaceholderProcessor.ts
> +      // if (typeof resolverValue !== 'string') {
Removed this.

2022-09-20 14:27 UTC, taras commented
I removed unnecessary bits.

2022-09-21 09:35 UTC, jhaals approved these changes
Thank you 👍

2022-09-21 09:35 UTC, merged