(feat): kubernetes add new backend endpoints to api interface
backstage/backstage pull request #13697
Opened 2022-09-16 02:00 UTC by mclarke47

Signed-off-by: Matthew Clarke <mclarke@spotify.com>

Add the new backend endpoints to the client

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-09-19 12:12 UTC, mclarke47 commented
@benjdlambert if you get a sec!

2022-09-19 14:43 UTC, jhaals requested changes
Looks good overall, small suggestion regarding the API for evolvability. 😄

2022-09-19 19:57 UTC, mclarke47 commented on plugins/kubernetes/src/api/types.ts
> +  getCustomObjectsByEntity(
done!

2022-09-20 06:41 UTC, jhaals approved these changes
Looking good, thanks!

2022-09-20 06:42 UTC, merged