Chore: docs grammar fix
backstage/backstage pull request #13744
Opened 2022-09-20 02:28 UTC by tusharxoxoxo

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-09-20 06:45 UTC, jhaals requested changes
Thanks for improving the documentation! 👏 Small tweak and this is good to go

2022-09-20 06:45 UTC, jhaals commented on SECURITY.md
> +To work around this and other similar issues, Snyk provides a method to ignored vulnerabilities. In order to provide the best visibility and most utility to adopters of Backstage, we store these igno
This should remain `ignore` :)

2022-09-20 17:22 UTC, tusharxoxoxo commented on SECURITY.md
> +To work around this and other similar issues, Snyk provides a method to ignored vulnerabilities. In order to provide the best visibility and most utility to adopters of Backstage, we store these igno
ok

2022-09-20 17:28 UTC, tusharxoxoxo commented
my bad

2022-09-21 04:10 UTC, tusharxoxoxo commented
is it right this time??

2022-09-21 05:53 UTC, tusharxoxoxo commented
![Screenshot 2022-09-21 at 11 22 23](https://user-images.githubusercontent.com/79051850/191424868-b23d98db-3f8d-42ef-a270-1b0c35f76f51.jpg)
I checked the git log 
it's showing that it's signed off now

2022-09-21 08:15 UTC, jhaals requested changes
hmm it looks like the DCO signing is not quite right, looks alright from your screenshot, there's probably some commit further back in the chain that is unsigned. The DCO bot suggests that you `git rebase HEAD~6 --signoff` and you have to force push afterwards. Looks like the branch need a rebase too.

If you don't manage to get the CI status green it's probably easier to close this PR and start a new branch from a fresh master.

Good luck! 🙏

2022-09-22 04:57 UTC, tusharxoxoxo commented
2 CI /test and DCO failed

2022-09-22 07:14 UTC, jhaals requested changes
I can still see that some of the earlier commits are not DCO signed and the CI error should be fixed by rebasing. I suggest you open a new PR with newly updated master from the upstream if you are unsure how to update the existing branch

2022-09-22 08:50 UTC, tusharxoxoxo commented
Ok

2022-09-22 08:50 UTC, closed without merging