gitlab oauth: consider hosted gitlab with relative path
backstage/backstage pull request #13855
Opened 2022-09-26 20:09 UTC by OpenSourceZombie

## Hey, I just made a Pull Request!

Fix backstage gitlab oauth callbacks to consider installations with [relative_url](https://docs.gitlab.com/ee/install/relative_url.html)
Originally reported in #8358, specifically [this comment](https://github.com/backstage/backstage/issues/8358#issuecomment-1014316566)
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-09-26 20:23 UTC, Rugvip approved these changes
Oh that's needed indeed! 🎉 Thank you 👍

2022-09-26 21:03 UTC, Rugvip requested changes
Realized I'd like to tweak the changeset at bit

2022-09-26 21:03 UTC, Rugvip commented on .changeset/slow-mirrors-eat.md
> +oauth callbacks to consider installations with relative URL.
```suggestion
Fix GitLab provider setup so that it supports GitLab installations with a path in the URL.
```

2022-09-27 08:48 UTC, OpenSourceZombie commented on .changeset/slow-mirrors-eat.md
> +oauth callbacks to consider installations with relative URL.
Ah, your changes are more descriptive :+1:

2022-09-27 09:08 UTC, Rugvip approved these changes
Nice, thanks! 👍

2022-09-27 09:08 UTC, merged