Handle the error when fetching pod metrics
backstage/backstage pull request #13966
Opened 2022-10-03 07:11 UTC by namco1992

Related to https://github.com/backstage/backstage/issues/13794.

The Kubernetes errors when fetching pod metrics are now captured and returned to the frontend.

Include the `PodStatus` into the `FetchResponse` union type. Now the method `fetchPodMetricsByNamespaces` accepts a set of namespaces and returns a `FetchResponseWrapper`, which is consistent with other public fetch methods.

Signed-off-by: Mengnan Gong <namco1992@gmail.com>

## Hey, I just made a Pull Request!

Currently, the whole endpoint for getting resources fails when it fails to fetch pod metrics, with just an error message "HTTP request failed" which doesn't help much.

Since the `fetchObjectsForService` in the fetcher already has a proper error handling mechanism, I think it's good to unify the fetch methods to have a consistent error handling and return type.

The appearance of the error is similar to https://github.com/backstage/backstage/issues/13794, but it's a different cause and the change in this PR is relatively isolated from what might be changed in #13794, so I decided to open a new PR. 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-10-03 07:16 UTC, namco1992 commented
Not sure if I should ping @mclarke47 here too 😳 .

This is a draft PR, my original thought was just handling the error when fetching pod metrics, but the change ends up bigger than I expected, and also includes some type and signature changes.

I'm not sure if it's an ideal way to do it, or if there is a better way, so I marked this PR as a draft. If the maintainers feel ok about it, I will polish it a bit and add more tests.

2022-10-06 19:31 UTC, jamieklassen requested changes
When I run a kind cluster locally and I `kubectl apply -f backstage.yml` where `backstage.yml` is:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
```
and I have `app-config.local.yaml`:
```yaml
kubernetes:
  clusterLocatorMethods:
    - type: config
      clusters:
        - url: https://127.0.0.1:<port of kind apiserver>
          name: kind
          authProvider: serviceAccount
          serviceAccountToken: <token for SA with the role at https://backstage.io/docs/features/kubernetes/configuration#role-based-access-control>
          skipTLSVerify: true
catalog:
  locations:
    - type: file
      target: ../../kubernetes.yaml
```
and `kubernetes.yaml` is:
```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-backstage
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=backstage'
spec:
  type: service
  lifecycle: stable
  owner: user:guest
```
and I run `yarn dev` and open http://localhost:3000/catalog/default/component/demo-backstage/kubernetes, the code on master shows me:
![Screen Shot 2022-10-06 at 3 21 18 PM](https://user-images.githubusercontent.com/22056320/194401922-11dc9fac-4214-464e-a4bc-9ead5e2e0149.png)

but if I do the same thing with the code  on this PR I see:
![Screen Shot 2022-10-06 at 3 25 12 PM](https://user-images.githubusercontent.com/22056320/194402006-2fa21f26-6c20-49c4-879c-d458cfa2ca6a.png)

Now that's much more pleasant to look at, but my kind cluster doesn't have metrics-server installed and when I look in the logs I see lines like

```text
[1] <timestamp> kubernetes warn statusCode=404 for resource /apis/metrics.k8s.io/v1beta1/namespaces/default/pods body=["404 page not found\n"] type=plugin
```

I'd like to see that 404 appear somewhere instead of seeing the jolly "Nice! No errors to report!" message. I haven't deeply investigated why this is, but I figure I'd mention it ASAP.

2022-10-06 21:24 UTC, jamieklassen commented on plugins/kubernetes-backend/src/service/KubernetesFanOutHandler.ts
> +    result.errors.concat(podMetrics.errors);
OK I figured out the problem. From [these docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat),

> The `concat()` method is used to merge two or more arrays. This method does not change the existing arrays, but instead returns a new array. 

so it would make more sense to have

```suggestion
    result.errors = result.errors.concat(podMetrics.errors);
```

or similar, whatever style feels right. I'd say an error case in the unit tests KubernetesFetcher is required as well.

2022-10-07 02:16 UTC, namco1992 commented on plugins/kubernetes-backend/src/service/KubernetesFanOutHandler.ts
> +    result.errors.concat(podMetrics.errors);
Oh what a rookie mistake! 😂 Thanks for spotting this @jamieklassen. 

>  I'd say an error case in the unit tests KubernetesFetcher is required as well.

Totally, the truth is that we don't even have test cases for fetching pod metrics 😂. My intention was to have a POC and see if the community is ok with where I'm heading to. Since both @jhaals and you seem to be in favor of the change, I will definitely add more tests and do a few e2e tests on my local to make sure it works as intended.

2022-10-09 13:56 UTC, namco1992 commented on plugins/kubernetes-backend/src/service/KubernetesFetcher.ts
> -export interface Clients {
I removed this interface as it's not used anywhere, I hope it won't cause any problems 😳 .

2022-10-09 13:58 UTC, namco1992 commented
Hi @jhaals @jamieklassen,

I've fixed the error appending and added unit tests for both the fetcher and fanout handler, pls help review again! Thank you!

2022-10-17 12:38 UTC, namco1992 commented
@jhaals @jamieklassen Friendly ping 😳.

2022-10-17 13:02 UTC, mclarke47 approved these changes
lgtm

2022-10-19 08:55 UTC, jhaals approved these changes
Thanks for this PR and your patience!

2022-10-19 08:55 UTC, merged