Added emptyContent to properties of Catalog Table
backstage/backstage pull request #14003
Opened 2022-10-05 13:25 UTC by Irma12

Signed-off-by: irma12 <irma@roadie.io>

## Hey, I just made a Pull Request!

Currently we cannot customise empty content, add customised message, component or similar, when there are not entities loaded in Catalog. Think we probably can pass this prop so it is usable in a same way as in other tables,

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-10-17 14:59 UTC, Rugvip requested changes
Thank you, makes sense! 👍 

Just a minor concern

2022-10-17 14:59 UTC, Rugvip commented on plugins/catalog/src/components/CatalogTable/CatalogTable.tsx
> +  },
I wonder if this styling is perhaps a bit too opinionated, should we leave it to the content instead? Especially since it's not possible to override

2022-10-17 18:26 UTC, Rugvip approved these changes
Great, thank you! :shipit:

2022-10-17 18:41 UTC, merged

2022-10-18 16:58 UTC, suuus commented
Thank you for contributing during Hacktoberfest 🍂! You can claim the Backstage Hacktoberfest Holopin at https://bck.st/hacktoberfest-holopin 🙌🏻