Set searchTooltip to Filter
backstage/backstage pull request #14116
Opened 2022-10-12 21:40 UTC by awanlin

Signed-off-by: Andre Wanlin <67169551+awanlin@users.noreply.github.com>

## Hey, I just made a Pull Request!

Set the `searchTooltip` to "Filter" to follow how the `searchPlaceholder` is set making this more consistent

![Screen Shot 2022-10-12 at 4 39 24 PM](https://user-images.githubusercontent.com/67169551/195453180-531a279c-d3c9-4cd8-a503-0370abc3b918.png)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-10-12 21:41 UTC, awanlin commented
@kuangp can you confirm that doing this people can still override it?

2022-10-12 22:43 UTC, kuangp commented
> @kuangp can you confirm that doing this people can still override it?

hm I believe so, if they pass in the `localization` prop, they should be able to override the default settings here via the `restProps` destructuring: https://github.com/backstage/backstage/pull/14116/files#diff-79e85773470f382e49d81f9084274aaeaaa29cfd1025843a35536d686d068731R522

2022-10-13 11:41 UTC, awanlin commented
@jhaals not sure why the tests are failing, any chance you could trigger them again, please?

2022-10-18 08:33 UTC, jhaals requested changes
👋 

I did retrigger the tests, I believe this is might be related to the change?

Looks like this `expect` fails currently
```
expect(await rendered.findByTitle('Search')).toBeInTheDocument();
```

2022-10-19 08:36 UTC, jhaals approved these changes
Thanks! Looking good now 👍 

Test updates does not require changesets as they're not published to npm

2022-10-19 08:36 UTC, merged

2022-10-19 11:42 UTC, awanlin commented
Awesome, thanks again @jhaals