Update Readme.md
backstage/backstage pull request #14257
Opened 2022-10-20 14:26 UTC by Saikatssd

Fixed some typos. Please Review.

    What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
    Docs Update
    Why was this change needed? (You can also link to an open issue here)
    To improve the quality of documentation.
    Other information:

2022-10-20 14:30 UTC, awanlin requested changes
Hi @Saikatssd, thanks for the contribution. Just left a comment about one of the changes

2022-10-20 14:30 UTC, awanlin commented on README.md
> +[Backstage](https://backstage.io/) is an open platform for building developer portals. Powered by a centralized software catalogue, Backstage restores order to your microservices and infrastructure a
This probably shouldn't be changed. Catalog is the term used in all the docs and code.

2022-10-21 07:37 UTC, Rugvip approved these changes
Thanks! 🎉

2022-10-21 07:37 UTC, merged

2022-10-24 20:53 UTC, suuus commented
Thank you for contributing during Hacktoberfest 🍂! You can claim the Backstage Hacktoberfest Holopin at https://bck.st/hacktoberfest-holopin 🙌🏻