Fix GitHub callback URL documentation
backstage/backstage pull request #14368
Opened 2022-10-27 23:11 UTC by jgrumboe

## Hey, I just made a Pull Request!

This fixes #14360 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-10-30 22:20 UTC, jgrumboe commented
@freben could you have a look at this PR, please, if something is missing or it's fine?
Thanks

2022-11-02 12:28 UTC, Rugvip requested changes
Thanks! Just a minor tweak

2022-11-02 12:28 UTC, Rugvip commented on plugins/auth-backend/README.md
>     1. Set this to `http://{APP_FQDN}:{APP_BACKEND_PORT}/api/auth/github` for non-local deployments.
This one should be updated as well

2022-11-02 12:33 UTC, jgrumboe commented on plugins/auth-backend/README.md
>     1. Set this to `http://{APP_FQDN}:{APP_BACKEND_PORT}/api/auth/github` for non-local deployments.
Thanks, good catch.

2022-11-02 12:39 UTC, jgrumboe commented on plugins/auth-backend/README.md
>     1. Set this to `http://{APP_FQDN}:{APP_BACKEND_PORT}/api/auth/github` for non-local deployments.
@Rugvip fixed

2022-11-02 12:57 UTC, Rugvip approved these changes
🎉 , let's :shipit: !

2022-11-02 12:57 UTC, merged

2022-11-24 14:53 UTC, suuus commented
Thank you for contributing during Hacktoberfest 🍂! You can claim the Backstage Hacktoberfest Holopin at https://bck.st/hacktoberfest-holopin 🙌🏻