Adress workflow warnings
backstage/backstage pull request #14376
Opened 2022-10-28 15:22 UTC by kevinneville

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-10-28 18:52 UTC, freben commented
Hi! Are the double quotes a personal preference or is it an actual enhancement? We have single quotes pretty commonly set in our editors I think, so wanted to check if it really was a necessary change

2022-10-28 18:53 UTC, freben commented
(Also, remember that you have to DCO sign all commits - the automated comment above has some more info)

2022-10-28 20:35 UTC, kevinneville commented
> Hi! Are the double quotes a personal preference or is it an actual enhancement? We have single quotes pretty commonly set in our editors I think, so wanted to check if it really was a necessary change

Nope, I don't think it is needed, it was some automated lining and formating from my side. I dropped that commit now.

2022-10-28 20:36 UTC, kevinneville commented
> (Also, remember that you have to DCO sign all commits - the automated comment above has some more info)

I think I have already done that. Or do I need to do something more.
```
Author: Kevin Neville <kevin@neville.se>
Date:   Fri Oct 28 17:21:49 2022 +0200

    remove deprecated set-output commands
    
    Signed-off-by: Kevin Neville <kevin@neville.se>
```

2022-10-29 19:41 UTC, Rugvip requested changes
Nice, thank you! 👍

2022-10-29 19:41 UTC, Rugvip commented on .github/workflows/pr-review-comment.yaml
> +            console.log(`pr-number=${prNumber} >> $GITHUB_OUTPUT`);
This doesn't work does it? I'm assuming we need to append to the file instead

2022-10-29 19:41 UTC, Rugvip commented on scripts/check-if-release.js
> +    console.log(`needs_release=false >> $GITHUB_OUTPUT`);
Same thing with the rest of these

2022-11-18 00:25 UTC, closed without merging