Added Affinidi to adopters
backstage/backstage pull request #15092
Opened 2022-12-07 16:43 UTC by idestis

2022-12-08 09:04 UTC, djamaile commented
Welcome 👋 !!

We need the DCO sign off before we can merge it 😄

2022-12-08 10:40 UTC, freben commented on ADOPTERS.md
> +| [Affinidi](https://affinid.com) | [Dmytro Shamenko](https://github.com/idestis), [Denis Fastovets](https://www.linkedin.com/in/denis-fastovets/) | The Backstage is used in the company to enhance de
Hey, it seems you forgot the last "i" in the company URL here.

2022-12-08 11:37 UTC, idestis commented
> And the DCO again! :) Sorry for the trouble.

done

2022-12-08 12:22 UTC, djamaile submitted a review, later dismissed

2022-12-08 12:25 UTC, djamaile requested changes
Seems like your local formatting tool brought some unnecessarily changes. Lets revert that 😄

2022-12-08 14:12 UTC, idestis commented
> Seems like your local formatting tool brought some unnecessarily changes. Lets revert that 😄

My bad, sorry for this. Reverted and fixed only URL in my line with DCO.

2022-12-08 14:44 UTC, djamaile requested changes

2022-12-08 14:44 UTC, djamaile commented on ADOPTERS.md
> +in the company to enhance development acceleration inside of the company and helps us keep the house in order, from cost efficiency and up to accountability.
Almost there! You have a enter here which makes these last lines fall in their own table cell. So, if you do some backspaces then we should be fine 😄

2022-12-08 17:25 UTC, idestis commented
@djamaile finally I did all changes :)

2022-12-08 17:53 UTC, djamaile approved these changes
Welcome, again :)

2022-12-08 20:10 UTC, idestis commented
Now we have to wait for @freben to review additionally. I hope he will like it :)

2022-12-11 15:19 UTC, freben approved these changes
Not just like it, I love it!

2022-12-11 15:19 UTC, merged