Add links in README to reference Sonarqube FE/BE
backstage/backstage pull request #15193
Opened 2022-12-12 22:02 UTC by scprek

## Hey, I just made a Pull Request!

The doc link from Backstage.io plugins sonarqube lead to the Frontend readme https://github.com/backstage/backstage/blob/master/plugins/sonarqube/README.md. Although it's probably common knowledge to always check if there's a backend element of the plugin, adding links to the READMEs help new users.

#### :heavy_check_mark: Checklist

- [ ] Added or updated documentation
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-12-13 08:33 UTC, OrkoHunter approved these changes
Thanks!

2022-12-13 08:34 UTC, OrkoHunter commented
> Thanks for the contribution! All commits need to be DCO signed before they are reviewed. Please refer to the the [DCO section in CONTRIBUTING.md](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) or the [DCO](https://github.com/backstage/backstage/runs/10048832441) status for more info.

@scprek Just a tiny change required to amend and sign the commit. :)

2022-12-13 08:35 UTC, OrkoHunter submitted a review, later dismissed
Needs DCO update.

2022-12-19 13:11 UTC, Rugvip requested changes
Thank you! 👍 

We'll need changesets as well for this to get released, see https://github.com/backstage/backstage/pull/15193#issuecomment-1347404674

2022-12-19 14:46 UTC, scprek commented
@Rugvip fixed it. I initially signed with my personal user and that wasn't working, so just used my work one.

2022-12-19 15:32 UTC, scprek commented
> Thank you! 👍
> 
> We'll need changesets as well for this to get released, see [#15193 (comment)](https://github.com/backstage/backstage/pull/15193#issuecomment-1347404674)

@Rugvip fixed

2022-12-19 15:36 UTC, Rugvip approved these changes
Thanks! 👍 

I tweaked it a bit to make it a bit more oriented towards the changelog reader

2022-12-19 15:36 UTC, Rugvip commented on .changeset/witty-phones-chew.md
> +Sonarqube doc change to link FE/BE changes needed
```suggestion
Added links to the frontend and backend plugins in the readme.
```

2022-12-19 15:57 UTC, merged