zcason/feature flag filter fix
backstage/backstage pull request #15437
Opened 2022-12-28 00:12 UTC by zcason

Signed-off-by: zcason <a-zcason@expediagroup.com>

## Hey, I just made a Pull Request!

I rewrote the feature flag filter functionality, it was broken previously.

![feature-flag-fix](https://user-images.githubusercontent.com/62040057/209737553-e21da146-4edf-4f28-bdc9-17a3840b5d0b.png)

<img width="1502" alt="Screen Shot 2022-12-27 at 6 06 00 PM" src="https://user-images.githubusercontent.com/62040057/209738453-a86c42da-2c5c-40e8-8666-5d16b2797ef2.png">

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2022-12-28 13:18 UTC, Rugvip reviewed
Thanks! I think the filter was intended to work a bit differently before, but I think this makes sense tbh, is more in line with what one would expect, and is simpler.

Could you add a changeset as well, it's needed for this to be released? See the comment above for details.

Would be lovely to add some tests as well if you're in the mood :grin:

2022-12-28 16:51 UTC, zcason commented
> Thanks! I think the filter was intended to work a bit differently before, but I think this makes sense tbh, is more in line with what one would expect, and is simpler.
> 
> Could you add a changeset as well, it's needed for this to be released? See the comment above for details.
> 
> Would be lovely to add some tests as well if you're in the mood 😁

Sure thing! I will ping you when once it's finished. Thank you for the feedback.

2022-12-29 15:36 UTC, Rugvip requested changes

2022-12-29 15:36 UTC, Rugvip commented on .changeset/loud-beds-occur.md
> +'@backstage/plugin-user-settings': major
Let's make this a `patch` bump. There's no API change and I'd consider the behavior change a fix.

2023-01-04 09:24 UTC, Rugvip approved these changes
Nice, thank you! 👍 

Let's :shipit: 🎉

2023-01-04 09:24 UTC, merged