backend-common: Remove read method from UrlReader
backstage/backstage pull request #15506
Opened 2023-01-02 15:36 UTC by jhaals

**BREAKING**: Removed deprecated `read` method from the `UrlReader` interface. All implementations should use the `readUrl` method instead.

Migrated `UrlReader` and related types to `backend/backend-plugin-api`, types remain re-exported from `backend-common` for now.

2023-01-02 16:53 UTC, OrkoHunter reviewed
Nice! This [docs page](https://backstage.io/docs/plugins/url-reader) will need some of line removals too. :)

2023-01-02 16:53 UTC, OrkoHunter commented on packages/backend-plugin-api/src/services/definitions/urlReaderServiceRef.ts
> +   * Use this as the read method will be removed in a future release.
It's gone now! 😁

2023-01-03 09:22 UTC, jhaals commented on packages/backend-plugin-api/src/services/definitions/urlReaderServiceRef.ts
> +   * Use this as the read method will be removed in a future release.
Thanks! ❤️

2023-01-03 09:29 UTC, jhaals commented
Thanks @OrkoHunter for pointing out the docs and tsdoc, I've addressed your comments

2023-01-03 10:00 UTC, iamEAP approved these changes

2023-01-03 10:58 UTC, Rugvip requested changes
Nice! 😁 

Just need a changeset for `@backstage/plugin-catalog-backend-module-openapi`

2023-01-03 12:27 UTC, Rugvip approved these changes
:shipit:

2023-01-03 13:13 UTC, merged