feat: extend Kubernetes AWS auth to allow specifying `clusterName` in addition to `name/displayName`
backstage/backstage pull request #15683
Opened 2023-01-11 07:40 UTC by cyrus-mc

## Hey, I just made a Pull Request!

Pull request to address https://github.com/backstage/backstage/issues/15668. When configuring EKS clusters it helps to have the display name differ from the cluster name used to generate bearer token.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-01-11 07:45 UTC, cyrus-mc commented
Fairly new to the Backstage ecosystem. Not exactly sure how I can test this locally. The change is pretty trivial but as of yet I haven't validated that it works as expected.

2023-01-11 07:46 UTC, cyrus-mc commented on plugins/kubernetes-backend/src/kubernetes-auth-translator/AwsIamKubernetesAuthTranslator.ts
> -      clusterDetails.name,
Maintains backwards compatibility. If `clusterName` isn't supplied default to the original `name` setting.

2023-01-17 09:46 UTC, sydorovdmytro commented
I'm a bit curious what is the difference between this PR and 2 rejected ones? 
https://github.com/backstage/backstage/pull/14681
https://github.com/backstage/backstage/pull/14712

2023-01-17 19:09 UTC, mclarke47 commented
Thanks for the PR! 

As @sydorovdmytro pointed out this seems similar to some previous PRs that were closed because we think we need an RFC. Perhaps you could get involved with these other contributors and see how we could fix this?

2023-02-11 15:21 UTC, Rugvip requested changes
Just want to echo @mclarke47. I think we need look for a less patchy solution to this and have something that just works out of the box.

2023-02-23 15:29 UTC, closed without merging