add entity labels card
backstage/backstage pull request #15706
Opened 2023-01-11 15:09 UTC by punkle

## Hey, I just made a Pull Request!

add entity labels card that looks like this.

```typescript jsx
    <EntitySwitch>
      <EntitySwitch.Case if={hasLabels}>
        <Grid item md={4} xs={12}>
          <EntityLabelsCard />
        </Grid>
      </EntitySwitch.Case>
    </EntitySwitch>
```

<img width="664" alt="image" src="https://user-images.githubusercontent.com/553697/211842325-5ffada93-a1dd-48fa-9b9c-0d1b87cb676d.png">

If the entity does not have labels it looks like this

<img width="657" alt="image" src="https://user-images.githubusercontent.com/553697/211842516-9b13987d-217e-478d-8646-07ae2dac0a97.png">

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-01-11 17:40 UTC, jcarres-mdsol commented
As a backstage user, I would not add this card because the "no label" state of the card is a little scary. People may think they have done something wrong as labels are missing.

Maybe there should be a `hasLabel` function so people could choose if they want to not display the component if there is no labels?

2023-01-11 17:55 UTC, awanlin commented
@jcarres-mdsol it doesn't look like it's being added to new instances created using `npx @backstage/create-app@latest` and existing installs would need to add it manually. Finally this is the same text used on various card, for example Links:

![image](https://user-images.githubusercontent.com/67169551/211881517-5576d53b-10c4-4272-808b-b2419abf1ff3.png)

This was taken from there demo site here: https://demo.backstage.io/catalog/default/component/playback-order

2023-01-11 18:14 UTC, jcarres-mdsol commented
I guess in my particular case I know (due to a processor) that we will always have links so never worried about this while I know labels may or may not be present.
I still think in general would be nice if the empty case in any of these components could be either "point to what's missing" or "do not render if not data available". I think that would be more flexible but probably this is outside the scope of this particular component.

2023-01-11 21:17 UTC, punkle commented
I can add a boolean function like entityHasLabels if it helps. But you can also choose to just not add the card.

2023-01-12 08:02 UTC, punkle commented
@jcarres-mdsol Ive added a hasLabels entity switch function. Hope that helps.

2023-01-12 08:55 UTC, UsainBloot commented
To once again compare this to the "Links" component, what do you think to dropping the word Entity from the title of the card, so it is just "Labels"?

2023-01-12 12:16 UTC, jhaals requested changes
Looks good to me, just one changeset to remove and then we're good to go.

2023-01-12 12:16 UTC, jhaals commented on .changeset/forty-ligers-teach.md
> +Add labels to one of the example entities.
It does not look like the examples dir is published as part of the package when I look at package.json so we can skip this changeset completely :)

2023-01-12 12:59 UTC, jhaals approved these changes

2023-01-12 13:00 UTC, jhaals requested changes

2023-01-12 13:00 UTC, jhaals commented on plugins/catalog/src/components/EntityLabelsCard/EntityLabelsEmptyState.tsx
> +export type EntityLabelsEmptyStateClassKey = 'code';
Hmm where is this used?

2023-01-12 13:15 UTC, punkle commented on plugins/catalog/src/components/EntityLabelsCard/EntityLabelsEmptyState.tsx
> +export type EntityLabelsEmptyStateClassKey = 'code';
Its not used and it can be deleted.

2023-01-12 13:19 UTC, jhaals requested changes

2023-01-12 13:19 UTC, jhaals commented on plugins/catalog/src/components/EntityLabelsCard/EntityLabelsEmptyState.tsx
> +/** @public */
I think you forgot to delete this line as well 😄

2023-01-12 14:53 UTC, punkle commented
I dont think the failure here is related to my change.

2023-01-13 14:08 UTC, jhaals approved these changes
Looking good 👍

2023-01-13 14:08 UTC, merged