add template replace option
backstage/backstage pull request #15791
Opened 2023-01-17 10:10 UTC by pitwegner

Signed-off-by: pitwegner <pit.wegner@gmail.com>

## Hey, I just made a Pull Request!

Allow the `fetch:template` action to overwrite existing files. This is useful for adding changes to an existing git repo.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-01-17 12:36 UTC, pitwegner commented
Not sure how to test this with the current testing framework. seems like there is no way to specify already existing files in the working directory.

2023-01-17 12:56 UTC, benjdlambert commented
Hey :wave: thanks for this!

For testing we use `mock-fs`, and I think what you will want to do is add a record to this object which has the key of the path in the workspace and the contents as the value. 

https://github.com/backstage/backstage/blob/fe3e4bfcf4852856fea76af526b08d19143158cf/plugins/scaffolder-backend/src/scaffolder/actions/builtin/fetch/template.test.ts#L98-L100

And then assert that when replace is false it's the same value and when replace is true it replaced the contents of it.

Some more docs on [mock-fs](https://github.com/tschaub/mock-fs)

2023-01-18 09:33 UTC, benjdlambert requested changes
Just one thing about the changeset and I think we're good to go! :pray:

2023-01-18 09:33 UTC, benjdlambert commented on .changeset/perfect-cheetahs-serve.md
> +'@backstage/plugin-scaffolder-backend': patch
Should be a minor change as this package is `>1.0.0` :pray:

2023-01-18 10:16 UTC, benjdlambert approved these changes

2023-01-18 10:16 UTC, benjdlambert commented
Nice! Thanks for this!

2023-01-18 10:16 UTC, merged