Entity Feedback Plugin
backstage/backstage pull request #15881
Opened 2023-01-21 04:25 UTC by kuangp

Signed-off-by: Phil Kuang <pkuang@factset.com>

_New year, new plugin_ 🎉 

### Introducing the Entity Feedback plugin!

This simple plugin allows you to rate the quality of entities in your Backstage catalog. Why would you want to rate entities you ask? As a new adopter your first big hurdle might be building out your software catalog and ensuring your content is correct and up to date. Allowing your users to rate entities brings them into the feedback loop that can help notify owners if something is wrong with their entity (ie. taking inspiration of the feedback model of TechDocs 😁). 

https://user-images.githubusercontent.com/6998196/213843150-d9a3dac5-cf23-4a90-bfb0-f7a83194d6d0.mov

### Future Work / Enhancement Ideas
- Additional rating types
- Displaying historical data (rating changes over time)
- Hooking up the permissions framework
- Support for anonymous feedback
- Cleaning up "orphaned rating data" from deleted entities
- Incorporating rating data into ranking of entities in search results (this would be pretty cool)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-01-31 15:00 UTC, kuangp commented
shoo stale bot 😠

2023-01-31 21:41 UTC, camilaibs reviewed
I easily see the rate incorporated in the search results score 🤩

2023-02-12 23:14 UTC, Rugvip requested changes
Sweet 😁 🎉 

Loving the additions on top of 👍 / 👎  to make the feedback more valuable

Just some small nits.

Btw, do you mind adding yourself as codeowner of the packages as well? Just to keep track of it for now, but hopefully not too long now before it actually has an effect 😁 Will ofc ask again at that point

2023-02-12 23:14 UTC, Rugvip commented on plugins/entity-feedback-common/src/index.ts
> +export interface Response {
Wonder if it might be better to call this `FeedbackResponse` or smth like tha?, there's some pretty direct overlap here 😅

2023-02-13 14:21 UTC, kuangp commented on packages/app/src/components/catalog/EntityPage.tsx
> +        <LikeDislikeButtons />
so the motivation behind this is to allow it to be more customizable in where the consumer wants to render these buttons. eg. internally we created a custom `AboutCard` and put the buttons there (AFAIK the API for a customizable `AboutCard` is still unsettled so wasn't sure if I should include in the demo app in that manner as an example):

![Screen Shot 2023-02-13 at 9 18 41 AM](https://user-images.githubusercontent.com/6998196/218482665-d0b826a8-ef25-4c4b-aec2-ff747228768c.png)

2023-02-13 14:32 UTC, Rugvip commented on packages/app/src/components/catalog/EntityPage.tsx
> +        <LikeDislikeButtons />
yep figured x), yeah it's really quite a lot nicer to have it on the `AboutCard`. Perhaps it's even worth calling it out in the README? Alright, let's leave as is

2023-02-13 17:51 UTC, kuangp commented
@Rugvip updated! thanks for taking the time to review!

2023-02-13 20:32 UTC, Rugvip approved these changes
Thank you! 😁 

Let's :shipit: 🎉

2023-02-13 20:32 UTC, merged