feat: add support for MADR v3
backstage/backstage pull request #16491
Opened 2023-02-21 11:31 UTC by gaurav517

## Hey, I just made a Pull Request!

Support parsing of [MADR v3 Format ](https://raw.githubusercontent.com/gaurav517/backstage/master/packages/catalog-model/examples/adrs/0003-madr-v3.md)

https://github.com/backstage/backstage/issues/16437

<img width="356" alt="image" src="https://user-images.githubusercontent.com/15346341/219867848-7e7acb3c-b09f-46c2-87e8-ef7e0591e6a4.png">

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-02-21 12:59 UTC, freben reviewed
Nice! Just a small tweak or two

2023-02-21 12:59 UTC, freben commented on .changeset/rich-ladybugs-punch.md
> +'@backstage/plugin-adr-backend': minor
Nonbreaking changes in 0.x packages can be `patch`

2023-02-21 20:03 UTC, kuangp requested changes
My thoughts here is that maybe instead of overloading the default `mdrParser` to support 2 major versions, we ship separate parsers for MADRv2 and MADRv3. That way we can keep the parsing logic a little more organized and isolated. 

We can probably do this by updating [`MadrParserOptions`](https://github.com/backstage/backstage/blob/master/plugins/adr-backend/src/search/createMadrParser.ts#L42-L53) for `createMadrParser` to include an additional option to specify spec version and [apply the appropriate parser](https://github.com/backstage/backstage/blob/master/plugins/adr-backend/src/search/createMadrParser.ts#L67) accordingly. If we want to keep this a non-breaking change, we can default to using the current v2 parser implementation

2023-02-26 07:47 UTC, gaurav517 commented on ADOPTERS.md
> -| Organization                                                                | Contact
My editor auto formats! will fix it.

2023-02-26 07:48 UTC, gaurav517 commented on plugins/adr-backend/src/search/madrParser.ts
> +  let adrStatus: string | undefined;
Will fix it inline with @kuangp's suggestion.

2023-02-26 09:43 UTC, freben commented
@kuangp Not to be selected hard-coded upfront though right? It'd be nice if we could register several parsers and they each get a go at the source data to detect whether they are able to understand it.

2023-02-26 09:45 UTC, gaurav517 commented
I pushed a changed based on @freben's feedback and did some related refactors.

About @kuangp's idea, there are few things to consider/discuss:
1. Looks like `madrParserOptions` is currently [not in use](https://github.com/backstage/backstage/blob/8006f8a602bb862c818715b8596d627fec7f296f/plugins/adr-backend/src/search/DefaultAdrCollatorFactory.ts#L117). We can use that and introduce an option for `version` but then it won't work well for organisations where some repos are using `v2` and some are using `v3` versions, as we would only be able to specify a specific version at backstage instance level: 
```
DefaultAdrCollatorFactory.fromConfig({
  adrVersions: v3 // this will break all v2 ADRs.
})
```
2. We can possibly overcome point-1 by having an additional annotation for adr version. e.g. `backstage.io/adr-version`, defaulting to `v2`. So that users can specify ADR versions at repo level. It would work assuming they won't be mixing versions in a repo. But thats a broader change in `DefaultAdrCollatorFactory`.

I am wondering whether we should just go ahead with current changes and come back to thinking about it later when we have another MADR version released? Supporting 2 versions by one parser is still not too bad atm. Please share your ideas. Thanks.

2023-02-26 15:46 UTC, kuangp commented
> I am wondering whether we should just go ahead with current changes and come back to thinking about it later when we have another MADR version released? Supporting 2 versions by one parser is still not too bad atm. Please share your ideas. Thanks.

sure, I'm ok with that! @freben also makes a good point about potentially supporting a collection of parsers (not just MADR) to attempt to interpret the data but we can definitely revisit that later. Change looks good on my end, thanks for the contribution 🙂

2023-02-26 15:46 UTC, kuangp approved these changes

2023-02-26 23:37 UTC, gaurav517 commented
Great. Thanks. Then looks like its ready to ship. @freben :)

2023-03-03 15:11 UTC, freben approved these changes
Alright!

2023-03-03 15:12 UTC, merged