[GitlabDiscoveryEntityProvider] add config to distinguish between `branch` and `fallbackBranch`
backstage/backstage pull request #16502
Opened 2023-02-21 15:16 UTC by Andy2003

* A new config option `fallbackBranch` is added to the GitlabDiscoveryEntityProvider, to define the branch to use , if there is no default branch configured at the repository
* The existing `branch` configuration is now used to explicitly set the branch to look up the catalog-info

resolves #13587

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-02-22 14:32 UTC, jhaals requested changes
Thanks for the PR!

Would we be able to first do a deprecation of this functionality to give people some heads up as suggested by [Rugvip in the referenced issue](https://github.com/backstage/backstage/issues/13587#issuecomment-1367258863)?

2023-02-22 14:32 UTC, jhaals commented on .changeset/fresh-schools-fly.md
> +'@backstage/plugin-catalog-backend-module-gitlab': major
```suggestion
'@backstage/plugin-catalog-backend-module-gitlab': minor
```

Major releases of packages is only something we do in rare cases and that will bring the package up to a stricter versioning policy. This package is on version 0.x which means breaking changes can occur in minor releases.

2023-02-22 14:32 UTC, jhaals commented on plugins/catalog-backend-module-gitlab/src/lib/types.ts
> +   * The name of the branch to be used, to search for catalog-info
```suggestion
   * The name of the branch to be used, to search for catalog files
```

It's not strictly required to name them catalog-info

2023-02-22 14:32 UTC, jhaals commented on plugins/catalog-backend-module-gitlab/src/lib/types.ts
> +   * to load the catalog-info.
```suggestion
   * to discover catalog files.
```

2023-03-02 16:27 UTC, Andy2003 commented
Do not close this PR, it needs to be merged after [`1.12.0` release](https://github.com/backstage/backstage/pull/16545#issuecomment-1443668304)

2023-03-03 09:27 UTC, jhaals commented
Adding a will-fix label on this one to prevent dependabot from closing. Let's rebase and fix it up once we completed the 1.12.0 release 👍

2023-03-18 16:43 UTC, Andy2003 commented
@jhaals 

> Let's rebase and fix it up once we completed the 1.12.0 release 

done

2023-03-20 10:41 UTC, jhaals requested changes
Thanks for keeping this alive :)

Small tweak to highlight but otherwise looking good!

2023-03-20 10:41 UTC, jhaals commented on .changeset/fresh-schools-fly.md
> +The configuration of the `GitlabDiscoveryEntityProvider` has changed as follows:
```suggestion
**BREAKING**: The configuration of the `GitlabDiscoveryEntityProvider` has changed as follows:
```

2023-03-20 10:41 UTC, jhaals commented on docs/integrations/gitlab/discovery.md
> +        branch: main # Optional. Used to discover on a concrete branch
```suggestion
        branch: main # Optional. Used to discover on a specific branch
```

2023-03-20 13:45 UTC, jhaals approved these changes
Nice work with this Andy! 👏 👏

2023-03-20 13:45 UTC, merged