Add .eslintignore file with **/public/** to create-app
backstage/backstage pull request #16630
Opened 2023-02-28 00:07 UTC by taras

## Hey, I just made a Pull Request!

Follow up to https://github.com/backstage/backstage/issues/16571

#### :heavy_check_mark: Checklist

- x ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-03-01 09:52 UTC, benjdlambert commented
Hmm it's a little unfortunate that this catches everything called `public`. Can we lock it down a little further and be more opinionated and then if people change they can update this path too?

2023-03-01 14:13 UTC, taras commented
@benjdlambert what about `packages/app/public`?

2023-03-02 10:02 UTC, benjdlambert commented
@taras thinking that we make a `packages/app/.eslintignore` with `public` in it instead? Feels a little nicer that way?

2023-03-07 21:29 UTC, taras commented
@benjdlambert good idea, done!

2023-03-08 07:51 UTC, benjdlambert requested changes
Nice, just smol nit about changeset.

2023-03-08 07:51 UTC, benjdlambert commented on .changeset/witty-squids-fetch.md
> +
Probably just wanna change this changeset a little bit to be more reflective of the actual change now.

2023-03-08 21:09 UTC, benjdlambert approved these changes

2023-03-08 21:09 UTC, merged