[Docs] Kubernetes - Adds AWS authentication example
backstage/backstage pull request #16753
Opened 2023-03-07 21:58 UTC by askmeegs

## Hey, I just made a Pull Request!

Adds AWS authentication information, and a configuration snippet, for the Backstage Kubernetes plugin. https://backstage.io/docs/features/kubernetes/authentication#server-side-providers

Closes https://github.com/backstage/backstage/issues/16677 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-03-08 14:23 UTC, jamieklassen approved these changes
LGTM, nice! I've sometimes heard the access-key/secret-access-key/session-token together described as ["AWS security credentials"](https://docs.aws.amazon.com/general/latest/gr/aws-security-credentials.html). Not saying I have any problem with "IAM keys", though; in my experience these are always things I have gotten from the ["access keys"](https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-about) section of the  IAM panel.

2023-03-08 17:24 UTC, askmeegs commented
Thanks for the guidance Jamie, updated!

2023-03-09 16:55 UTC, jamieklassen approved these changes

2023-03-09 16:56 UTC, Rugvip requested changes
Thank you! 👍 

Just a Q about the config structure

2023-03-09 16:56 UTC, Rugvip commented on docs/features/kubernetes/authentication.md
> +        secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
Is this supposed to be under `aws.accounts` or `aws.mainAccount` instead? per https://github.com/backstage/backstage/blob/master/packages/integration-aws-node/README.md#backstage-app-configuration

As far as I see this config path doesn't exist

2023-04-02 10:04 UTC, closed without merging