Include the failureMetadata and successMetadata in TechInsightsApi
backstage/backstage pull request #16835
Opened 2023-03-13 17:03 UTC by Symbianx

## Hey, I just made a Pull Request!

Adds the `failureMetadata` and `successMetadata` fields to the `Check` returned by the `getAllChecks` API so we can use them to show metadata in the UI.

Also copied over the documentation from the backend code while I was at it.

These fields already exist and are returned by the backend server.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-03-14 09:58 UTC, jhaals requested changes
Thanks for the PR!
I've added some comments, also make sure to update the api-report. See build status for more info

2023-03-14 09:58 UTC, jhaals commented on plugins/tech-insights/src/api/types.ts
> +  successMetadata?: Record<string, any>;
```suggestion
  successMetadata?: Record<string, unknown>;
```

Let's make these unknown instead of any :)

2023-03-14 09:58 UTC, jhaals commented on .changeset/lazy-monkeys-worry.md
> +The Check class now includes the failureMetadata and successMetadata as returned by the runChecks call.
```suggestion
The `Check` type now optionally include the `failureMetadata` and `successMetadata` as returned by the `runChecks` call.
```

2023-03-14 09:58 UTC, jhaals commented on .changeset/lazy-monkeys-worry.md
> +'@backstage/plugin-tech-insights': minor
```suggestion
'@backstage/plugin-tech-insights': patch
```

We can introduce new features as patch as this package is 0.x

2023-03-15 16:47 UTC, Symbianx commented
@jhaals changes applied

2023-03-17 10:47 UTC, jhaals approved these changes
Thank you! 👍

2023-03-17 10:47 UTC, merged