feat(cli): support import of .md files
backstage/backstage pull request #16836
Opened 2023-03-13 20:02 UTC by kuangp

## Hey, I just made a Pull Request!

I would like to be able to import local .md files to load Markdown content eg:
```tsx
import mdContent from './example.md'

...
const content = await fetchApi.fetch(mdContent).then(res => res.text());
...
<MarkdownContent content={content} />
```

Let me know if there's a better way to implement this change. As far as I can tell there's no support for a local rollup config override (eg. auto recognizing a local `rollup.config.js`). Alternatively, let me know if there's interest in opening up this API to allow passing custom config options rather then hardcoding this set of file extensions to support. 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-03-14 12:54 UTC, jhaals requested changes
This seems fine to me.

I'll let @Rugvip also take a look as well

2023-03-14 12:54 UTC, jhaals commented on packages/cli/src/lib/builder/config.ts
> +              /\.md/,
Should end with md right?

```suggestion
              /\.md$/,
```

2023-03-14 13:20 UTC, Rugvip commented
Are you looking to use this in backend or frontend packages? If backend it could be done with assets instead.

If it's for frontend I want to think an extra round about whether this should result in a URL or immediate text content. Iirc it needs to be added to the bundle config too, as well as asset-types.

2023-03-14 13:46 UTC, kuangp commented
> Are you looking to use this in backend or frontend packages? 

I'm currently looking to import this into frontend code

> If it's for frontend I want to think an extra round about whether this should result in a URL or immediate text content

Let me know what you think and/or what additional changes need to be made!

2023-03-21 14:48 UTC, kuangp commented
can someone re-trigger the failed e2e run ? looks like an intermittent error

2023-03-21 15:45 UTC, Rugvip approved these changes
Alright, let's :shipit: 😁 

Thank you! 👍

2023-03-21 15:45 UTC, merged