[Playlist] feat: add dynamic group noun through config
backstage/backstage pull request #16955
Opened 2023-03-18 22:35 UTC by antoniobergas

## Hey, I just made a Pull Request!

I added some config properties for the Playlist plugin to be able to change dynamically the group noun in all UI components

![image](https://user-images.githubusercontent.com/26031467/226143576-5d4aae24-d240-4c0b-99ac-04068d756b90.png)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-03-20 14:05 UTC, kuangp requested changes
cc @benjdlambert if you have some thoughts about this change as it relates to the [RFC](https://github.com/backstage/backstage/issues/16876) you recently opened, specifically regarding doing simple UI text customization in plugins

2023-03-20 15:06 UTC, antoniobergas commented
thanks for the feedback @kuangp I will make the changes as soon as I have some time.

Can you maybe guide me with the test CI issue?
![image](https://user-images.githubusercontent.com/26031467/226381507-e2fcb2a2-ceeb-48ab-ad34-f31ed3d53581.png)

I check locally but don't know why that it's failing

2023-03-20 15:41 UTC, antoniobergas commented on plugins/playlist/config.d.ts
> +    groupPluralNoun: string;
Yeah, having pluralize it will make it easier and title make more sense 👍🏻

2023-03-20 18:35 UTC, antoniobergas commented
I found out that the issue in the test its related to use the new useTitle hook at the same time that the usePlaylistList hook.
![image](https://user-images.githubusercontent.com/26031467/226434401-7398984b-2893-4e0b-a2f6-cd9e46be4376.png)
![image](https://user-images.githubusercontent.com/26031467/226434469-7c60adae-8821-4825-a8bf-fdc45d070092.png)

![image](https://user-images.githubusercontent.com/26031467/226434529-41ee67ad-53a2-478e-a6db-660c62b4a4ec.png)


The tests of usePlaylistList hook its also declaring a configApiRef. I have not that much expertise in React to know why this it's producing an error in the test neither how to fix it. 

If someone can guide me I will appreciate it 😊

2023-03-20 19:20 UTC, antoniobergas commented on plugins/playlist/src/hooks/useTitle.ts
> +export function useTitle(inPlural: boolean, inLowerCase: boolean) {
Make sense! I will make the changes

2023-03-20 20:22 UTC, kuangp approved these changes
Looks good to me! Thanks for the great contribution! 

over to @benjdlambert for maintainers review

2023-03-20 20:33 UTC, antoniobergas commented
Done, I think I am not forgetting anything.

Thanks a lot for the help and the guidance @kuangp 😊

2023-03-24 12:45 UTC, benjdlambert commented
Sorry - just coming round to this now.

Is there a reason for the preference of `config` over a prop to pass in the `plugin` itself? It would just be unfortunate not to follow the current (most probably going to change with #16876) patterns that we have in place for this.

You're right @kuangp that it deffo fits into the i18n category of that RFC, would like to try and follow the patterns that we have to day, even it they are changing :pray:

Thoughts?

2023-03-24 15:36 UTC, kuangp commented
hmm my recommendation of using a config here is same reasons laid out in the RFC regarding prop drilling to multiple various components to do a simple text customization. It's also inspired by the current `app.title` config that allows you to "rebrand" Backstage and in the same manner since this change is about rebranding the "Playlist" term (originally named to follow the Backstage/Spotify naming theme 😄), I thought it made sense to leverage the same mechanism ie. a company will probably rebrand "Backstage" and "Playlists" in a consistent manner to both follow whatever naming theme they wish to use.

2023-03-25 07:43 UTC, antoniobergas commented
I am quite new in Backstage and don't know at all the impact of this.

If I understood correct, there's 3 flavors to pass custom data to plugins right?
- Vía configApi
- Vía props
- Vía i18n (just text data)(in progress)

In a first attepmt I also thought about the props but after kuangp mentioned the configApi, It looks quite more clean solution (and also easy to use from a user perspective)

Which are the pros and cons of each flavor ?

2023-04-01 07:57 UTC, antoniobergas commented
Hi guys! Any suggestions of the next steps for this?

2023-04-02 15:12 UTC, kuangp commented
@benjdlambert thoughts on my reasoning ?

2023-04-04 08:07 UTC, benjdlambert commented
Apologies - had a busy few weeks and just getting back round to this now.

Yeah I see your reasoning @kuangp, it deffo fits into the internationalisation part I think, which I guess is going to come from config eventually. I don't really have a strong opinion to be honest, maybe let's just keep it in config for now then.

I guess we could also use this example as something to drive the i18n part of that RFC too if someone wants to have a stab at that after? :pray:

2023-04-04 08:08 UTC, benjdlambert approved these changes

2023-04-04 08:08 UTC, merged

2023-04-05 06:30 UTC, antoniobergas commented
Thanks @benjdlambert ! I will try to keep an eye to the RFC if we need to adjust it later.

Thanks also @kuangp for guide me 😊