add new scaffolder action to ensure a gitlab group exists
backstage/backstage pull request #16990
Opened 2023-03-21 08:54 UTC by Andy2003

With this action it can be ensured, that a Gitlab group exists.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-03-28 10:15 UTC, Andy2003 commented
Rlease do not close this PR! I wait for the Review!

2023-04-04 14:26 UTC, Andy2003 commented
Still wait for PR review!

@Rugvip can you please reassign this PR, in case you have no time to review it.

2023-04-05 02:39 UTC, manobi commented
This would make my automations so much simples.
Looking forward to see that merged.

2023-04-05 08:39 UTC, Rugvip requested changes
Thank you! 👍 🎉 

Just some minor stuff, sorry it took at while to review

2023-04-05 08:39 UTC, Rugvip commented on plugins/scaffolder-backend-module-gitlab/src/actions/createGitlabProjectAccessTokenAction.ts
> +            .string({ description: 'Access Level of the Token' })
Should be a `number` here right?

2023-04-05 08:39 UTC, Rugvip commented on plugins/scaffolder-backend-module-gitlab/src/actions/createGitlabGroupEnsureExistsAction.ts
> +        )) as any as Array<GroupSchema>;
Perhaps add a comment here since this is quite unexpected, just explaining that the type is actually wildly wrong

2023-04-12 06:21 UTC, Andy2003 commented
@Rugvip any updates on this?

2023-04-19 06:32 UTC, Andy2003 commented
Still wait for PR approval!

2023-04-26 06:55 UTC, Andy2003 commented
Still wait for PR approval!

2023-05-03 08:19 UTC, Andy2003 commented
Still wait for PR approval!

@Rugvip can you please reassign this PR, in case you have no time to review it.

2023-05-03 08:56 UTC, Rugvip approved these changes
All good, thank you! 👍 🎉 

We're all busy, in particular the last few weeks. Working on scaling things though 😁

2023-05-03 08:59 UTC, merged