OWNERS: update Catalog project area
backstage/backstage pull request #17074
Opened 2023-03-24 09:38 UTC by Rugvip

This formalizes the Catalog project area, along with its maintainers. You've likely seen the Chipmunks squad in the catalog SIG and other places, who have been taking over responsibility of the catalog.

In addition to this change the @backstage/catalog-core team will be renamed to @backstage/catalog-maintainers.

2023-03-24 09:49 UTC, Edje-C commented on OWNERS.md
> +| Mike Blockley  | Spotify      | Chipmunks | [mikeyhc](http://github.com/mikeyhc)     | -                |
```suggestion
| Mike Blockley  | Spotify      | Chipmunks | [mikeyhc](http://github.com/mikeyhc)     | harker#0766        |
```

2023-03-24 09:54 UTC, Rugvip commented on OWNERS.md
> +| Mike Blockley  | Spotify      | Chipmunks | [mikeyhc](http://github.com/mikeyhc)     | -                |
Thanks! 👍

2023-03-24 10:00 UTC, benjdlambert commented on OWNERS.md
> +| Mike Blockley  | Spotify      | Chipmunks | [mikeyhc](http://github.com/mikeyhc)     | harker#0766        |
Hmm prettier?

2023-03-24 13:29 UTC, mikeyhc requested changes

2023-04-03 12:58 UTC, jhaals approved these changes

2023-04-11 14:53 UTC, mikeyhc approved these changes

2023-04-11 14:54 UTC, alde approved these changes

2023-04-11 15:35 UTC, benjdlambert approved these changes
SUPER APPROVED

2023-04-11 15:43 UTC, merged