Streamline Your Onboarding Process with Our Top-Rated Onboarding Plugin
backstage/backstage pull request #17218
Opened 2023-04-03 17:46 UTC by twshubham

## Hey, I just made a Pull Request!

## Summary 

This plugin is created to automate the processes of onboarding by which new hires are integrated into the organization. It includes activities that allow new employees to complete an initial new-hire orientation process, as well as learn about the organization and its structure, culture, vision, mission, and values. By automating this onboarding process, organizations can reduce administrative tasks, improve efficiency, and provide new employees with a better experience. This can help to improve retention rates and reduce the time and resources needed for onboarding, ultimately leading to cost savings for the company.

<img width="1420" alt="Screenshot 2023-03-31 at 5 00 18 PM" src="https://user-images.githubusercontent.com/108401398/229108878-417a4276-1e4a-42a9-9346-925c70d296c5.png">

## Feature

-  Easy to onboard new and existing members.
-  All the prerequisites are available in one place.
-  Track the status of the onboarding procedure.
-  Easy to manage checklist.
-  Reminder for pending checklist every time a member visits the application by opening a popup.
- Organized and optimized data flow.

2023-04-13 05:40 UTC, twshubham commented
> Is this a duplicate of #17181?

This PR are closed now

2023-04-20 14:29 UTC, benjdlambert requested changes
Hey :wave: apologies this has taken a while to get round to, been pretty busy the last few weeks. Thanks for this PR though! :pray:

I added some higher level comments that I think we probably wanna address :)

2023-04-20 14:29 UTC, benjdlambert commented on app-config.yaml
> +    - type: onboarding-repo-url
think you can remove this as this won't be set

2023-04-20 14:29 UTC, benjdlambert commented on packages/backend/src/index.ts
> +import onboarding from './plugins/onboarding';
move this import to the top with the other plugins.

2023-04-20 14:29 UTC, benjdlambert commented on packages/backend/src/plugins/onboarding.ts
> +  // Here is where you will add all of the required initialization code that
Not sure we need this?

2023-04-20 14:29 UTC, benjdlambert commented on plugins/onboarding-backend/package.json
> +  "version": "1.0.0",
I'd say set this to `0.0.0` as the default, and then a `minor` changeset to take it to `0.1.0`

2023-04-20 14:29 UTC, benjdlambert commented on plugins/onboarding-backend/src/service/Github.service.ts
> +    } catch (error) {
Think we probably want to do something with the error here?

2023-04-20 14:29 UTC, benjdlambert commented on plugins/onboarding-backend/src/service/Github.service.ts
> +      const response = await axios(this.baseRepo, {
Have you thought about using the Octokit library instead of using http requests?

2023-04-20 14:29 UTC, benjdlambert commented on plugins/onboarding/package.json
> +  "version": "1.0.0",
Same as the backend plugin here too

2023-04-20 14:29 UTC, benjdlambert commented on plugins/onboarding-backend/src/service/router.ts
> +  router.put('/updateStatus', async (req, res) => {
think we should keep this lowercase and avoid case sensitive.

either `PUT /status` or `PUT /update-status` or something

2023-04-20 14:29 UTC, benjdlambert commented on plugins/onboarding-backend/src/service/router.ts
> +  router.get('/getChecklists', async (req, res) => {
`GET /checklists` instead?

2023-04-28 07:32 UTC, benjdlambert commented
Wanna also bring in some people that are looking at onboarding in general and get their thoughts @tudi2d @mitchhentgesspotify, but I think that this could be a good start for us to build upon.

2023-04-28 08:34 UTC, mitchhentgesspotify commented
> Wanna also bring in some people that are looking at onboarding in general and get their thoughts

Unless I'm mistaken, I believe that this PR is more for onboarding users onto an existing Backstage instance, while our recent looking into "onboarding" has been more focused on getting started with _running_ (and configuring) a Backstage instance.

-----

From a user onboarding perspective, I can see how having a nice checklist to work through would be beneficial.
👍 from me, though I might recommend changing the name from `onboarding[-backend]` to `user-onboarding[-backend]`, to avoid any potential confusion with [the `onboard` command](https://github.com/backstage/backstage/pull/16526)

2023-04-28 09:31 UTC, benjdlambert commented
@mitchhentgesspotify yep - understood, and I though as much, and this made me think of that - so I think `user-onboarding` renaming is a good idea!

2023-05-10 09:33 UTC, closed without merging