Show aggregate users under groups
backstage/backstage pull request #17495
Opened 2023-04-24 20:42 UTC by wss-rbunning

## Hey, I just made a Pull Request!

This PR adds a toggle switch to the members card, allowing you to toggle between showing direct members and aggregated members of a group. Aggregated users is recursive and handles duplicated users and child groups. 

This addresses feature request #16959 

## Before:
![image](https://user-images.githubusercontent.com/129326788/234110604-b3486e04-0ca3-41d1-a4ee-b10b64137577.png)

## After:
![image](https://user-images.githubusercontent.com/129326788/234110649-88f5672f-a8f9-49b8-8f0e-d95671cf3a19.png)
![image](https://user-images.githubusercontent.com/129326788/234110667-c1e0cf72-de10-4bc6-8ba9-081a071d66d2.png)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-04-24 21:49 UTC, ahhhndre commented
@wss-rbunning, is this opt in? As in we won’t see the switch at all if we don’t enable it.

2023-04-26 18:45 UTC, wss-rbunning commented
@ahhhndre As it is right now, the switch is not opt-in and will always be visible. It does, however, default to the off position when the page loads, showing only direct members like before.

2023-04-26 18:52 UTC, awanlin commented
> @ahhhndre As it is right now, the switch is not opt-in and will always be visible. It does, however, default to the off position when the page loads, showing only direct members like before.

The general practice is to make these types of things Opt-In. Doing it this way people can choose to have it visible versus it being force upon them. Should be a pretty easy thing to implement. Can we please change that?

(Sorry if this is confusing, I am Ahhhndre I just wanted to follow up on this when I saw it on my phone before I forgot and it got merged in)

2023-04-26 19:00 UTC, awanlin requested changes
Thanks for this contribution @wss-rbunning, please don't take my comments about making this opt-in to seem like it's not wanted. I know that this is something the Community will be happy to have once it's merged in and released 🚀 

Overall this looks good to me, left a few comments

2023-04-27 19:06 UTC, wss-rbunning commented on plugins/org/src/components/Cards/Group/MembersList/MembersListCard.tsx
> +        <Switch
I have made the aggregate users toggle switch be opt-in now. There is now a showAggregateMembersToggle on MembersListCard that when set will show the toggle. If it is not set, the card will not look different.

2023-04-27 19:07 UTC, wss-rbunning commented on plugins/org/src/components/Cards/Group/MembersList/MembersListCard.tsx
I have created a Storybook entry for when the toggle switch is turned on. From the Storybook page, you can toggle the switch on and off to see the aggregated users get added or removed.

2023-04-27 19:09 UTC, wss-rbunning commented on .changeset/new-roses-fail.md
> +Changed the MembersListCard component to allow displaying aggregated members when viewing a group. Now, a toggle switch is displayed that lets you switch between showing direct members and aggregated
I have now added a small code snippet to the change set that demonstrates how to enable the aggregate users toggle switch.

2023-04-27 19:20 UTC, wss-rbunning commented
@awanlin I fully understand the reason for wanting to have it be opt-in and I appreciate the feedback. I have pushed changes that should address your feedback items. Please let me know if there is any other feedback or suggestions you would like me to address 👍.

2023-04-27 20:44 UTC, awanlin commented on plugins/org/src/components/Cards/Group/MembersList/MembersListCard.tsx
Thanks! 👍

2023-04-27 20:44 UTC, awanlin approved these changes
LGTM! 🚀

2023-04-27 20:45 UTC, awanlin commented on plugins/org/src/components/Cards/Group/MembersList/MembersListCard.tsx
> +        <Switch
Thanks! 👍

2023-04-27 20:45 UTC, awanlin commented on .changeset/new-roses-fail.md
> +Changed the MembersListCard component to allow displaying aggregated members when viewing a group. Now, a toggle switch is displayed that lets you switch between showing direct members and aggregated
Thanks! 👍

2023-04-28 20:52 UTC, wss-rbunning commented
@awanlin: 
@jtreher brought this to my attention: With my current implementation of the switch it loads the aggregated users regardless of whether or not the switch is requested through the prop or flipped on. 

With how it is now, it loads the aggregated users in the background, not delaying the page load while this happens. If the switch is flipped to "Aggregate Users" before all aggregate users are done loading, no additional users will be displayed until it is finished.

I am going to change this so that it will only run the logic to get aggregated users if the "show the switch" prop is set (so it isn't doing a lot of extra stuff that someone isn't asking for). Do we want to show a loading bar if the switch is flipped and aggregate users are loading?

2023-05-01 12:44 UTC, awanlin commented
Sounds good to me @wss-rbunning, I think showing a progress bar would be good. How do they deal with that for the Ownership Card? They do something very similar. We don't use it though so I don't remember if it has a progress bar or not.

2023-05-01 20:33 UTC, wss-rbunning commented
@awanlin It looks like in the Ownership Card they have a separate "ownership grid" component that is a child of the card itself and does not contain the toggle switch. This grid shows a loading bar when it is loading members. 

I have pushed changes with my suggestions. Here is the new behavior:

- When the toggle switch is not enabled, the MembersCard will not bother to load descendant members.
- The existing overall loading bar displayed when loading members on the MemebersCard is still used. It is, however, only used when loading direct members. The loading of descendant members is still asynchronous and does not delay rendering the page or direct members. If the user does flip the switch over to aggregate members before it is done enumerating descendant members, a loading bar will be displayed in place of members until it is finished.

2023-05-02 13:08 UTC, Rugvip requested changes
Thank you, looks good! 👍 

Just a couple of nits

2023-05-03 20:08 UTC, wss-rbunning commented on plugins/org/package.json
> +    "@backstage/catalog-client": "workspace:^",
I have moved the testing helpers to a ```__testUtils__``` folder and moved this dependency to being a dev dependency 👍. I am only using these mocks in the tests and storybook.

2023-05-03 20:29 UTC, wss-rbunning commented on plugins/org/src/components/Cards/Group/MembersList/MembersListCard.tsx
> +      return nameToCompareInA.localeCompare(nameToCompareInB);
I have switched this to now compare based off of the results of stringifyEntityRef 👍

2023-05-04 09:30 UTC, Rugvip approved these changes
Nice, thank you! 😁 

Just a tiny think that I'll tweak and then good to :shipit:

2023-05-04 09:30 UTC, Rugvip commented on plugins/org/src/components/Cards/Group/MembersList/MembersListCard.stories.tsx
> + * Copyright 2020 The Backstage Authors
```suggestion
 * Copyright 2021 The Backstage Authors
```

Oops, bit too far back here 😅

2023-05-04 09:59 UTC, merged