Signed-off-by: Pritam Saha <saha7pritam@gmail.com>
backstage/backstage pull request #17658
Opened 2023-05-04 20:01 UTC by Saha-7

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-05-05 08:32 UTC, freben requested changes

2023-05-05 14:06 UTC, Saha-7 commented on plugins/newrelic/src/api/index.ts
> +  getApplications(apiKey: string): Promise<NewRelicApplications>;
Okay, I will try to complete this. If any issue happened  I will let you know.

2023-05-05 19:11 UTC, Saha-7 commented
@freben I raised a  fresh PR for this in #17677 .
You can continue there & close this PR. 
Please let me know if other changes required .

2023-05-08 14:21 UTC, Saha-7 commented
@freben is the PR still open or closed?

2023-05-11 15:53 UTC, freben commented
Well it's open right? The other one was closed in favor of this one, and this one still does not have a green status.

2023-05-23 16:05 UTC, closed without merging