Add ownership for OpenAPI tooling.
backstage/backstage pull request #17717
Opened 2023-05-09 14:13 UTC by sennyeya

## Hey, I just made a Pull Request!

Adding "OpenAPI Tooling" as an Incubating Project Area.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-05-09 15:04 UTC, Rugvip requested changes
🎉 🙏

2023-05-09 15:04 UTC, Rugvip commented on OWNERS.md
> +
Let's add the `team` and `scope` too. For team put @backstage/openapi-tooling-maintainers and we'll create that. I'll let you take the first stab at the scope 😁

2023-05-09 15:04 UTC, Rugvip commented on OWNERS.md
> +
```suggestion
## Incubating Project Areas

These incubating project areas have shared ownership with @backstage/maintainers.
```

2023-05-09 15:16 UTC, sennyeya commented on OWNERS.md
> +
Updated.

2023-05-10 12:57 UTC, Rugvip approved these changes
Thank you, looks good! 👍

2023-05-10 13:08 UTC, freben approved these changes

2023-05-10 16:19 UTC, merged