Refactor: move initial state to props for CatalogGraphPage
backstage/backstage pull request #17792
Opened 2023-05-13 10:55 UTC by shubhamjajoo

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-05-13 10:57 UTC, shubhamjajoo commented
@sennyeya As per your comment on this [issue](https://github.com/backstage/backstage/issues/17096#issuecomment-1500457684), created this PR to refactor props.
Can you pls start reviewing this ?

2023-05-22 10:36 UTC, benjdlambert requested changes
Hey :wave: think this is looking good - we just want to nail down the changeset I think. 

Also would be good to get some feedback from @rugvip and @sennyeya too

2023-05-22 10:36 UTC, benjdlambert commented on .changeset/blue-ants-scream.md
> +Refactor `props` of CatalogGraphPage component. Move properties from `initialState` to `props` and use from `EntityRelationsGraphProps`.
I think that you might want to elaborate that it's a breaking change here, and provide some examples for how to migrate to the new version if using the `initialState` version as it is today.

`**BREAKING**: ...` is normally how we prefix these changes too.

2023-05-22 11:47 UTC, sennyeya commented on plugins/catalog-graph/src/components/CatalogGraphPage/useCatalogGraphPage.ts
> -    rootEntityRefs?: string[];
I may have been a bit overzealous in my original comment. I think this use of `initialState` makes sense for `useCatalogGraphPage` and _probably_ `CatalogGraphPage` as well. I didn't realize we were supporting dynamically setting all of these options.

@benjdlambert is this generally how `initialState` is used across the project?

2023-06-02 18:39 UTC, sennyeya commented on plugins/catalog-graph/src/components/CatalogGraphPage/useCatalogGraphPage.ts
> -    rootEntityRefs?: string[];
@benjdlambert bump.

2023-06-14 18:53 UTC, closed without merging