Adding info on entities selected to catalog table title
backstage/backstage pull request #17847
Opened 2023-05-17 17:13 UTC by SnowBlitzer

## Hey, I just made a Pull Request!

In prep for user research, we realized this page can cause confusion on what is currently selected. This makes the title on the table more descriptive for the user.
<img width="871" alt="Screenshot 2023-05-17 at 10 52 01 AM" src="https://github.com/backstage/backstage/assets/7171310/88245385-7594-45f4-9029-c5cdad689b24">

<img width="913" alt="Screenshot 2023-05-17 at 10 51 42 AM" src="https://github.com/backstage/backstage/assets/7171310/e2dc650f-54f9-4e3a-bd90-e9ac4e419fde">
<img width="890" alt="Screenshot 2023-05-17 at 10 51 54 AM" src="https://github.com/backstage/backstage/assets/7171310/1bf89a0a-1d92-4a55-ba5e-666eb3bf28e9">

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-05-18 16:53 UTC, efenner-cambia commented
This looks great!

2023-05-31 15:11 UTC, Rugvip requested changes
Ah sorry, missed actually posting the review 🤦

Thank you! Looks good, just a small nit

2023-06-07 18:09 UTC, SnowBlitzer commented on plugins/catalog/src/components/CatalogTable/CatalogTable.tsx
> +      title={`${titleDisplay}${currentKind ? 's' : ''} (${entities.length})`}
Ohhh, thank you for this. I'm having an issue pushing the commit but I will get that up

2023-06-12 15:56 UTC, Rugvip approved these changes
Nice! 👍 

Let's :shipit:

2023-06-12 15:57 UTC, merged