Improve Devtools Docs based on installation in Docker
backstage/backstage pull request #18038
Opened 2023-05-31 13:13 UTC by dlaird-ovo

## Updated DevTools Plugin Docs

This is a few changes to DevTools documentation based on my usage with Backstage in a docker container

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-05-31 13:14 UTC, dlaird-ovo commented
@ahhhndre - this is a PR for DevTools Docs - hope this is helpful.

2023-05-31 13:16 UTC, dlaird-ovo commented
Do you need a changeset for Doc changes? I read this `Changesets are also not needed for changes that do not affect the published version of each package, for example changes to tests or in-line source code comments.` in CONTRIBUTING.md and assumed it was not required.

2023-05-31 15:09 UTC, awanlin requested changes
Thanks for this contribution @dlaird-ovo, this is super helpful! 🚀 

Overall very happy with this just one nit about where one section is

2023-05-31 15:09 UTC, awanlin commented on plugins/devtools/README.md
> +#### Backstage Version Reporting
The content and formatting of this is great, I just think it should be moved up to be under the `Info` heading as that's where the Backstage version is shown.

2023-05-31 15:09 UTC, awanlin commented on plugins/devtools/README.md
> +#### Backstage Version Reporting
Just below the image

2023-05-31 15:11 UTC, awanlin commented
Regarding the changeset: if you can add it that would be good, it just makes sure that a new package gets created which then updates things on NPM. People do use the `README` content that shows up there so good to keep it up to date

2023-06-01 11:35 UTC, awanlin approved these changes
Awesome! Thanks again @dlaird-ovo 🚀

2023-06-01 11:36 UTC, awanlin commented
Hi @benjdlambert, these are just changes to the `README`. I'm happy with them, if you could give them a quick look that would be great. Thanks in advance!

2023-06-08 12:12 UTC, awanlin commented
Not stale as it's ready to go, just needs to be approved and merged. Can you take a look @benjdlambert, please?

2023-06-13 08:14 UTC, benjdlambert approved these changes
Apologies for the delay! I've been off since last week, just catching up! :pray:

2023-06-13 08:28 UTC, merged

2023-06-13 11:40 UTC, awanlin commented
Thanks again @dlaird-ovo and @benjdlambert 🚀