Fix 18035
backstage/backstage pull request #18077
Opened 2023-06-02 07:04 UTC by npiyush97

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ X] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-06-02 08:08 UTC, jhaals requested changes
Thanks for the PR! Some minor tweaks added

2023-06-02 08:08 UTC, jhaals commented on .changeset/gorgeous-timers-act.md
> +'@backstage/plugin-catalog-backend-module-gitlab': minor
```suggestion
'@backstage/plugin-catalog-backend-module-gitlab': patch
```

2023-06-02 08:08 UTC, jhaals commented on .changeset/gorgeous-timers-act.md
> +added test if user does not have name or profile picture,variable default to undefined
```suggestion
Fixed bug that caused ingestion errors when a user's name or profile picture is undefined.
```

Reworded this slightly as this is what goes in the changelog for this package. The tests are a great addition but an internal thing to the package so no need mentioning that.

2023-06-02 08:08 UTC, jhaals requested changes
Thanks for the PR! Some minor tweaks added

2023-06-02 11:39 UTC, merged

2023-06-15 13:36 UTC, malagant commented
This is a very important fix. Can you already tell, when this will be published?

2023-06-15 13:40 UTC, jamieklassen commented
@malagant according to the github-actions bot post [above](https://github.com/backstage/backstage/pull/18077#issuecomment-1573598035),

> Thank you for contributing to Backstage! The changes in this pull request will be part of the `1.15.0` release, scheduled for Tue, 20 Jun 2023.

it should be published next Tuesday.