Add Azure DevOps Wiki Search plugin
backstage/backstage pull request #18229
Opened 2023-06-13 12:07 UTC by arhill05

## Hey, I just made a Pull Request!

This adds the Azure DevOps Wiki Search plugin to the plugins site

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ x ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-06-13 12:40 UTC, awanlin requested changes
This is a super cool plugin @arhill05, thanks for the contribution! 🚀 

Just left a comment about the logo

2023-06-13 12:40 UTC, awanlin commented on microsite/data/plugins/ado-wiki-search-icon.png
Sadly we can't use this based on guidance from Microsoft on this topic: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks

2023-06-13 12:49 UTC, arhill05 commented on microsite/data/plugins/ado-wiki-search-icon.png
D'oh! My bad. I've updated the logo.

2023-06-13 13:02 UTC, awanlin approved these changes
Awesome! Thank again @arhill05 👍

2023-06-20 13:10 UTC, Rugvip approved these changes
Thank you! 👍  sorry for the delay

2023-06-20 13:11 UTC, merged