cli: Add `Request` `Response` `Headers` and `fetch` to `jsdom` environment
backstage/backstage pull request #18234
Opened 2023-06-13 13:54 UTC by benjdlambert

2023-06-13 13:59 UTC, Rugvip reviewed
Sweet! This is indeed a nicer broader fix. Let's also clean up poliyfills in setupTests.ts

2023-06-13 13:59 UTC, Rugvip commented on packages/cli/config/jest.js
> +      return { testEnvironment: require.resolve('./jsdomEnvironment') };
everything else in the config dir is namespaced, could we make this `jestJsdomEnvironment`?

2023-06-13 14:07 UTC, Rugvip approved these changes

2023-06-13 15:09 UTC, Rugvip approved these changes
🧹 :shipit:

2023-06-13 16:56 UTC, Rugvip requested changes
So we need to do a bit more thinking 😅

2023-06-19 11:43 UTC, camilaibs approved these changes
Approving discoverability changes 🙂 .

2023-06-19 11:55 UTC, Rugvip requested changes
Yep let's do it, and then perhaps be able to just ship in in the env in 18

2023-06-19 11:55 UTC, Rugvip commented on packages/cli/config/jest.js
> +    options.setupFilesAfterEnv.push(require.resolve('cross-fetch/polyfill'));
Feeling we want to make sure this is always first right? so `.unshift` given the change above

2023-06-19 11:55 UTC, Rugvip commented on packages/cli/config/jest.js
> +  options.setupFilesAfterEnv = [];
Feeling we should `options.setupFilesAfterEnv = options.setupFilesAfterEnv || []` here

2023-06-19 12:07 UTC, Rugvip approved these changes
Sweet 😎 :shipit:

2023-06-19 12:26 UTC, freben approved these changes
Love it!

2023-06-20 08:40 UTC, merged