Add option to pass kinds to AnnotateScmSlugEntityProcessor, eg ['Component', 'Template'] (#17351)
backstage/backstage pull request #18342
Opened 2023-06-19 14:02 UTC by Pike

## Hey, I just made a Pull Request!

Add option to pass kinds to AnnotateScmSlugEntityProcessor, like discussed in #17351 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-06-28 11:04 UTC, Pike commented
Ping.

2023-07-05 17:49 UTC, Pike commented
Pong.

2023-07-17 19:53 UTC, freben commented
Reopening!

2023-07-24 20:23 UTC, Pike commented
Pung.

2023-08-01 12:26 UTC, Rugvip requested changes
Nice, thank you! 👍 

Just a minor nit

2023-08-01 12:26 UTC, Rugvip commented on plugins/catalog-backend/src/modules/core/AnnotateScmSlugEntityProcessor.ts
> +    if (!this.opts.kinds.includes(entity.kind) || location.type !== 'url') {
While we're at it I think it'd be best to make this comparison case insensitive

2023-08-08 14:47 UTC, kuangp commented
I actually just implemented this in https://github.com/backstage/backstage/pull/18918 😄

2023-08-08 14:47 UTC, closed without merging