Feature/entity dependencies card enhancements
backstage/backstage pull request #18504
Opened 2023-06-30 07:35 UTC by Abhay-soni-developer

I have extended the EntityHasSubcomponentsCard, EntityDependsOnResourcesCard and EntityDependsOnResourcesCard and EntityTable to supports tableOptions.

i have extended these components in such a way that it does not effect the current implementation just extend it capabilities to support tableOptions

This PR is the implementation for this https://github.com/backstage/backstage/issues/18503

2023-06-30 07:38 UTC, Abhay-soni-developer commented
@Rugvip  @benjaminr  @Edje-C @awanlin

2023-06-30 07:45 UTC, NishkarshRaj commented
This is pretty helpful.

As we scale Backstage adoption, we don't want to scroll down a lot. So from a UX perspective - Pagination and Filtering is a bliss.

2023-06-30 07:45 UTC, NishkarshRaj commented
> ## Missing Changesets
> The following package(s) are changed by this PR but do not have a changeset:
> 
> * **@backstage/plugin-catalog-react**
> * **@backstage/plugin-catalog**
> 
> See [CONTRIBUTING.md](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets) for more information about how to add changesets.
> 
> ## Changed Packages
> Package Name	Package Path	Changeset Bump	Current Version
> @backstage/plugin-catalog-react	plugins/catalog-react	**none**	`v1.7.1-next.0`
> @backstage/plugin-catalog	plugins/catalog	**none**	`v1.11.3-next.0`

@Abhay-soni-developer ☝️

2023-07-04 09:04 UTC, benjdlambert commented
@Abhay-soni-developer this will need some changesets :pray:

2023-07-05 17:03 UTC, benjdlambert requested changes

2023-07-05 17:03 UTC, benjdlambert commented on .changeset/popular-icons-doubt.md
> +I have extended the EntityHasSubcomponentsCard, EntityDependsOnResourcesCard, EntityDependsOnResourcesCard and EntityTable to support table options.
```suggestion
Tables which use `EntityTableProps` now have an additional `tableOptions` prop which can be used to provide additional table options to these components.
```

2023-07-06 03:24 UTC, Abhay-soni-developer commented
@benjdlambert  the requested changes  have been done. are we ready to merge this

2023-07-06 08:51 UTC, benjdlambert approved these changes

2023-07-10 05:46 UTC, Abhay-soni-developer commented
@benjdlambert  i just merged the feedbacks after that pipeline is failing , can you help me resolve this
as i can not find the reason of failure

2023-07-10 11:47 UTC, merged

2023-07-10 11:47 UTC, benjdlambert commented
The e2e's are failing for a seperate reason - i've just mer7ged this.