Allow uiSchema to be set as part of the settings for HomePage
backstage/backstage pull request #18574
Opened 2023-07-05 08:50 UTC by ivangonzalezacuna

## Hey, I just made a Pull Request!

While integrating the custom HomePage, we noticed that in some cases we needed to customize the way the UI was generated in the SettingsWidget. Unfortunately, this wasn't possible since we couldn't use the `uiSchema`. This PR is simply adding the little pieces needed for that. An example is available in the README file. We also tested it in our local instance and it worked completely fine for us.

Of course, this is something optional, so nothing will break at all if the `uiSchema` is not used.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-07-10 12:21 UTC, tikabom approved these changes

2023-07-10 14:31 UTC, benjdlambert requested changes
Think there's a small mistake in the README, but just here to unblock the merge! :pray:

2023-07-11 06:28 UTC, ivangonzalezacuna commented on plugins/home/README.md
> +      schemaUi: {
Yes. Indeed it was a mistake when writing the docs. I've just fixed it

2023-07-11 08:25 UTC, benjdlambert approved these changes

2023-07-11 08:25 UTC, benjdlambert commented
Thanks :tada:

2023-07-11 08:25 UTC, merged