Airbrake backend: Support the new backend system
backstage/backstage pull request #18598
Opened 2023-07-06 05:20 UTC by anicke

## Hey, I just made a Pull Request!

Added support for the new backend system for the airbrake plugin.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-07-06 05:21 UTC, anicke commented
Ping #18301

2023-07-08 23:35 UTC, awanlin requested changes
Thanks for the contribution @anicke 🚀 

The code changes look good to me just left a comment about the `README`

2023-07-08 23:35 UTC, awanlin commented on plugins/airbrake/README.md
> +   ```typescript
We aren't ready to have everyone use the new backend system as the default. You'll want to keep the existing documentation as is. But then add a new section specifically about this. The Azure DevOps Backend is a good example: https://github.com/backstage/backstage/tree/master/plugins/azure-devops-backend#new-backend-system

2023-07-09 07:02 UTC, anicke commented
Made the change on my phone. Could not figure out how to sign the commit. Will fix later.

2023-07-09 17:45 UTC, awanlin approved these changes
Looks good to me, thanks! 🚀 

Just make sure to resolve the issue with the DCO.

FYI - The build failures do not looks related and we are seeing them fail the same way for other PRs

2023-07-10 11:50 UTC, benjdlambert commented
@anicke we also need a changeset for the readme update in the `airbrake` plugin :pray:

2023-07-10 17:26 UTC, anicke commented
Changeset added!

2023-07-11 08:24 UTC, benjdlambert approved these changes
Nice thanks :tada:

2023-07-11 08:24 UTC, merged