added support to Lighthouse for new backend
backstage/backstage pull request #18633
Opened 2023-07-11 08:52 UTC by jroebu14

## Hey, I just made a Pull Request!

Added support for the new backend system for the Lighthouse plugin.

https://github.com/backstage/backstage/issues/18301

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-07-12 08:16 UTC, Rugvip requested changes
Thank you, looks good! 👍 

Just some minor nits

2023-07-12 08:16 UTC, Rugvip commented on plugins/lighthouse-backend/README.md
> ++ );
```suggestion
+ backend.add(lighthousePlugin());
```

Might as well right? 😁

2023-07-12 08:16 UTC, Rugvip commented on plugins/lighthouse-backend/src/plugin.ts
> +        const catalogClient = new CatalogClient({ discoveryApi: discovery });
Let's depend on the `catalogServiceRef` from `'@backstage/plugin-catalog-node/alpha'` to access this instead.

2023-07-12 08:30 UTC, jroebu14 commented on plugins/lighthouse-backend/README.md
> ++ );
much prettier 😄

2023-07-13 08:06 UTC, Rugvip approved these changes
Excellent, let's :shipit:!

2023-07-13 08:06 UTC, merged