Displaying an alert popup everytime the Playlist is created or deleted
backstage/backstage pull request #18782
Opened 2023-07-24 17:22 UTC by AmbrishRamachandiran

## Hey, I just made a Pull Request!

Displaying an alert popup every time the Playlist is created or deleted, similar to other backstage activities.
The popup will be disappeared after some seconds
This will help users to experience good UI experience

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-07-24 17:45 UTC, kuangp requested changes
One additional request but this change is looking good so far! 😁

2023-07-24 17:45 UTC, kuangp commented on plugins/playlist/src/components/CreatePlaylistButton/CreatePlaylistButton.tsx
> +        });
Can you also add this success message [here](https://github.com/backstage/backstage/blob/master/plugins/playlist/src/components/EntityPlaylistDialog/EntityPlaylistDialog.tsx#L134) as well 🙏 ? this is for when new playlists are created from the entity context

2023-07-24 17:45 UTC, kuangp commented on .changeset/purple-dolls-change.md
> +Displaying an alert popup everytime the Playlist is created or deleted
```suggestion
Displaying an alert popup every time the Playlist is created or deleted
```

2023-07-24 18:08 UTC, AmbrishRamachandiran commented
@kuangp changes pushed please review and let me know if any changes required

2023-07-24 18:52 UTC, kuangp requested changes
Looks like a failing test also needs to be addressed

2023-07-24 18:52 UTC, kuangp commented on .changeset/purple-dolls-change.md
Looks like 2 identical changesets were created? You should only need one and can delete the other

2023-07-25 04:33 UTC, AmbrishRamachandiran commented
@kuangp the latest commit have all the changes with all the test cases passed please review

2023-07-25 13:25 UTC, AmbrishRamachandiran commented
@kuangp deleted duplicate files please review - TIA

2023-07-25 13:45 UTC, kuangp approved these changes
looks good! thanks for the contribution!

2023-07-25 14:09 UTC, benjdlambert approved these changes

2023-07-25 14:09 UTC, merged

2023-07-25 14:09 UTC, benjdlambert commented
Thanks both! :tada: