[`sonarqube-backend plugin`] added optional `externalUrl` config for overriding the frontend URL
backstage/backstage pull request #18825
Opened 2023-07-27 19:27 UTC by ConnorDY

## Hey, I just made a Pull Request!

In some cases, you might want to use one base URL for connecting via the backend and a different URL for display on the frontend.

For example, we deploy SonarQube and Backstage in a Kubernetes cluster. We use an internal Kubernetes URL for connecting to SonarQube from the Backstage backend (it looks something like `develop-sonarqube.develop-sonarqube.svc.cluster.local:9000`). But users cannot access the SonarQube URL from their web browsers using this link.

This PR would allow users of the plugin to provide a different external URL used for the SonarQube links displayed on the frontend.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-07-27 19:42 UTC, ltdonner approved these changes

2023-07-27 19:44 UTC, morganmspencer approved these changes

2023-08-01 11:54 UTC, Rugvip requested changes
Makes sense, thank you! 👍 

For a consistency PoV I'm thinking it might make sense to call the new option `externalBaseUrl`, seeing as it's still a base URL used to generate full ones. What do you think?

2023-08-01 11:56 UTC, Rugvip commented
Another option could be the following, if you think it's neater, we somewhat have precedence for both:

```yaml
sonarqube:
  baseUrl:
    internal: https://sonarqube-internal.example.com
    external: https://sonarqube.example.com
```

2023-08-01 12:38 UTC, ConnorDY commented
> For a consistency PoV I'm thinking it might make sense to call the new option externalBaseUrl, seeing as it's still a base URL used to generate full ones. What do you think?

I like that! I'll make the change.

2023-08-09 15:28 UTC, ConnorDY commented
@Rugvip Could you please re-review?
Bumping this thread so that my PR doesn't get automatically closed. 😅

2023-08-12 12:54 UTC, Rugvip approved these changes
Nice, thank you! 👍 

Let's :shipit:

2023-08-12 12:54 UTC, Rugvip commented on .changeset/warm-peas-hang.md
> +'@backstage/plugin-sonarqube-backend': minor
```suggestion
'@backstage/plugin-sonarqube-backend': patch
```

Switching to `patch` since this isn't a breaking change

2023-08-12 13:10 UTC, merged