fix(explore): don't put ? if no query params
backstage/backstage pull request #18891
Opened 2023-08-01 15:04 UTC by jpatovh

## Hey, I just made a Pull Request!

Hello,

The Explore plugin frontend do a call to `/api/explore/tools?` with a trailing "?" sign at the end of the URL, when there are no filters.

I've some trouble on my internal proxy on this request , so I push this fix.

Thank you!

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-08-01 16:26 UTC, awanlin requested changes
Thanks for the contribution @blaryjp, code looks good to me but it would be great to have a test for this. You can do that in the `ExploreClient.test.ts` file right beside this one 👍

2023-08-02 07:39 UTC, blaryjp commented
Thank you @awanlin . You are right ; I added the unit test :)

2023-08-09 13:19 UTC, awanlin approved these changes

2023-08-09 13:19 UTC, awanlin commented
@Rugvip, look good to me, can you take a peek?

2023-08-12 12:57 UTC, Rugvip approved these changes
Nice, thank you! 👍

2023-08-12 12:57 UTC, merged