make `search-backend-module-explore` & `search-backend-module-techdocs` configurable from app-config
backstage/backstage pull request #19297
Opened 2023-08-09 14:40 UTC by tudi2d

- Removing options from backend modules `search-backend-module-explore` & `search-backend-module-techdocs`
- Add respective `config.d.ts` & change effected tests
- Convert `permission-backend` from callback to object in favour of not wanting options in the future

---

- In addition to https://github.com/backstage/backstage/pull/19278
- Works towards https://github.com/backstage/backstage/issues/18390

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-08-10 08:13 UTC, Rugvip requested changes
Nice! 😁

2023-08-10 08:13 UTC, Rugvip commented on plugins/search-backend-module-explore/src/alpha.ts
> +        const schedule = config.has('search.explore.schedule')
I've been moving these into the equivalent of `ToolDocumentCollatorFactory.fromConfig` instead, that way you can still use static configuration in the old system. Thinking that avoids potential confusion about why the config schema doesn't match and doesn't hurt much.

2023-08-10 08:13 UTC, Rugvip commented on plugins/search-backend-module-techdocs/src/collators/DefaultTechDocsCollatorFactory.ts
> +      'search.techdocs.collators.locationTemplate',
Yeah definitely feeling that `search.collators.techdocs.locationTemplate` would make more sense? 😅

2023-08-10 09:39 UTC, freben commented on plugins/search-backend-module-explore/config.d.ts
> +    explore?: {
That's what https://github.com/backstage/backstage/pull/19278 does too

2023-08-15 13:23 UTC, merged

2023-08-15 13:26 UTC, camilaibs approved these changes
LGTM, just left a non-blocking suggestion.

2023-08-15 13:33 UTC, camilaibs commented on plugins/search-backend-module-explore/src/alpha.ts
> +          ? readTaskScheduleDefinitionFromConfig(
Perfect, thanks for sharing 🙌🏻

2023-08-16 11:07 UTC, camilaibs commented on plugins/search-backend-module-explore/config.d.ts
> +        schedule?: TaskScheduleDefinitionConfig;
TIL, thanks for sharing about the anchors!