Add AWS Annotations to Kubernetes Cluster Resource
backstage/backstage pull request #19304
Opened 2023-08-09 17:22 UTC by clementblaise

## Hey, I just made a Pull Request!

Issue #19225 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-08-10 19:15 UTC, jamieklassen requested changes
One little note about the changeset, but otherwise this looks great!

2023-08-12 14:30 UTC, jamieklassen commented on .changeset/chatty-goats-mate.md
> +'@backstage/plugin-kubernetes-common': minor
since these packages are still 0.x
```suggestion
'@backstage/plugin-kubernetes-backend': patch
'@backstage/plugin-kubernetes-common': patch
```

2023-08-21 17:32 UTC, jamieklassen approved these changes

2023-08-22 13:37 UTC, freben approved these changes

2023-08-22 13:38 UTC, merged