Add Microsoft Teams actions plugin to microsite
backstage/backstage pull request #19336
Opened 2023-08-11 07:43 UTC by grvpandey11

## Hey, I just made a Pull Request!

Adds Microsoft Teams scaffolder actions plugin to the plugins list.

For use of Microsoft Teams logo:
- https://answers.microsoft.com/en-us/msteams/forum/all/use-of-logos/6f0a104b-ebf1-49c7-b76e-bcfea88baa5c

Please do let me know If I have to change the Icon.

Inspired by Andrew Hill Slack Plugin

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-08-11 08:21 UTC, grvpandey11 commented
@benjdlambert The Verify Docs Quality check is failing on my name. Is there something I can do?

2023-08-11 14:02 UTC, adamdmharvey commented
@grvpandey11 You can add your first name and surname here:

https://github.com/backstage/backstage/blob/master/.github/vale/Vocab/Backstage/accept.txt

Usually on pages with a lot of contributor names being added, those files would be excluded (like the adopters page), but since this is a main content page in the primary docs site, it's still spell checked.  Hope that helps!

2023-08-11 14:43 UTC, grvpandey11 commented
Thanks @adamdmharvey It certainly helped.

2023-08-11 15:07 UTC, awanlin requested changes

2023-08-11 15:07 UTC, awanlin commented on microsite/static/img/Ms-Teams.png
We can't use this without consent from Microsoft: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks

Can you please change this?

2023-08-11 15:17 UTC, grvpandey11 commented on microsite/static/img/Ms-Teams.png
Fixed

2023-08-11 15:28 UTC, awanlin commented on microsite/static/img/Ms-Teams.png
Sorry, I totally missed the comment about this in the PR. We generally err on the side of caution with things like this. Thanks for the understanding 👍

2023-08-11 15:29 UTC, awanlin approved these changes

2023-08-12 17:04 UTC, grvpandey11 commented
@benjdlambert Can you please have a look to this Pull Request.

2023-08-13 09:28 UTC, Rugvip approved these changes
Great, thanks! :+1: 

Thank you for helping out with reviews @adamdmharvey @awanlin :heart:

2023-08-13 09:29 UTC, merged