fetching project/repo from location
backstage/backstage pull request #19412
Opened 2023-08-16 15:19 UTC by taraknath555

## Hey, I just made a Pull Request!

backstage.io/managed-by-location: https://dev.azure.com/{org}/{project}/_git/{repo}?path=/.catalog/component.yml

if `dev.azure.com/project-repo` annotation is not provided and `dev.azure.com/project` not exits then to extract the project and repo information we can use `backstage.io/managed-by-location` annotation if location contains `dev.azure.com` in url to enable CICD tab.

![image](https://github.com/backstage/backstage/assets/42321546/8547c70d-9c8f-4134-bb33-5be3dbcfb5d7)

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-08-16 19:55 UTC, awanlin requested changes
Thanks for the contribution @taraknath555, this is a good idea but I think we should make sure to support both Cloud and Server versions of Azure DevOps. This should be achievable if you use `git-url-parse`, there are many examples in this repo. 

Also, I'm not sure if `backstage.io/managed-by-location` will work for everyone, we keep our YAML in a central repo so it would pull in the wrong project and repo for us. Could we use `backstage.io/source-location` instead?

Finally, if we could add some tests for this that would be really good!

2023-08-16 21:41 UTC, cal5barton commented on plugins/azure-devops/README.md
> +if `dev.azure.com/project-repo` annotation is not provided and `dev.azure.com/project` not exits then to extract the project and repo information we can use `backstage.io/managed-by-location` annotat
This needs to be more clear. Maybe something like this?
```
If the annotation dev.azure.com/project-repo is absent and the dev.azure.com/project does not exist, we can derive the project and repository details by utilizing the backstage.io/managed-by-location annotation. This approach becomes active when the URL within the location contains dev.azure.com, allowing the activation of the CICD tab.
```

2023-08-17 17:05 UTC, cal5barton commented
> Thanks for the contribution @taraknath555, this is a good idea but I think we should make sure to support both Cloud and Server versions of Azure DevOps. This should be achievable if you use `git-url-parse`, there are many examples in this repo.
> 
> Also, I'm not sure if `backstage.io/managed-by-location` will work for everyone, we keep our YAML in a central repo so it would pull in the wrong project and repo for us. Could we use `backstage.io/source-location` instead?
> 
> Finally, if we could add some tests for this that would be really good!

It seems like this method would work to support both correct? https://github.com/backstage/backstage/blob/master/plugins/github-actions/src/components/getHostnameFromEntity.ts

It also seems like this method should be more of a core helper method. Is that something we should consider?

2023-08-17 17:06 UTC, cal5barton commented on plugins/azure-devops/src/constants.ts
> +export const AZURE_DEVOPS_PROJECT_LOCATION = 'backstage.io/managed-by-location';
This won't be needed.

2023-08-17 17:07 UTC, cal5barton commented on plugins/azure-devops/src/utils/isAzureLocation.ts
> +export const isDevAzureLocation = (entity: Entity): boolean => {
If we end up making this method https://github.com/backstage/backstage/blob/master/plugins/github-actions/src/components/getHostnameFromEntity.ts a core helper method then this won't be needed, however, if not we should mirror the functionality there in this file.

2023-08-24 20:07 UTC, awanlin commented
Hi @taraknath555, I only recently learned about the existence of this processor but I'm think it would be much smarter to add this feature to the existing `AnnotateScmSlugEntityProcessor` as it then becomes opt-in for users and would support both Cloud and Server usage. 

To implement this all you would need to do is add the `dev.azure.com/project-repo` annotation here: https://github.com/backstage/backstage/blob/263e3846d8e0d2270800f7ddc224da902912f53e/plugins/catalog-backend/src/modules/core/AnnotateScmSlugEntityProcessor.ts#L29

And then update this switch with a case for `azure`: https://github.com/backstage/backstage/blob/263e3846d8e0d2270800f7ddc224da902912f53e/plugins/catalog-backend/src/modules/core/AnnotateScmSlugEntityProcessor.ts#L77

2023-08-28 06:28 UTC, taraknath555 commented
Hey @awanlin, can you please make me clear if only need to do the below change in this pull request?
![image](https://github.com/backstage/backstage/assets/42321546/88e707f8-49a1-4b8a-bf15-151f36337dcf)
 
If so the other part of the code that will make the requirement work is taken care by #19616 ?

2023-08-28 12:35 UTC, awanlin commented
Hi @taraknath555, yes, I would just make the changes I suggested to add getting the `dev.azure.com/project-repo` annotation set in the `AnnotateScmSlugEntityProcessor`. I don't want you to have to wait around for my changes to get merged in as they may take a while as they get reviewed. Just doing this will be a big win for the community 🚀 

Also, thanks for taking my various requests in stride, I really appreciate it 👍

2023-09-05 06:50 UTC, taraknath555 commented
> Hi @taraknath555, yes, I would just make the changes I suggested to add getting the `dev.azure.com/project-repo` annotation set in the `AnnotateScmSlugEntityProcessor`. I don't want you to have to wait around for my changes to get merged in as they may take a while as they get reviewed. Just doing this will be a big win for the community 🚀
> 
> Also, thanks for taking my various requests in stride, I really appreciate it 👍

Hey @awanlin, I updated the PR as per you suggested, Please take a look on this!

2023-09-05 12:06 UTC, awanlin requested changes
Looks good to me but we should add a test for this in `AnnotateScmSlugEntityProcessor.test.ts`, please

2023-09-06 11:20 UTC, taraknath555 commented
> Looks good to me but we should add a test for this in `AnnotateScmSlugEntityProcessor.test.ts`, please

Done!

2023-09-08 14:23 UTC, awanlin approved these changes
Looks good to me, approving but if you can update the PR description as well with what was actually done would be great

2023-09-10 16:12 UTC, taraknath555 commented
> what was actually done would be great

Hey @awanlin i updated the PR title! Now, Where you want me to add the things that is actually done for this PR ?

2023-09-13 06:50 UTC, taraknath555 commented
> > what was actually done would be great
> 
> Hey @awanlin i updated the PR title! Now, Where you want me to add the things that is actually done for this PR ?
Hey @awanlin can you please suggest what else changes you required , i already updated the description/title of PR and when can we merge this PR ?

2023-09-13 07:45 UTC, freben reviewed
The catalog maintainers are the ones to help merge this. You'll have to wait for their review too.

2023-09-13 07:45 UTC, freben commented on .changeset/tiny-bulldogs-grow.md
> +'@backstage/plugin-azure-devops': patch
```suggestion
'@backstage/plugin-catalog-backend': minor
```

since the change is in that package, and a feature addition

2023-09-13 12:08 UTC, awanlin approved these changes

2023-09-13 12:12 UTC, awanlin commented
Hi @taraknath555, sorry this fell off my radar. Can you also update the description of this PR? It still talks about the previous changes and has the image that isn't relevant anymore. You could simply replace that with: "Set azure annotation `dev.azure.com/project-repo` in `AnnotateScmSlugEntityProcessor` to find the project and repo information for the repos that contains `dev.azure.com` in the url"

As already mentioned I'm just the first approval you will need approval from the catalog maintainers as well. They will also be the ones to do the merge.

2023-09-14 07:39 UTC, freben commented on .changeset/tiny-bulldogs-grow.md
> +'@backstage/plugin-azure-devops': patch
You still didn't change the package name.

2023-09-15 08:38 UTC, freben approved these changes

2023-09-15 08:38 UTC, merged

2023-09-25 06:24 UTC, taraknath555 commented
Hey @freben @awanlin just want to check about is this change is added in current release of 1.18.1 as after updating the backstage to same i.e. 1.18.1,  i am not able to take the advantage of the changes!

2023-09-25 14:06 UTC, awanlin commented
Hi @taraknath555, did you add the processor? This would be done in your `/packages/backend/src/plugins/catalog.ts` file and you would add this:

```ts
const integrations = ScmIntegrations.fromConfig(env.config);
 builder.addProcessor(new AnnotateScmSlugEntityProcessor(integrations))
  ```
  
  There'll be some imports as welll