Change styling in banner
backstage/backstage pull request #19507
Opened 2023-08-22 14:00 UTC by ivangonzalezacuna

## Hey, I just made a Pull Request!

This change allows the info banner to have a lighter background, which improves the readability for the link.

This is how it looked like before:

![Screenshot from 2023-08-22 15-58-39](https://github.com/backstage/backstage/assets/49096359/308cdbf9-a584-4a50-bb86-4f2b890fee79)

This is how it would look like now:

![Screenshot from 2023-08-22 15-58-28](https://github.com/backstage/backstage/assets/49096359/e1434936-375b-4e05-b85d-cde3edef7679)

I believe this new background color is nicer when the text is black. But feel free to suggest another color instead.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-08-23 11:55 UTC, benjdlambert commented
Hey :wave: where does the black dark text colour come from anyway here? I would like to dig into that before changing the background colour, because I could argue that the black shouldn't be there at all.

2023-08-23 14:54 UTC, ivangonzalezacuna commented
> Hey 👋 where does the black dark text colour come from anyway here? I would like to dig into that before changing the background colour, because I could argue that the black shouldn't be there at all.

Hi. For the tests I was using the announcements plugin. Which used the color `banner.link` if there's any `a` element in the message. Currently, it looks like the raw texts is using `white` and the `links` are in `black`. That's the reason. Here is the style used there: https://github.com/K-Phoen/backstage-plugin-announcements/blob/main/plugins/announcements/src/components/NewAnnouncementBanner/NewAnnouncementBanner.tsx#L17-L47

And so far, here is the only place in the repo where this `banner` palette is used: https://github.com/backstage/backstage/blob/master/packages/core-components/src/components/DismissableBanner/DismissableBanner.tsx (which is basically using the same styling, but defined in a slightly different way).

In our team we were also thinking about it, and it might make sense to analyze a little bit more the colors used in general for the `banner`, because depending on the alert type, the text might be hard to read.

2023-08-29 10:09 UTC, Rugvip commented
@tikabom you did something similar in #17695, do you happen to have an opinion on the new color choice? 😁

2023-09-04 15:55 UTC, Rugvip approved these changes
Approving the change as such, but would like feedback on the color choice.

@backstage/discoverability-maintainers if you're happy with the new color you can go ahead and merge

2023-09-12 21:02 UTC, tikabom requested changes
The new colour hex #348FCB unfortunately does not pass the WCAG standards against a white foreground: 
<img width="490" alt="image" src="https://github.com/backstage/backstage/assets/4676275/f23e3328-da95-4fd9-ba7b-709bfe3dede2">

The existing one #2E77D0 on the other hand does pass against both black and white foregrounds for AA (small and large texts) and AAA for large texts. Fails AAA for small texts but it's a better alternative to the one suggested in this PR. 

<img width="500" alt="image" src="https://github.com/backstage/backstage/assets/4676275/0c4658b2-33e5-4452-b4dd-b11f2f294a28">

2023-09-12 21:04 UTC, tikabom commented
We could possibly instead explore an alternative style (weight/colour) for the links in the banner?

2023-09-13 10:14 UTC, soapraj commented
https://dequeuniversity.com/rules/axe/4.4/color-contrast can help find another foreground color that passess the accessibility checks

2023-10-02 09:46 UTC, closed without merging