auth: add `oauth2` provider module
backstage/backstage pull request #19696
Opened 2023-08-31 12:55 UTC by awanlin

## Hey, I just made a Pull Request!

This migrates the `oauth2` provider to be a separate module

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-08-31 13:01 UTC, awanlin commented
Hi @Rugvip, so this has pretty much everything from the current `oauth2` provider, did run into some config that wasn't in the `config.d.ts` file so I made sure to include that in this version. Also, there's one outstanding item: the current provider has a `disableRefresh` option and I'm not sure how to implement that in this module. Here's the current code: https://github.com/backstage/backstage/blob/535f5fd6ce466baf29f2c3a3c2d06b9c9c80dca3/plugins/auth-backend/src/providers/oauth2/provider.ts#L139. 

Finally, the current provider has a test that it actually triggers the auth and checks the result, should I try and replicate that?

2023-09-05 08:14 UTC, Rugvip requested changes
Thank you! 🎉 

Do you want to do the final step an migrating `auth-backend` to use this new module instead of the existing implementation as well?

2023-09-05 08:14 UTC, Rugvip commented on .changeset/dull-eyes-pay.md
> +'@backstage/plugin-auth-backend-module-oauth2-provider': patch
```suggestion
'@backstage/plugin-auth-backend-module-oauth2-provider': minor
```

2023-09-08 19:21 UTC, awanlin commented on plugins/auth-backend-module-oauth2-provider/src/authenticator.ts
> +    return helper.refresh(input);
Can do, just a little stuck as to how I would get at the config, any suggestions?

2023-09-08 19:21 UTC, awanlin commented on .changeset/dull-eyes-pay.md
> +'@backstage/plugin-auth-backend-module-oauth2-provider': patch
Updated 👍

2023-09-12 10:53 UTC, Rugvip approved these changes
Nice! 👍 Looks good, thank you! 🎉 :shipit:

2023-09-12 10:53 UTC, merged

2023-09-12 11:40 UTC, awanlin commented
Thanks @Rugvip 🚀