react 18 props with children upgrade
backstage/backstage pull request #19707
Opened 2023-08-31 21:14 UTC by RobotSail

This PR aims to add PropsWithChildren explicitly on as many components as possible in order to make the React 18 upgrade easier.

Related to #18243 
#12252 

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-09-01 08:50 UTC, tudi2d requested changes
Thanks for the PR - definitly something to be fixed. I want to highlight the following alternative avoiding `PropsWithChildren` as we root for using `children?: React.ReactNode` in most places already (https://stackoverflow.com/a/71809927).

Other than that only a small change to remove `React.FC` required :)

2023-09-01 08:50 UTC, tudi2d commented on packages/core-components/src/components/Link/Link.test.tsx
> +    const wrapper: React.FC<React.PropsWithChildren<{}>> = ({ children }) => {
Heads-up for the following [`ADR` on `React.FC`](https://backstage.io/docs/architecture-decisions/adrs-adr006)

2023-09-04 14:12 UTC, freben commented on packages/core-app-api/src/app/AppContext.test.tsx
> +      wrapper: ({ children }: React.PropsWithChildren<{}>) => (
It's unfortunate to put upon us as consumers to add this type, should have been added on the renderHook side instead :) Does switching over to the replacement library let us sidestep this? :) https://github.com/testing-library/react-hooks-testing-library#a-note-about-react-18-support

2023-09-12 09:35 UTC, freben approved these changes
I'm good. @tudi2d how's your feeling on this one?

2023-09-12 09:35 UTC, freben commented on packages/test-utils/src/testUtils/appWrappers.tsx
> +  Component: ComponentType<PropsWithChildren<{}>> | ReactNode,
This is actually not technically necessary, albeit not exactly harmful either. The test renderer just wants to render any component, it doesn't care about adding children to it.

2023-09-12 09:44 UTC, tudi2d approved these changes
good work - let's ship it 🚢

2023-09-12 10:01 UTC, merged