Migrate sonarqube-backend plugin to the new backend system
backstage/backstage pull request #19781
Opened 2023-09-05 09:20 UTC by andym0457

## Hey, I just made a Pull Request!

Migrate sonarqube-backend plugin to the new backend system to contribute to the issue  #18301 

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-09-06 08:38 UTC, jhaals requested changes
Thanks for the PR, there are some fixes required and it would be great to add a test for the new `sonarqubePlugin`

2023-09-08 13:02 UTC, andym0457 commented
> Thanks for the PR, there are some fixes required and it would be great to add a test for the new `sonarqubePlugin`

Hi jhaals,
I have tried to address all the comments, if there's any mistakes let me know. I'm not sure how to test the new sonarqubePlugin as I was following the other backend plugins that have been merged and couldn't see tests that have been added

2023-09-12 08:30 UTC, jhaals requested changes
This looks better with the router now being wired up properly.

The diff for yarn.lock is however very large so this branch is either out of date or you might have forgot to run `yarn`

2023-09-15 13:20 UTC, andym0457 commented
> This looks better with the router now being wired up properly.
> 
> The diff for yarn.lock is however very large so this branch is either out of date or you might have forgot to run `yarn`

Hi @jhaals,

Think the issue with the yarn.lock should now be fixed? Is there any other comments in relation to this PR?

2023-09-18 11:17 UTC, jhaals commented
There's still a change needed to yarn.lock but a fairly small one. You can see that the post validation step is currently failing because `yarn` produces as diff. So if you commit the lock file from running yarn. It should be a quite small change.

2023-09-20 11:36 UTC, jhaals requested changes
CI Is currently failing because there are no updated API reports, please make sure to run `yarn build:api-reports` and commit the api report.

2023-09-20 11:40 UTC, jhaals requested changes
CI Is currently failing because there are no updated API reports, please make sure to run `yarn build:api-reports` and commit the api report.

2023-09-20 11:40 UTC, jhaals commented on plugins/sonarqube-backend/src/index.ts
> +export { sonarqubePlugin } from './plugin';
```suggestion
export { sonarqubePlugin as default } from './plugin';
```

2023-09-20 11:40 UTC, jhaals commented on packages/backend-next/src/index.ts
> +backend.add(sonarqubePlugin());
This is not how plugins are imported any longer, if you look at the example above this should be 
```suggestion
backend.add(import('@backstage/plugin-sonarqube-backend');
```

2023-09-20 11:40 UTC, jhaals commented on packages/backend-next/src/index.ts
> +import { sonarqubePlugin } from '@backstage/plugin-sonarqube-backend';
```suggestion
```

2023-09-25 11:51 UTC, jhaals requested changes
Thanks! Very small change left and then this is good to go 👍

2023-09-25 11:51 UTC, jhaals commented on plugins/sonarqube-backend/README.md
> ++ backend.add(sonarqubePlugin());
```suggestion
+ backend.add(import('@backstage/plugin-sonarqube-backend');
```

2023-09-25 11:51 UTC, jhaals commented on plugins/sonarqube-backend/README.md
> ++ import { sonarqubePlugin } from '@backstage/plugin-sonarqube-backend';
```suggestion
```

2023-09-26 11:32 UTC, jhaals approved these changes
Thank you 👏

2023-09-26 11:32 UTC, merged