TechInsight plugin - Export ScorecardInfo and ScorecardsList Components
backstage/backstage pull request #19994
Opened 2023-09-18 12:44 UTC by Rbillon59

## Hey, I just made a Pull Request!

Fixes : https://github.com/backstage/backstage/issues/19993

This PR aim to export ScorecardInfo and ScorecardsList Component to be able to use CheckResults directly without having to pass `checksId` to `EntityTechInsightsScorecardContent`

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-09-25 13:56 UTC, vinzscam requested changes
nice! just a minor changeset suggestion

2023-09-25 13:56 UTC, vinzscam commented on .changeset/twenty-bags-sin.md
> +Export ScorecardInfo and ScorecardsList Components to be able to use manually queried CheckResults directly.
```suggestion
Export `ScorecardInfo` and `ScorecardsList` components to be able to use manually queried check results directly.
```

2023-10-02 12:34 UTC, vinzscam approved these changes

2023-10-05 10:14 UTC, freben approved these changes

2023-10-05 10:14 UTC, merged

2024-03-13 08:36 UTC, Vity01 commented
@freben shouldn't be those components **ScorecardInfo** and **ScorecardsList** created with `createComponentExtension` instead of `createRoutableExtension` ? How can I reuse it out of the route `/tech-insight`? (let's say on the homepage or in my own component)?