Add support to graphql and playlist for the new backend
backstage/backstage pull request #20002
Opened 2023-09-18 20:45 UTC by zcason

## Hey, I just made a Pull Request!

I added support to graphql and playlist plugins for the new backend system.
GH Issue: #18301 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-09-20 11:51 UTC, jhaals commented on .changeset/eighty-wasps-remain.md
> +'@backstage/plugin-playlist-backend': patch
Let's make each plugin a separate changeset.

2023-09-20 11:52 UTC, jhaals commented on plugins/graphql-backend/README.md
> ++ backend.add(graphqlPlugin());
```suggestion
+ backend.add(import('@backstage/plugin-graphql-backend'));
```

2023-09-20 11:52 UTC, jhaals commented on plugins/playlist-backend/README.md
> ++ import { playlistPlugin } from '@backstage/plugin-playlist-backend';
```suggestion
```

2023-09-20 11:52 UTC, jhaals commented on plugins/playlist-backend/README.md
> ++ backend.add(playlistPlugin());
```suggestion
+ backend.add(import('@backstage/plugin-playlist-backend'));
```

2023-09-21 07:48 UTC, jhaals requested changes
Some minor changes, API reports also needs to be generated :)

2023-09-21 07:48 UTC, jhaals commented on plugins/graphql-backend/README.md
> +The grahpql backend plugin has support for the [new backend system](https://backstage.io/docs/backend-system/), here's how you can set that up:
Vale is not happy with this spelling. try GraphQL

2023-09-21 08:52 UTC, jhaals commented
Sorry @zcason, a little late but the GraphQL Plugin is in a bad state currently so let's not migrate it to the new backend system. Please exclude it entirely from this PR

2023-09-21 14:50 UTC, zcason commented
> Sorry @zcason, a little late but the GraphQL Plugin is in a bad state currently so let's not migrate it to the new backend system. Please exclude it entirely from this PR

No problem

2023-09-26 08:20 UTC, jhaals approved these changes
Thank you! 👍

2023-09-26 08:20 UTC, merged