Migrate nomad backend plugin to new backend system
backstage/backstage pull request #20105
Opened 2023-09-22 11:19 UTC by lavanya-sainik-ericsson

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-09-26 07:09 UTC, benjdlambert commented
hey @lavanya-sainik-ericsson :wave:

Looks like you'll need to update the api-reports here so that we can see what's happened! 

`yarn buiild:api-reports` should generate you some new `markdown` files that will need pushing to this branch in order to make the build green :tada:

2023-09-26 11:02 UTC, lavanya-sainik-ericsson commented
Hi [benjdlambert](https://github.com/benjdlambert),
Thanks for your comment. I have generated the api-report. Please have a look and let me know if any more comments / corrections needed.

2023-10-02 11:12 UTC, benjdlambert requested changes
Just a quick comment on the docs :)

2023-10-02 11:12 UTC, benjdlambert commented on plugins/nomad-backend/README.md
> ++ backend.add(nomadPlugin());
I think that these docs can be replaced with the example above:

```
backend.add(import('...'))
```

instead :)

2023-10-02 12:24 UTC, lavanya-sainik-ericsson commented
Hey [benjdlambert](https://github.com/benjdlambert), 

Thanks for your comment. Done that change :) Please have a look and let me know if any more comments / corrections needed.

2023-10-04 10:56 UTC, lavanya-sainik-ericsson commented
Hey [benjdlambert](https://github.com/benjdlambert),

Thanks  :) Please have a look again and let me know if any more comments / corrections needed.

2023-10-04 11:17 UTC, benjdlambert approved these changes
Nice thanks :tada:

2023-10-04 11:17 UTC, merged