add i18n to some components in scaffolder plugin
backstage/backstage pull request #20130
Opened 2023-09-23 21:33 UTC by angeliski

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-09-23 22:04 UTC, Rugvip requested changes
Awesome, thank you! :tada:

2023-09-23 22:04 UTC, Rugvip commented on plugins/scaffolder/src/translation.ts
> +export const scaffolderTranslationRef = createTranslationRef({
Let's mark this as @alpha and export it via /alpha too

2023-09-23 22:12 UTC, Rugvip commented
Ah another bit: you can provide translations for other languages to createTranslationRef. This is all still very early, but you can see it in action in tests: https://github.com/backstage/backstage/blob/d4a8a921699aed81db801bf6ff32716ca7c9e8d4/packages/core-plugin-api/src/translation/TranslationResource.test.ts#L64

2023-09-25 08:41 UTC, benjdlambert commented
@angeliski I'd also like to push towards adding i18n to things that's in the `next` folder as a priority as those things will hopefully become the default components moving forward after this next mainline release. :pray:

2023-10-11 13:08 UTC, closed without merging

2023-10-12 12:54 UTC, angeliski commented on plugins/scaffolder/src/translation.ts
> +    failed_to_load_installed_actions: 'Failed to load installed actions',
Nice! I will try some tricks with https://eslint.org/docs/latest/rules/sort-keys