[TechDocs] Enhance PlantUML support in the techdocs container to include external puml or pu files
backstage/backstage pull request #20229
Opened 2023-09-28 14:47 UTC by lavanya-sainik-ericsson

Issue Reference #20184

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-09-28 19:53 UTC, awanlin commented on docs/features/techdocs/how-to-guides.md
> +## How to render plantUML diagram in TechDocs
```suggestion
## How to render PlantUML diagram in TechDocs
```

2023-09-28 19:55 UTC, awanlin requested changes
Thanks for this contribution @lavanya-sainik-ericsson, just left a few small corrections 👍

2023-09-28 19:55 UTC, awanlin commented on docs/features/techdocs/how-to-guides.md
> +PlantUML allows to create diagrams from plain text language. Each diagram description begins with the keyword - (@startXYZ and @endXYZ, depending on the kind of diagram). For UML Diagrams, Keywords @
```suggestion
PlantUML allows you to create diagrams from plain text language. Each diagram description begins with the keyword - (@startXYZ and @endXYZ, depending on the kind of diagram). For UML Diagrams, Keywords @startuml & @enduml should be used. Further details for all types of diagrams can be found at [PlantUML Language Reference Guide](https://plantuml.com/guide).
```

2023-09-28 19:55 UTC, awanlin commented on docs/features/techdocs/how-to-guides.md
> +PlantUML allows to create diagrams from plain text language. Each diagram description begins with the keyword - (@startXYZ and @endXYZ, depending on the kind of diagram). For UML Diagrams, Keywords @
```suggestion
PlantUML allows you to create diagrams from plain text language. Each diagram description begins with the keyword - (@startXYZ and @endXYZ, depending on the kind of diagram). For UML Diagrams, Keywords @startuml & @enduml should be used. Further details for all types of diagrams can be found at [PlantUML Language Reference Guide](https://plantuml.com/guide).
```

2023-10-03 14:36 UTC, lavanya-sainik-ericsson commented
Hello [awanlin](https://github.com/awanlin),

Thanks for your comments. Have done those changes. Let me know if any more corrections needed or it can be merged.

2023-10-11 18:56 UTC, johnphilip283 approved these changes

2023-10-11 19:05 UTC, awanlin approved these changes

2023-10-11 19:06 UTC, awanlin commented
@johnphilip283 thanks for the review and approval. Feel free to merge when you have time, that's not something I've generally done

2023-10-11 19:08 UTC, merged