Scaffolder
backstage/backstage pull request #20281
Opened 2023-09-29 16:39 UTC by tperehinets

## Hey, I just made a Pull Request!

Issue: #18739

I fixed `featureFlag` in `scaffolder/next`.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-09-29 16:47 UTC, tperehinets commented
@camilaibs and @benjdlambert , thanks for the feedback in my previous pull request! My previous branch was causing issues with `concurrently`, so I decided to create another one.

2023-10-02 13:25 UTC, benjdlambert requested changes
Thanks for this! Just a few comments - also would be good to add some tests for the hook and the Workflow component changes.

2023-10-02 13:25 UTC, benjdlambert commented on plugins/scaffolder-react/src/next/components/Workflow/Workflow.tsx
> +  const filterOutStepProperties = useCallback(() => {
Can we move this out into a hook somewhere else other than this component?

Maybe in the `../../hooks` directory.

Something like `useFeatureFlaggedProperties()` or something?

2023-10-02 13:25 UTC, benjdlambert commented on plugins/scaffolder-react/src/next/components/Workflow/Workflow.tsx
> +// import { clone } from 'lodash/fp';
remove this.

2023-10-09 13:41 UTC, benjdlambert commented
@tperehinets is there anything we can help with here? :pray:

2023-10-11 17:44 UTC, tperehinets commented
> @tperehinets is there anything we can help with here? 🙏

Apologies for the delay, and thank you very much for your feedback. I've made the required adjustments. However, I have found that the hook `useTemplateSchema` is supposed to filter out properties that are not enabled with the feature flag. But, it does not filter the steps. Does that mean that it's better to enable sorting in `useTemplateSchema`, or implement a `useFeatureFlaggedProperties` hook as you recommend?

2023-10-30 16:01 UTC, benjdlambert commented on plugins/scaffolder-react/alpha-api-report.md
> +export const useFeatureFlaggedProperties: (
`useFilteredSchemaProperties` or something? Maybe don't have to mention feature flags in the hook itself actually. Thinking it's a little cleaner as to what it's doing.

2023-11-06 18:22 UTC, benjdlambert commented
@tperehinets  do you have time to fix this up? :pray: Would also be pretty good to add some tests too? :pray:

2023-11-13 10:08 UTC, benjdlambert approved these changes
Thanks for this! And the patience @tperehinets :tada:

2023-11-13 10:21 UTC, dagda1 approved these changes
Nice work!  This is definitely needed

2023-11-13 13:53 UTC, tperehinets commented
@benjdlambert thank you so much for the feedback!

2023-11-13 15:09 UTC, benjdlambert commented
@tperehinets could you look at some of these test failures? Not really sure what's going on here.

2023-11-14 08:49 UTC, benjdlambert commented
@tperehinets nevermind I think I got it - want to get this in before the release today :tada:

2023-11-14 09:06 UTC, merged