Fix `authenticate()` ctx properties being missing
backstage/backstage pull request #20317
Opened 2023-10-02 14:24 UTC by mitchhentgesspotify

The return value of `initialize()` is a `Promise<...>`, but it wasn't being `await`'d before being passed to `authenticator.authenticate(...)`.

This was causing the `gcpIap` provider to fail on the `/request` endpoint because `jwtHeader` was undefined.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-10-02 16:52 UTC, Rugvip requested changes
Good find! 👍 

The context is really intended to be sync actually, matching the way the OAuth equivalent is implemented. Could we switch it around so that https://github.com/backstage/backstage/blob/7accd01a2cde796a4ee474e56dd2b7057cd404e0/plugins/auth-node/src/proxy/types.ts#L24 returns `TContext` instead? along with whatever else that entails 😅

I feel it's better that way because it discourages any kind of async work at init which realistically you'd always want to do on demand or retry instead.

2023-10-03 15:09 UTC, Rugvip requested changes
Nice! 👍 

Just needs a changeset for the gcp-iap module too, enough to just mention that it's updated to the most recent `auth-node` APIs

2023-10-06 09:58 UTC, nikolaik commented
We were hit by this as well. Looking forward to have this land <3

2023-10-09 14:41 UTC, Rugvip approved these changes
Let's :shipit: !

2023-10-09 14:41 UTC, merged