Microsoft authentication doc clafications
backstage/backstage pull request #20666
Opened 2023-10-18 22:17 UTC by afscrome

* Add API Permissions to the app registration setup
* Encouraged re-use of an existing app registration over creating a new one.
* Moved the `Adding the provider to the Backstage front end` higher up so it's not so easily missed

Updated the microsoft authentication document to include details on adding API Permissions. At more relaxed companies, these permissiosn will be silently added to this list the first time they're requested, however in more locked down companies, a directory admin will need to consent to these permissions before users can use them.

Also slighlty reworked the docs to encourate re-using any existing app registration.  This includes renaming the `AUTH_MICROSOFT_*` variables to match the `AZURE_*` ones used throughout other azure integrations.

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-10-19 00:02 UTC, awanlin requested changes
Looks good @afscrome, left a pair of minor comments.

While you have this open would it make sense to start adding mention to Microsoft Entra ID? Totally optional, will leave that for you to decide

2023-10-19 00:02 UTC, awanlin commented on docs/auth/microsoft/provider.md
> +![App Registration Permissions](permissions.png)
```suggestion
![App Registration Permissions](./permissions.png)
```
When I use the rich preview this is a broken image for me, wondering if you need the `./` as suggested above

2023-10-19 00:02 UTC, awanlin commented on docs/auth/microsoft/provider.md
> +- **Redirect URI**: `http://your-backstage.com/api/auth/microsoft/handler/frame` (for local dev, typically `http://localhost:7007/api/auth/microsoft/handler/frame`)
```suggestion
- **Redirect URI**: `https://your-backstage.com/api/auth/microsoft/handler/frame` (for local dev, typically `http://localhost:7007/api/auth/microsoft/handler/frame`)
```

2023-10-19 00:05 UTC, awanlin commented on docs/auth/microsoft/provider.md
> +![App Registration Permissions](permissions.png)
Never mind, looks fine when I view it in your branch 👍

2023-10-19 08:53 UTC, afscrome commented
Re the Entra ID rename, I did start but it blew up in scope so I think it makes sense for a separate PR.

Microsoft have a handy script to help with the rename, although it will also need some manual work on top as we'll want to leave a few `formerly Azure Active Directory` phrases around as not everyone is familiar with the new name, and we'll also want the docs to show up if someone searches for aad.
 https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/how-to-rename-azure-ad#sample-powershell-script

2023-10-19 12:13 UTC, awanlin approved these changes
Awesome, thanks again @afscrome for taking the time to make these changes, they have a huge positive impact! 🚀 

For the name change thanks for the details and for taking a try at it, I agree it's probably best for its own PR 👍

2023-10-23 19:37 UTC, vinzscam approved these changes

2023-10-26 20:35 UTC, grvpandey11 requested changes

2023-10-26 20:35 UTC, grvpandey11 commented on docs/auth/microsoft/provider.md
> +        clientSecret: ${AZURE_CLIENT_ID}
Isn't it should be AZURE_CLIENT_SECRET

2023-10-26 20:47 UTC, awanlin commented on docs/auth/microsoft/provider.md
> +        clientSecret: ${AZURE_CLIENT_ID}
Good catch!

2023-10-26 20:53 UTC, afscrome commented on docs/auth/microsoft/provider.md
> +        clientSecret: ${AZURE_CLIENT_ID}
🤦 absolutely

2023-10-30 15:57 UTC, benjdlambert approved these changes
Nice! thanks :tada"

2023-10-30 15:58 UTC, merged