Create docker-tags.yaml
backstage/backstage pull request #20776
Opened 2023-10-24 16:54 UTC by pascalwilbrink

## Hey, I just made a Pull Request!
I've created a plugin that displays the Docker tags for a specific component

#### :heavy_check_mark: Checklist

I don't think the next checklist is applicable :)

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-10-24 17:59 UTC, awanlin requested changes
Thanks for the contribution @pascalwilbrink, left a comment about the documentation link

Would also be great to get an image of what this feature looks like in use in your docs so that potential users have a feel for the features

2023-10-24 17:59 UTC, awanlin commented on microsite/data/plugins/docker-tags.yaml
> +documentation: 'https://raw.githubusercontent.com/Work-m8/backstage-docker-plugin/main/README.md'
```suggestion
documentation: 'https://github.com/Work-m8/backstage-docker-plugin/blob/main/README.md'
```

This get's you the raw Markdown, you probably want to use this 👆

2023-10-24 18:59 UTC, pascalwilbrink commented
@awanlin, Thanks for you suggestions :D I've updated the yaml file and added some screenshots in the README.md

2023-10-24 19:23 UTC, awanlin approved these changes
Looking good @pascalwilbrink 🚀 

We just need a review and approval from one of the maintainers now

2023-10-24 23:00 UTC, pascalwilbrink commented
Looks like a flaky gh action

2023-10-25 12:57 UTC, tudi2d approved these changes
Welcome to the community & thanks for adding yourself to the Plugins Directory! 🎉

2023-10-25 12:57 UTC, tudi2d commented on microsite/data/plugins/docker-tags.yaml
> +authorUrl: 'https://github.com/work-m8/.github'
Do you actually want to redirect to the repository? Or the organisation? :)

```suggestion
authorUrl: 'https://github.com/work-m8'
```

2023-11-01 19:50 UTC, pascalwilbrink commented
Any updates on this?

2023-11-07 09:19 UTC, freben approved these changes

2023-11-07 09:19 UTC, merged