Bug/18436 entity unregister redirect
backstage/backstage pull request #20786
Opened 2023-10-25 09:23 UTC by NeuralEvolution

## Hey, I just made a Pull Request!

fixes #18436 navigates to catalog root using rootRouteRef after successfully unregistering and entity.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-10-25 13:38 UTC, benjdlambert commented
Hey @NeuralEvolution! Thanks for the contribution!

There's a little bit more context here that I think you might have missed from a previous attempt at this work, but I think it would be good if we used an `externalRouteRef`here instead.

https://github.com/backstage/backstage/pull/18894#issuecomment-1714125186

2023-10-26 12:49 UTC, mprinold commented
@benjdlambert Updated the solution to include the external route ref and fall back to the catalog root route ref if no external one is bound. 

After those commits i rebased the fork and this branch as it was behind original and now i'm seeing failing checks. Could do with a bit of guidance on this please.

2023-10-26 13:29 UTC, benjdlambert commented
I think that these are failing because of a bad yarn lock because of the addition to `package.json`.

Quick look through the PR though you might not need that dependency at all. As it uses `useNavigate` from `react-router-dom` so maybe mock that instead?

https://github.com/backstage/backstage/pull/20786/files#diff-2b97bcc2e16b1532a23a6719b7a254379e2497905ce705e57685650d74b577fcR52

2023-10-27 08:16 UTC, NeuralEvolution commented
@benjdlambert yeah i originally was going to mock useNavigate from react-router-dom however there are other tests in the file that rely on it so that wasn't an option and it seems you cant spy on it either as you get an error "Cannot redefine property useNavigate" which is why i went down the approach of spying on useNavigate from react-router.

2023-10-27 12:33 UTC, NeuralEvolution commented
@benjdlambert all checks passing again now

2023-10-30 16:25 UTC, benjdlambert requested changes
Nice thanks for this :tada: Think that this is looking pretty good just a few nits.

2023-10-30 16:25 UTC, benjdlambert commented on plugins/catalog/src/routes.ts
> +  id: 'unregister-redirect',
we normally try namespace these. something like `catalog:unregister-redirect` or something works.

2023-10-30 16:25 UTC, benjdlambert commented on .changeset/lucky-kids-cough.md
> +fixes bug where after unregistering an entity you are redirected to "/". Adds an optional external route "unregisterRedirect" into the catalog plugin which when bound will be navigated to on successf
```suggestion
- Fixes bug where after unregistering an entity you are redirected to `/`.
- Adds an optional external route `unregisterRedirect` to override this behaviour to another route.
```

2023-11-16 09:10 UTC, NeuralEvolution commented
@benjdlambert requested changes made, rebased with master branch and all checks passing again.

2023-11-20 13:45 UTC, merged