Master
backstage/backstage pull request #20812
Opened 2023-10-25 21:39 UTC by PurseChicken

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-10-30 16:30 UTC, benjdlambert requested changes
Hey :wave: thanks for this!

Think this is a good step in the right direction for sure.

I wonder though if we can take some inspiration from the `catalog` plugin and show `diff` patches for where code should be inserted to keep them easier to follow?

Thoughts?

2023-11-04 05:21 UTC, PurseChicken commented
> Hey 👋 thanks for this!
> 
> Think this is a good step in the right direction for sure.
> 
> I wonder though if we can take some inspiration from the `catalog` plugin and show `diff` patches for where code should be inserted to keep them easier to follow?
> 
> Thoughts?

Sorry for the delay here.

I went ahead and reviewed the catalog ReadMe and implemented the diff's into this ReadMe via the latest commit. Let me know if that's in alignment with what you were thinking.

Thanks!

2023-11-06 19:02 UTC, vinzscam commented on plugins/cloudbuild/README.md
> +#### In your 'cicdContent' const, add the following switch case
```suggestion
#### In your `cicdContent` const, add the following switch case
```

2023-11-06 21:51 UTC, benjdlambert approved these changes
Thanks! :tada:

2023-11-06 21:52 UTC, benjdlambert commented
@PurseChicken one thing, we will need to you to sign the commits using DCO. You can see how to do that in the comment: https://github.com/backstage/backstage/pull/20812#issuecomment-1780097621

2023-11-07 04:24 UTC, PurseChicken commented
> @PurseChicken one thing, we will need to you to sign the commits using DCO. You can see how to do that in the comment: [#20812 (comment)](https://github.com/backstage/backstage/pull/20812#issuecomment-1780097621)

I folled the documentation and it seems because I synced my fork its trying to pull in a bunch of other commits due to the rebase. Should I just redo this PR?

2023-11-07 10:47 UTC, freben commented
@PurseChicken maybe it's easiest at this point - there's _always_ some git magic you can pull to get out of a hole like this, but sometimes it's just easier to just start over quickly

2023-11-08 01:31 UTC, PurseChicken commented
I am closing this PR and will be re-submitting.

2023-11-08 01:31 UTC, closed without merging

2023-11-08 02:39 UTC, PurseChicken commented
New PR is at https://github.com/backstage/backstage/pull/21069