Update docker.md
backstage/backstage pull request #20836
Opened 2023-10-26 12:40 UTC by fsilvaortiz

Git and node-gyp installation is added. Without these, errors occur when trying to create the image.

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-10-26 13:27 UTC, awanlin commented
Hi @fsilvaortiz, thanks for this contributions but the solution in this PR is probably the better way for us to handle this: https://github.com/backstage/backstage/pull/20695. What do you think?

2023-10-26 16:15 UTC, fsilvaortiz commented
Hi @awanlin, that PR fixes the missing node-gyp package and it's a better solution. I added the git package only to address this warning:

 [build 8/9] RUN yarn --cwd packages/backend build                                                                                                                                                                                                                                                                                                      8.1s
 => => # app:  WARNING: Failed to read git commit, ExitCodeError: Command 'git rev-parse HEAD' exited with code 127
 => => # app:
 => => # app:  /bin/sh: 1: git: not found
 => => # app:
 => => # app:  WARNING: Failed to describe git version, ExitCodeError: Command 'git describe --always' exited with code 127

2023-10-26 16:31 UTC, awanlin commented
As that output from git is just warnings and not actually errors that impact functionality I'm not sure it needs to be added. But if we do add this there are several other places that should be updated as well

@freben @vinzscam what do you think?

2023-11-06 14:22 UTC, freben commented
Agreed, just merged #20695 now for the node-gyp change.

Regarding the git warning - am I right in understanding that you are performing the multi-stage build, so you do the build step inside a docker image? @awanlin is correct that in a sense it doesn't affect runtime much, except that it does make it possible to inspect the built commit and version in the interface later on. In the spirit of wanting to have the dockerized build have the same features as the host build, I don't mind much adding git there but only there.

So if you scale this PR down to only the git change, I think we're good 👍

2023-11-07 15:53 UTC, fsilvaortiz commented
Hi! I undid the change of node-gyp installation and left only the git one.

2023-11-07 16:42 UTC, awanlin requested changes
Looks good just one small nit then I think we are good 👍

2023-11-07 16:42 UTC, awanlin commented on docs/deployment/docker.md
> +
Can we remove this extra space, please?

2023-11-07 18:16 UTC, awanlin approved these changes
Awesome! Thanks @fsilvaortiz 🚀

2023-11-14 20:37 UTC, awanlin commented
Hi @freben, can you give this a quick look, please? It's a small change, looks ready to merge from my perspective 👍

2023-11-14 21:50 UTC, freben commented
Build is still red though. Something is making prettier angry - the second line looks unexpected right?

2023-11-15 15:09 UTC, awanlin commented
> Build is still red though. Something is making prettier angry - the second line looks unexpected right?

Shoot, missed that, thought it was just the reoccurring microsite issues :(

@fsilvaortiz can you take a look at this, please?

2023-11-16 13:00 UTC, freben commented
Hey sorry, I see DCO is failing too - replacing this with #21348, thanks for raising this 🙏

2023-11-16 13:00 UTC, closed without merging