Add core nav logo extension
backstage/backstage pull request #20847
Opened 2023-10-26 23:12 UTC by craigtracey

## Hey, I just made a Pull Request!

Customizing the look and feel of Backstage sometimes requires altering the Core Nav logos. This feature introduces a createNavLogoExtension so that users may utilize their own logos.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-11-14 09:09 UTC, camilaibs reviewed
Thanks for starting experimenting with extensions, we are looking for feedback 🎉 

It seems something that adopters could configure via configuration file instead of having to create an extension to customise it through code...
Have you thought about the sidebar extension receiving the logos path via configuration file?

I would like to hear @backstage/maintainers  thoughts as well 🙂 .

2023-11-22 10:56 UTC, Rugvip requested changes
Discussed a bit more, and let's ship this 👍 

Could you apply the suggestion? Don't have access to edit your fork

2023-11-22 22:15 UTC, Rugvip requested changes

2023-11-22 22:15 UTC, Rugvip commented on packages/frontend-plugin-api/src/extensions/createNavLogoExtension.tsx
> +      bind({
Ah, the factory interface has been updated to return outputs rather than call bind

2023-11-22 22:20 UTC, craigtracey commented
Yeah, I'm on it.

On Wed, Nov 22, 2023, 5:15 PM Patrik Oldsberg ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In packages/frontend-plugin-api/src/extensions/createNavLogoExtension.tsx
> <https://github.com/backstage/backstage/pull/20847#discussion_r1402757832>
> :
>
> > + * @public
> + */
> +export function createNavLogoExtension(options: {
> +  id: string;
> +  logoIcon: JSX.Element;
> +  logoFull: JSX.Element;
> +}) {
> +  const { id, logoIcon, logoFull } = options;
> +  return createExtension({
> +    id,
> +    attachTo: { id: 'core.nav', input: 'logos' },
> +    output: {
> +      logos: coreExtensionData.logoElements,
> +    },
> +    factory: ({ bind }) => {
> +      bind({
>
> Ah, the factory interface has been updated to return outputs rather than
> call bind
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/backstage/backstage/pull/20847#pullrequestreview-1745453207>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIBOF7BJOJTAW7H7XRBJ6LYFZ2P5AVCNFSM6AAAAAA6R6RHUOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONBVGQ2TGMRQG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-22 23:54 UTC, Rugvip approved these changes
Thank you! Let's :shipit:

2023-11-22 23:54 UTC, merged