feat: add the entire entity to `EntityNodeData`
backstage/backstage pull request #20974
Opened 2023-11-03 21:04 UTC by benkeil

## Hey, I just made a Pull Request!

Add the entire entity to `EntityNodeData` to allow better customisation.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

resolve #20594

2023-11-07 08:10 UTC, camilaibs requested changes
Thank you for contributing with us, left only two minor comments 🙂

2023-11-07 08:10 UTC, camilaibs commented on .changeset/long-sheep-exercise.md
> +Add the entire `Entity` to `EntityNodeData`
Could you write a bit more details about what changed and add one example of how to use the entity instead of the individual properties?

2023-11-07 19:09 UTC, benkeil commented on plugins/catalog-graph/api-report.md
> -  spec?: JsonObject;
How do I do that? Adding an annotation to the properties, doesn't change the output of the api report.

2023-11-08 15:35 UTC, freben approved these changes

2023-11-09 08:58 UTC, camilaibs commented on plugins/catalog-graph/api-report.md
> -  spec?: JsonObject;
Interesting! I thought adding the deprecated annotation would be enough...
Any ideas @freben ?

2023-11-09 08:59 UTC, camilaibs approved these changes
Amazing, thanks again 🙌🏻

2023-11-09 08:59 UTC, merged

2023-11-09 12:27 UTC, benkeil commented
when we want to remove the deprecate fields?