Adds blog entry about KubeCon NA 23
backstage/backstage pull request #21308
Opened 2023-11-15 09:40 UTC by jorgelainfiesta

## Hey, I just made a Pull Request!

Adding a blog post about BackstageCon and KubeCon NA '23

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-11-15 13:35 UTC, vinzscam commented on microsite/blog/2023-11-15-backstagecon-kubecon-23.mdx
> +Hellen Greul, Head of Engineering for Backstage at Spotify, hosted [a panel discussion](https://www.youtube.com/watch?v=Iti5glzYOG8&list=PLj6h78yzYM2PxiInfZi2OKu1KluNfbLtc&index=10) with four adopter
```suggestion
Helen Greul, Head of Engineering for Backstage at Spotify, hosted [a panel discussion](https://www.youtube.com/watch?v=Iti5glzYOG8&list=PLj6h78yzYM2PxiInfZi2OKu1KluNfbLtc&index=10) with four adopters that are using Backstage at scale: Twilio, Lunar Bank, US Bank, and Expedia. The crucial role of Backstage in fostering inner sourcing and simplifying new hires onboarding were a few of the subjects covered in the panel.
```

2023-11-15 13:35 UTC, vinzscam commented on microsite/blog/2023-11-15-backstagecon-kubecon-23.mdx
> +The next KubeCon Europe is scheduled for March 18-22 in Paris.We're looking forward to meeting you all there! [KubeCon EU](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/program/cfp
```suggestion
The next KubeCon Europe is scheduled for March 18-22 in Paris. We're looking forward to meeting you all there! [KubeCon EU](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/program/cfp/) and[ BackstageCon EU](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/co-located-events/backstagecon/) are accepting CFPs, submit your proposal now!
```

2023-11-15 14:01 UTC, jamieklassen commented on microsite/blog/2023-11-15-backstagecon-kubecon-23.mdx
> +With a whopping peak attendance of 400+ people, the crowd nearly doubled from last year,[ taking the center stage of the conference](https://www.forbes.com/sites/janakirammsv/2023/11/14/backstage-pro
```suggestion
With a whopping peak attendance of 400+ people, the crowd nearly doubled from last year,[ taking the center stage of the conference](https://www.forbes.com/sites/janakirammsv/2023/11/14/backstage-project-takes-center-stage-at-kubecon-north-america-2023/?sh=1972303a6539), as reported by Forbes. For some, BackstageCon was their first entry point into the community, but the event also boasted lots of  familiar faces, mostly from some of the most mature adopters such as Dynatrace, Lunar, and US Bank. We also got to hear from new voices in the community like Comcast and Grafana Labs.
```

2023-11-15 14:01 UTC, jamieklassen commented on microsite/blog/2023-11-15-backstagecon-kubecon-23.mdx
> +How adopters are using Backstage was also a highlight of the day. B3, Brazil's Stock Exchange, shared [how they're building their developer portal](https://www.youtube.com/watch?v=FyWCKIVYO7g&list=PL
```suggestion
How adopters are using Backstage was also a highlight of the day. B3, Brazil's Stock Exchange, shared [how they're building their developer portal](https://www.youtube.com/watch?v=FyWCKIVYO7g&list=PLj6h78yzYM2PxiInfZi2OKu1KluNfbLtc&index=14). And from Grafana Labs, we heard how they're using [Backstage along Crossplane to drive GitOps](https://www.youtube.com/watch?v=q-JUWob69Hw&list=PLj6h78yzYM2PxiInfZi2OKu1KluNfbLtc&index=10).
```

2023-11-15 14:08 UTC, jamieklassen commented on microsite/blog/2023-11-15-backstagecon-kubecon-23.mdx
> +The interest from the cloud-native community in Backstage did not waiver this year. Instead, the Backstage booth in the KubeCon Project Pavillion saw a nonstop flux of visitors asking more about the
waiver = document relinquishing a claim
waver = be undecided; become unreliable
```suggestion
The interest from the cloud-native community in Backstage did not waver this year. Instead, the Backstage booth in the KubeCon Project Pavillion saw a nonstop flux of visitors asking more about the project. There were three talks featuring Backstage during KubeCon.
```

2023-11-15 14:09 UTC, jamieklassen commented on microsite/blog/2023-11-15-backstagecon-kubecon-23.mdx
> +Backstage maintainers Ben and Patrick addressed a full-room during their talk “Simplifying Backstage - Breaking the Code Barrier” in which they explained Declarative Integrations, how it works and th
```suggestion
Backstage maintainers Ben and Patrik addressed a full-room during their talk “Simplifying Backstage - Breaking the Code Barrier” in which they explained Declarative Integration, how it works and the expected migration path. Declarative Integration will enable adopters to define the plugins they use—and even customize them—without dealing with Node or React. The mechanism relies on abstracting away the complexity behind a declaration of routes and configs defined in YAML.
```

2023-11-15 15:58 UTC, vinzscam approved these changes
🌟

2023-11-15 17:13 UTC, jorgelainfiesta commented
> The DCO check might not like the signoff line on [516d6d8](https://github.com/backstage/backstage/commit/516d6d80405508a376d394568778468bdeaffac9), which has the email `jorgelainfiesta@users.noreply.github.com` as opposed to the others which have `jlainfiestarosales@spotify.com`. I wonder if the check will consider both to be well-enough associated to you for license purposes?

Ah I see, so it didn't like the GitHub commit. I'll have to redo that commit

2023-11-16 09:01 UTC, Rugvip requested changes
:tada:, just a few nits on the DI details

2023-11-16 10:15 UTC, freben approved these changes

2023-11-16 10:19 UTC, Rugvip approved these changes

2023-11-16 10:19 UTC, merged