Add Highlights plugin to plugins marketplace
backstage/backstage pull request #21441
Opened 2023-11-20 18:45 UTC by radoslaw-sz

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-11-20 20:45 UTC, awanlin requested changes
Thanks for wanting to add this to the Plugins Directory @radoslaw-sz, just left one comment 👍

2023-11-21 07:45 UTC, radoslaw-sz commented on microsite/data/plugins/highlights.yaml
> +npmPackageName: '@rsc-labs/backstage-highlights-plugin'
Sure will do, thanks!
Additionally, I made a mistake mentioning Gerrit instead of Github, so I will correct it also.

2023-11-21 13:33 UTC, awanlin commented on microsite/data/plugins/highlights.yaml
> +npmPackageName: '@rsc-labs/backstage-highlights-plugin'
Great, just follow up here so we know to review it again 👍

2023-11-21 15:44 UTC, radoslaw-sz commented on microsite/data/plugins/highlights.yaml
> +npmPackageName: '@rsc-labs/backstage-highlights-plugin'
hi @awanlin
1) I fixed description from Gerrit to Github
2) I made updates to READMEs - in frontend README I mention backend with a link, in backend README I mention frontend with a link.

2023-11-21 15:47 UTC, awanlin requested changes
Getting there, just one more small change, please

2023-11-21 15:47 UTC, awanlin commented on microsite/data/plugins/highlights.yaml
> +description: Highlight what is important for you and put it on front for the quick view and access. Built-in support of Git information from Github and Gitlab.
```suggestion
description: Highlight what is important for you and put it on front for the quick view and access. Built-in support of Git information from GitHub and GitLab.
```

2023-11-21 15:56 UTC, radoslaw-sz commented on microsite/data/plugins/highlights.yaml
> +description: Highlight what is important for you and put it on front for the quick view and access. Built-in support of Git information from Github and Gitlab.
Sure, done

2023-11-21 16:48 UTC, tudi2d approved these changes

2023-11-21 17:32 UTC, awanlin approved these changes

2023-11-21 17:34 UTC, awanlin commented
@tudi2d not sure what else is needed? Feel free to merge when you can! 🚀

2023-11-23 09:56 UTC, merged