implement text based entity card/content filters
backstage/backstage pull request #21480
Opened 2023-11-22 16:11 UTC by freben

2023-11-22 18:05 UTC, freben commented
One thing of note here is that the filter builder throws errors. This does probably fail "too hard", leading to error overlays if you have bad syntax problems. We may want to compile forgivingly (making filters more permissive in the face of failures, ie ignoring restriction clauses) and emitting warnings instead.

2023-11-23 13:13 UTC, Rugvip requested changes
Nice 😎

Main tricky bit for me is the interaction between plugin builder and integrator when it comes to filter definitions, there's a comment starting up that discussion. Rest is mostly nits 😅

2023-11-23 13:13 UTC, Rugvip commented on plugins/catalog/src/alpha/plugin.tsx
> +    unregister: convertLegacyRouteRef(unregisterRedirectRouteRef),
https://github.com/backstage/backstage/pull/21481/files#diff-8172f1eed894166ce8329a218913d4b4b6dc47a3357ec8e6d404b9774c4dabf6 😅, I'll extract it, https://github.com/backstage/backstage/pull/21495

2023-11-23 14:52 UTC, freben commented on plugins/catalog-common/alpha-api-report.md
> +export function parseFilterExpression(
Made it internal!

2023-11-23 14:52 UTC, freben commented on plugins/catalog-common/alpha-api-report.md
> +    ) => void;
yah, returned an array instead

2023-11-23 15:37 UTC, freben commented on plugins/catalog-react/src/alpha.tsx
>  >('plugin.catalog.entity.filter');
alright, done!

2023-11-23 15:39 UTC, freben commented on plugins/catalog-common/src/filter/matrchers/createIsMatcher.ts
> +  };
sure! done

2023-11-23 15:43 UTC, freben commented on plugins/catalog-common/src/filter/matrchers/createHasMatcher.ts
> +    },
Or `annotation:github.com/project-slug` or `field:metadata.annotations.github.com/project-slug` perhaps. `has` was meant to be an easy-to-type, quick and "semantic" set of common utilities that you want for your entities. So with that philosophy, you'd add a custom `has` extension, perhaps making it `has:github-project-slug`? Or `is:github-enabled` or `has:github-annotations`? But yeah, the question becomes how plugins can provide those, then.

2023-11-28 13:31 UTC, Rugvip approved these changes
:shipit:

2023-11-28 13:31 UTC, merged