Added support of UnifiedThemeProvider in Page component
backstage/backstage pull request #21482
Opened 2023-11-22 17:38 UTC by IlyaSavich

Added support of UnifiedThemeProvider in Page component

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-11-23 09:57 UTC, IlyaSavich commented
@camilaibs @benjdlambert could you pls help me a bit with these storybooks, what am I missing ?

2023-11-23 12:32 UTC, camilaibs commented
> @camilaibs @benjdlambert could you pls help me a bit with these storybooks, what am I missing ?

Hi 👋🏻 ,
Here you can find details about build errors:
https://www.chromatic.com/build?appId=5eafd13eaebb8f00227540f4&number=10911
![image](https://github.com/backstage/backstage/assets/6290749/832da159-8c07-4f89-ba17-8f0435e11a79)


It looks like the getPageTheme is undefined:
https://www.chromatic.com/test?appId=5eafd13eaebb8f00227540f4&id=655f2c449a0c27e8ba599c63

2023-11-23 12:35 UTC, IlyaSavich commented
@camilaibs thanks, yeah, I saw this one, I guess it's because backstage's extension for themes is missed for some reason for these particular cases. Could you pls suggest how this can be fixed ?

2023-11-23 12:59 UTC, camilaibs commented on packages/core-components/src/layout/Page/Page.tsx
> +              page: v4Theme.getPageTheme({ themeId }),
Do you have any recommendation @tudi2d ?

2023-11-23 13:00 UTC, IlyaSavich commented on packages/core-components/src/layout/Page/Page.tsx
> +              page: v4Theme.getPageTheme({ themeId }),
v4Theme is mui theme, not unified theme

2023-11-23 13:14 UTC, camilaibs commented on packages/core-components/src/layout/Page/Page.tsx
> +              page: v4Theme.getPageTheme({ themeId }),
oh, you're right, I was looking at the `theme` object, not the `v{4|5}theme` objects.
Let's see if @tudi2d has any recommendations 🙂

2023-11-27 15:00 UTC, tudi2d requested changes
Hej @IlyaSavich - thanks for raising this. Can I ask what specific problem you have ran into that requires a change in the `Page` component? 

I don't think it is the right approach to replace the `v4` `ThemeProvider` with the `UnifiedThemeProvider` as they fullfill different purposes. What should be done in the future is to replace it with the `v5` `ThemeProvider`, but for that we should figure out first how to generaly migrate the `core-components` to `v5`. 

Generally speaking you only want a single `UnifiedThemeProvider` at the top of your application as the React code of it looks smth. like this:

```tsx
<StyledEngineProvider injectFirst>
  <Mui5Provider theme={v5Theme}>
    <StylesProvider generateClassName={generateV4ClassName}>
        <Mui4ThemeProvider theme={v4Theme}>
          <CSSBaseline />
          {children}
        </Mui4ThemeProvider>
      </StylesProvider>
  </Mui5Provider>
</StyledEngineProvider>
```
As you can see the `UnifiedThemeProvider` does not only provide the themes, but also defines how CSS injection works & how class names are generated. Adding this somewhere in your application can lead to unintended side effects. 

My suggestion would be to close this PR and convert it into an issue to discuss the need for a `v5` `Page` `core-component` :)

2023-11-29 09:23 UTC, IlyaSavich commented
@tudi2d he reason is we're re-styling our app and doing it gradually: page by page. So now I need to wrap each migrated page in UnifiedThemeProvider while backstage already has page themes, but just hasn't adopted unified theme there

2023-12-01 11:15 UTC, tudi2d commented
Thanks! Just to clarify the goal of `UnifiedTheme` is not to have 2 seperate themes. It is to have a single theme & support both Material UI v4 as well as v5 with this single theme. The function `createUnifiedTheme` takes the `UnifiedThemeOptions`, which can contain your `pageThemes`. This way they would be supported across `v4` & `v5`. 

If you want to migrate from `v4` to `v5` page-by-page there should not be a problem wrapping the complete app in the `UnifiedThemeProvider` and then only migrating each page on it's own. Adding the `UnifiedThemeProvider` somewhere in the tree is not intended.

If there is an error you are running in (both visual or in the CLI) please share them here. Maybe I'm missing something.

2023-12-01 14:16 UTC, IlyaSavich commented
no, it's not about migrating mui to v5, it's about changing styling page by page, so I wanted to re-use these `page` themes for it, but can't because this Page component sets only v4 ThemeProvider while we in parallel migrated already some page to v5, some stay on v4 still. So for every page migrated to v5 I need to wrap page with UnifiedThemeProvider, for v4 I need to wrap in v4 ThemeProvider. I wanted to eliminate these extra theme providers

2023-12-23 14:34 UTC, closed without merging