feat: add permission to catalog create and refresh buttion
backstage/backstage pull request #21598
Opened 2023-11-28 06:08 UTC by mario-mui

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-11-30 15:28 UTC, nuritizra requested changes

2023-11-30 15:28 UTC, nuritizra commented on plugins/catalog/src/components/AboutCard/AboutCard.test.tsx
> +      result: AuthorizeResult.ALLOW,
can you please add a test for DENY

2023-12-08 08:00 UTC, freben approved these changes
Looking good! @nuritizra for final approval and merge?

2023-12-12 13:01 UTC, vinzscam approved these changes
nice!

2023-12-12 18:49 UTC, nuritizra approved these changes

2023-12-14 02:07 UTC, mario-mui commented
@nuritizra why this pr not auto merged?

2023-12-14 13:41 UTC, merged