Adding Jira Dashboard plugin to the Directory
backstage/backstage pull request #21628
Opened 2023-11-29 12:32 UTC by fridajac

Added the Jira Dashboard plugin to the Directory.

## Hey, I just made a Pull Request!

The Jira Dashboard plugin is now open sourced and available. The plugin has been added to the plugin Directory at backstage.io. 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-11-29 12:39 UTC, awanlin requested changes
Very excited to see this get into the Plugin Directory @fridajac! Left a pair of comments

2023-11-29 12:39 UTC, awanlin commented on microsite/data/plugins/jira-dashboard
> +documentation: https://github.com/AxisCommunications/backstage-plugins
You'll want to link them to the specific documentation for this plugin, I would use this: https://github.com/AxisCommunications/backstage-plugins/blob/main/plugins/jira-dashboard/README.md

2023-11-29 12:39 UTC, awanlin commented on microsite/data/plugins/jira-dashboard
> +iconUrl: https://github.com/AxisCommunications/backstage-plugins/blob/main/plugins/jira-dashboard/media/jira-logo.png
This looks to be an official Atlassian Jira logo, can you confirm we have permissions to use this?

2023-11-30 12:42 UTC, awanlin commented on microsite/data/plugins/jira-dashboard
> +iconUrl: https://github.com/AxisCommunications/backstage-plugins/blob/main/plugins/jira-dashboard/media/jira-logo.png
Looks like perhaps you can: https://www.atlassian.com/legal/trademark#:~:text=You%20may%20use%20the%20Atlassian,transposing%20Atlassian's%20logo%20with%20your

2023-11-30 12:42 UTC, awanlin commented on microsite/data/plugins/jira-dashboard
> +iconUrl: https://github.com/AxisCommunications/backstage-plugins/blob/main/plugins/jira-dashboard/media/jira-logo.png
@benjdlambert what's your thoughts?

2023-11-30 18:50 UTC, awanlin approved these changes
🚀

2023-12-01 11:17 UTC, tudi2d approved these changes
:shipit:

2023-12-01 13:01 UTC, merged