Added azure-storage plugin into the plugin marketplace
backstage/backstage pull request #21675
Opened 2023-12-01 08:19 UTC by deepan10

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-12-01 12:05 UTC, tudi2d requested changes
Thanks for adding this plugin! Needs some clarification & updated documentation :)

2023-12-01 19:32 UTC, deepan10 commented on microsite/data/plugins/azure-storage.yaml
> +documentation: https://github.com/deepan10/backstage-plugins/tree/main/plugins/azure-storage
Updated the single page documentation for both Frontend and backend plugin setup along with the screenshots.

2023-12-04 19:18 UTC, deepan10 commented
@tudi2d  Prettier is successful in my local. it is failing in the pipeline can you re-trigger its once.

![image](https://github.com/backstage/backstage/assets/5843888/f6476e36-3ec8-48ce-83c1-ca4ec2e8a74a)

2023-12-04 19:59 UTC, freben commented
@deepan10 did you run it inside the microsite folder? That check is not likely to be flaky and have a different outcome next time.

2023-12-05 07:26 UTC, deepan10 commented
Thanks @freben It worked! 😄

2023-12-07 09:17 UTC, tudi2d approved these changes

2023-12-07 09:17 UTC, tudi2d commented on microsite/data/plugins/azure-storage.yaml
> +documentation: https://github.com/deepan10/backstage-plugins/tree/main/plugins/azure-storage
Awesome - this is great!

2023-12-19 09:43 UTC, deepan10 commented
Hello @freben / @tudi2d  / @Rugvip,

Can you please re-open this PR #21675 .

2023-12-19 10:08 UTC, freben commented
Sure.

2023-12-19 10:09 UTC, freben approved these changes

2023-12-19 10:09 UTC, merged