feat: display links card for groups by default
backstage/backstage pull request #21720
Opened 2023-12-03 04:00 UTC by kurtaking

## Hey, I just made a Pull Request!

Display the `EntityLinksCard` for group entities by default. 

<img width="1570" alt="image" src="https://github.com/backstage/backstage/assets/14222009/5fa094b6-b39f-4727-a7a5-1deedfc42acf">

This is especially useful when your teamTransformer enriches the entity with links. For example, we do this to surface a team's support channel (slack id) and Jira boards (jira key).

#### Current example

<img width="1518" alt="image" src="https://github.com/backstage/backstage/assets/14222009/db92cce2-84b2-443d-bc38-c2334c1bb29f">

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-12-03 19:12 UTC, awanlin requested changes
Thanks for adding this @kurtaking, just left a pair of related comments 🚀

2023-12-03 19:12 UTC, awanlin commented on packages/create-app/templates/default-app/packages/app/src/components/catalog/EntityPage.tsx
> +        </Grid>
Can you move this down? When we add things we try to keep the current state as much as possible. I also think Ownership being on the same row as the Profile Card makes more sense as it's more likely to have content in the early stages of adopting Backstage

2023-12-03 19:12 UTC, awanlin commented on packages/app/src/components/catalog/EntityPage.tsx
> +        </Grid>
I know this is just the example but I would do the same here to keep things consistent, move it down 👍

2023-12-03 19:28 UTC, awanlin approved these changes
Awesome! Thanks again @kurtaking 🚀

2023-12-04 11:18 UTC, merged

2023-12-04 16:06 UTC, kurtaking commented
> Sure. Only slightly unsightly (heh) thing there is that the empty state is so ugly, and the vast majority of people getting started will likely be seeing that empty state. Wouldn't mind having it wrapped in
> 
> ```tsx
> <EntitySwitch>
>   <EntitySwitch.Case if={e => e?.metadata?.links?.length}>
> ```
> 
> or something like that 🤔 Or arguably, the empty state itself should probably be much milder instead, just saying `No links [learn how to change this]` where the last bit is a clickable thing that opens a popover with the info or whatever.
> 
> But let's merge for now

Hey @freben, do you think every entity with `EntityLinksCard` should have a conditional check like your example, or were you primarily focused on `group` entities?

2023-12-04 16:11 UTC, freben commented
Ultimately it's entirely up to the adopter to choose, since this is in code that they 100% control. All we do is provide some default setup that makes more or less sense to a majority of people. In those terms, I thought that maybe it's more common to NOT have links on groups than to have them, so maybe an entire if statement could perhaps make sense. The drawback of those is, now the entire layout of the page changes depending on what group you're looking at (depending on screen size etc), so that's a definite downside. Hence my thought that hey, maybe the card itself is what should be tweaked to just look great always, whether there are links or not.

But anyway, it's a bit of a separate feature request and could be done as a separate effort.