docs(tutorials): add Setup OpenTelemetry tutorial
backstage/backstage pull request #21785
Opened 2023-12-08 11:04 UTC by tcardonne

## Hey, I just made a Pull Request!

Adds a simple tutorial to setup OpenTelemetry in a Backstage project using simple Console exporters

#### :heavy_check_mark: Checklist

- [ ] ~A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))~
- [X] Added or updated documentation
- [ ] ~Tests for new functionality and regression tests for bug fixes~
- [ ] ~Screenshots attached (for UI changes)~
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-12-08 15:38 UTC, awanlin requested changes
This is an awesome first step on this subject @tcardonne, thanks for this contribution! 🚀 

Left a pair of comments.

I'd like to keep #20155 as I see this as the first step, I'd eventually like to see how to actually use the Traces and how to add more metrics. Hope that's alright with you?

Oh, also don't worry about the E2E tests failing, that's clearly not due to your changes 👍

2023-12-08 16:38 UTC, tcardonne commented on docs/tutorials/setup-opentelemetry.md
> +import './instrumentation'; // Setup the OpenTelemetry instrumentation
I tested it on our own Backstage instance which uses the new backend system :+1:

2023-12-08 16:38 UTC, awanlin commented on docs/tutorials/setup-opentelemetry.md
> +import './instrumentation'; // Setup the OpenTelemetry instrumentation
Awesome, thanks!

2023-12-08 16:42 UTC, tcardonne commented
Hey @awanlin, thanks for the review!

> I'd like to keep #20155 open as I see this as the first step, I'd eventually like to see how to actually use the Traces and how to add more metrics. Hope that's alright with you?

Yes of course, there's still work to do in my opinion.
It would be nice to also have an exhaustive listing of available metrics per package/plugin. We just started to play with metrics on our side, maybe I'll hack a follow-up PR to add this list as a reference somewhere.

2023-12-11 15:41 UTC, benjdlambert approved these changes
Nice - this is great! Been wanting something like this for a while :tada:

2023-12-11 16:32 UTC, awanlin approved these changes

2023-12-11 16:33 UTC, awanlin commented
@benjdlambert, can you merge this? It's a docs only change so the E2E tests are not related

2023-12-12 10:22 UTC, merged

2023-12-12 13:15 UTC, awanlin commented
Thanks again @tcardonne and thanks for the merge @benjdlambert 🚀