Scaffolder-backend-gerrit: Add dry run support for 'publish:gerrit'
backstage/backstage pull request #21834
Opened 2023-12-13 11:20 UTC by anicke

## Hey, I just made a Pull Request!

Added support for running the "publish:gerrit" scaffolder action in "dry run" mode. In dry run mode the input arguments will be logged.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [X] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-12-14 11:03 UTC, benjdlambert requested changes
Just a few nits really, thanks for this :tada:

2023-12-14 11:03 UTC, benjdlambert commented on .changeset/early-pumpkins-hope.md
> +'@backstage/plugin-scaffolder-backend-module-gerrit': minor
Think this should just be a patch change as the package is 0.x

2023-12-15 08:39 UTC, anicke commented on plugins/scaffolder-backend-module-gerrit/src/actions/gerrit.ts
> +        ctx.logger.info(`Dry run ctx.input: ${JSON.stringify(ctx.input)}`);
Yes!

2023-12-19 09:46 UTC, benjdlambert approved these changes
Thanks! :tada:

2023-12-19 09:46 UTC, merged