Update custom permission rule naming and files
backstage/backstage pull request #21886
Opened 2023-12-15 13:37 UTC by stanley-nicholl

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2023-12-21 18:08 UTC, awanlin requested changes
Thanks for the adjustments @stanley-nicholl, took the time to actually implement this and ran into some problems which I've left comments for.

2023-12-21 18:08 UTC, awanlin commented on docs/permissions/custom-rules.md
> +import { createCatalogPermissionRule } from '@backstage/plugin-catalog-backend/alpha';
```suggestion
import { catalogConditions, createCatalogConditionalDecision, createCatalogPermissionRule } from '@backstage/plugin-catalog-backend/alpha';
```

These are needed here related to the adds below

2023-12-21 18:08 UTC, awanlin commented on docs/permissions/custom-rules.md
>  import { createConditionFactory } from '@backstage/plugin-permission-node';
```suggestion
import { catalogConditions, createCatalogConditionalDecision, createCatalogPermissionRule } from '@backstage/plugin-catalog-backend/alpha';
```

These are needed later

2023-12-21 18:08 UTC, awanlin commented on docs/permissions/custom-rules.md
> +import { isInSystemRule } from './permissions';
Sadly we get a type error with this:

![image](https://github.com/backstage/backstage/assets/67169551/a76a3f11-ef2b-41d0-8c3e-3bd20fb91f58)

2023-12-22 15:26 UTC, awanlin approved these changes
Awesome work @stanley-nicholl 🚀

2024-01-10 15:02 UTC, benjdlambert approved these changes

2024-01-10 15:02 UTC, benjdlambert commented
Thanks @stanley-nicholl! :tada:

2024-01-10 15:02 UTC, merged