Adding support for removing file from git index
backstage/backstage pull request #22012
Opened 2023-12-23 10:57 UTC by manuelfalcon

## Hey, I just made a Pull Request!

Added support for removing file from git index. [isomorphic remove](https://isomorphic-git.org/docs/en/remove)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-01-02 15:23 UTC, tudi2d approved these changes
looks good to me - is there any risk with it, @benjdlambert?

2024-01-03 11:29 UTC, benjdlambert requested changes
Nice thanks! Just one comment about the changeset and we're good to go.

2024-01-03 11:29 UTC, benjdlambert commented on .changeset/brave-shirts-hang.md
> +'@backstage/backend-common': minor
Think this should be `patch`

2024-01-05 12:40 UTC, manuelfalcon commented on .changeset/brave-shirts-hang.md
> +'@backstage/backend-common': minor
Agree. Done :)

2024-01-09 10:39 UTC, manuelfalcon commented
@benjdlambert let me know if the change is looking good now :)

2024-01-10 14:58 UTC, benjdlambert approved these changes
Nice thanks! :Tada:

2024-01-10 14:59 UTC, merged