fix(docs): replace AsyncAPI spec urls with valid ones
backstage/backstage pull request #22067
Opened 2024-01-02 14:17 UTC by RiverPhillips

## Hey, I just made a Pull Request!

Replace AsyncAPI spec urls with valid ones. Resolves #22066 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-01-02 15:16 UTC, tudi2d requested changes
thanks for fixing this! let's use `latest` over a specific version:)

2024-01-02 15:16 UTC, tudi2d commented on plugins/api-docs/README.md
> +- [AsyncAPI](https://www.asyncapi.com/docs/reference/specification/v3.0.0)
```suggestion
- [AsyncAPI](https://www.asyncapi.com/docs/reference/specification/latest)
```

2024-01-02 15:16 UTC, tudi2d commented on docs/features/software-catalog/descriptor-format.md
> +[AsyncAPI](https://www.asyncapi.com/docs/reference/specification/v3.0.0),
```suggestion
[AsyncAPI](https://www.asyncapi.com/docs/reference/specification/latest),
```

2024-01-02 15:16 UTC, tudi2d commented on docs/features/software-catalog/descriptor-format.md
> +  [AsyncAPI](https://www.asyncapi.com/docs/reference/specification/v3.0.0) spec.
```suggestion
  [AsyncAPI](https://www.asyncapi.com/docs/reference/specification/latest) spec.
```

2024-01-02 15:27 UTC, tudi2d approved these changes
ah, sorry - small addition. I believe you can remove the changeset as this PR only updates documentation.

other than that it looks good to me.

2024-01-02 15:55 UTC, RiverPhillips commented
All done, thanks for the quick turnaround

2024-01-02 17:02 UTC, RiverPhillips commented
Is it possible to re-run CI? Seems to be an issue in the node runtime, I don't think it's related to my changes

2024-01-04 09:40 UTC, benjdlambert approved these changes

2024-01-04 09:40 UTC, benjdlambert commented
Thanks :pray:

2024-01-04 09:40 UTC, merged