Deprecate domain card
backstage/backstage pull request #22060
Opened 2023-12-30 19:36 UTC by cursedcoder

## Hey, I just made a Pull Request!

See issue #21742.

Tl;dr this removes the duplicated code.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-01-02 12:44 UTC, tudi2d approved these changes
Approving as I do agree & think this is a good change, but I remember that there was a reason that this exists. Maybe someone of the maintainers can shed a light on this.

2024-01-02 13:10 UTC, awanlin requested changes
Thanks for this @cursedcoder, just left one comment.

For history sake the `DomainCard` came first and then the generic `EntityCard` was added as part of this PR: https://github.com/backstage/backstage/pull/15381 @tudi2d

2024-01-02 13:10 UTC, awanlin commented on plugins/explore/src/components/DomainCard/DomainCard.tsx
> + * @deprecated You should use EntityCard instead, it's identical
```suggestion
 * @deprecated You should use {@link EntityCard} instead, it's identical
```

2024-01-10 10:18 UTC, benjdlambert commented on .changeset/large-stingrays-try.md
> +'@backstage/plugin-explore': minor
Think this should be a `patch` release as the package is 0.x and this isn't a breaking change.

2024-01-11 07:19 UTC, benjdlambert submitted a review, later dismissed
Nice! Thanks for this! :tada:

2024-01-11 08:07 UTC, benjdlambert commented
@cursedcoder sorry, I think that the API report is failing - I think it's because the `EntityCard` isn't exported.  Do we think that `EntityCard` is the right name for this? Or is there something better /cc @awanlin @tudi2d

2024-01-15 11:49 UTC, benjdlambert commented
Looks like you'll need to run prettier on the repo to get [CI / Verify](https://github.com/backstage/backstage/actions/runs/7489202423/job/20385309881?pr=22060) to pass.

Also thinking if it's worth deleting the `DomainCard` implementation entirely, and just exporting the `EntityCard` as `DomainCard` but deprecate that export if it is exactly the same. There's no point in having duplicates of the same code right?

2024-01-16 13:47 UTC, cursedcoder commented
@benjdlambert I don't like that idea.

About prettier - it's not prettier but some bug in the master branch. See other PRs also have it e.g. https://github.com/backstage/backstage/pull/22224

```
node_modules/@mui/base/Unstable_Popup/Popup.d.ts:13:70 - error TS2707: Generic type 'ElementType' requires between 0 and 1 type arguments.

13 declare const Popup: React.ForwardRefExoticComponent<Omit<PopupProps<React.ElementType<any, keyof React.JSX.IntrinsicElements>>, "ref"> & React.RefAttributes<Element>>;
                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@mui/material/Popper/Popper.d.ts:46:17 - error TS2707: Generic type 'ElementType' requires between 0 and 1 type arguments.

46     component?: React.ElementType<any, keyof React.JSX.IntrinsicElements> | undefined;
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@mui/material/Popper/Popper.d.ts:53:16 - error TS2707: Generic type 'ElementType' requires between 0 and 1 type arguments.

53         Root?: React.ElementType<any, keyof React.JSX.IntrinsicElements> | undefined;
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

2024-01-16 14:15 UTC, benjdlambert commented
@cursedcoder what I mean is to delete the `DomainCard` implementation and do this instead:

```ts
/** @deprecated **/
export const DomainCard = EntityCard
```

That way the export is still there, and deprecated, and we've deleted duplicate code if they're the same?

Can you elaborate why you don't like this idea?

2024-01-16 14:17 UTC, benjdlambert commented
It seems like you fixed prettier anyways so that's fine. The errors you're referring to is the E2E test, which are broken because of this: https://github.com/mui/material-ui/issues/40427

2024-01-28 14:34 UTC, closed without merging