auth-backend: migrated AWS ALB provider to new backend.
backstage/backstage pull request #22103
Opened 2024-01-04 14:19 UTC by GuptaNavdeep1983

## Hey, I just made a Pull Request!

This migrates the AWS ALB auth provider module.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-01-04 15:56 UTC, GuptaNavdeep1983 commented
> Regarding yarn.lock, a hint: you may want to squash your PR, and then `git checkout master yarn.lock` to get exactly the original lock file and then run `yarn install`. There's usually little value in merging it manually.

@freben, following your hint, squashed the PR but its not allowing me to make a commit with the error that its an empty commit even though there is a small change in "@octokit/openapi-types@npm:^17.2.0" package.

2024-01-22 20:58 UTC, GuptaNavdeep1983 commented on package.json
> +    "csstype": ">=3.0.2 <=3.1.2",
updated.

2024-01-23 22:00 UTC, Rugvip approved these changes
Thank you! 👍 🎉 

Just a few small tweaks

2024-01-23 22:01 UTC, Rugvip requested changes
derp 😅

2024-01-23 23:04 UTC, GuptaNavdeep1983 commented on plugins/auth-backend-module-aws-alb-provider/src/types.ts
> +export type PassportProfile = passport.Profile & {
Moved.

2024-01-23 23:04 UTC, GuptaNavdeep1983 commented on plugins/auth-backend-module-aws-alb-provider/package.json
> +    "passport": "^0.7.0"
Removed.

2024-01-23 23:05 UTC, GuptaNavdeep1983 commented on plugins/auth-backend-module-aws-alb-provider/src/index.d.ts
Removed.

2024-01-23 23:11 UTC, GuptaNavdeep1983 commented on yarn.lock
Performed this step multiple times but it always yield so many changes!

2024-01-24 10:08 UTC, benjdlambert commented
@GuptaNavdeep1983 I think this needs another rebase before it will start to build. Looks like there's some conflicts in the yarn.lock.

2024-01-24 13:39 UTC, GuptaNavdeep1983 commented
> @GuptaNavdeep1983 I think this needs another rebase before it will start to build. Looks like there's some conflicts in the yarn.lock.

No luck still. Same result.

2024-01-25 10:21 UTC, Rugvip approved these changes
Alright did the `yarn.lock` update. This was on top of a pretty old master which was causing the issues. Had to grab it from the merge base instead:

```bash
git checkout $(git merge-base HEAD master) -- yarn.lock
yarn install                                                                                                          
```

2024-01-25 11:56 UTC, merged