auth-backend-module-okta-provider: add "additionalScopes" to config schema
backstage/backstage pull request #22125
Opened 2024-01-06 20:11 UTC by mprokopowicz

## Hey, I just made a Pull Request!

Updated the recently refactored `auth-backend-module-okta-provider` configuration schema to include `additionalScopes` introduced in https://github.com/backstage/backstage/pull/20580

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-01-11 13:31 UTC, vinzscam requested changes

2024-01-11 13:31 UTC, vinzscam commented on .changeset/brown-items-hammer.md
> +Added missing "additionalScopes" option to configuration schema.
so that we get rid of the error :D 
```suggestion
Added missing `additionalScopes` option to configuration schema.
```

2024-01-11 17:37 UTC, mprokopowicz commented on .changeset/brown-items-hammer.md
> +Added missing "additionalScopes" option to configuration schema.
TY 🙌

2024-01-17 09:51 UTC, mprokopowicz commented
@vinzscam can you take another look?

2024-01-21 12:35 UTC, Rugvip approved these changes
Thank you! 👍

2024-01-21 12:36 UTC, merged