Fixing new adopters form height
backstage/backstage pull request #22152
Opened 2024-01-09 12:53 UTC by AmbrishRamachandiran

## Hey, I just made a Pull Request!

This PR is for https://github.com/backstage/backstage/issues/22123

lastest screen after fix

![image](https://github.com/backstage/backstage/assets/133481507/74763193-e266-474b-b310-8aaad90e9d8d)

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-01-09 17:03 UTC, npiyush97 reviewed
translateY(-40%) ?

2024-01-14 10:37 UTC, npiyush97 commented
can you change the button style appropriately failing a11y test.
https://dequeuniversity.com/rules/axe/4.8/color-contrast?application=AxeChrome

2024-01-17 08:48 UTC, AmbrishRamachandiran commented
> can you change the button style appropriately failing a11y test. https://dequeuniversity.com/rules/axe/4.8/color-contrast?application=AxeChrome

can you add more info ? why button style is involved here for fixing height issue?

2024-01-18 12:41 UTC, AmbrishRamachandiran commented
Awaiting review commenting for avoid stale

2024-01-18 14:15 UTC, benjdlambert requested changes
Don't think that this is the right fix unfortunately. I'm also struggling to reproduce this issue, but I think you will want to make sure that the adopter container flexes and has padding top and bottom in order to make the contents fit correctly.

2024-01-18 14:15 UTC, benjdlambert commented on microsite/src/pages/home/hubSpotNewAdoptersForm.module.scss
> +  transform: translateY(-40%);
I'm not sure that this a fix for this. This is meant to be half of the size of the element, I think you'll probably want to make sure that the element has a different sizing.

2024-01-18 15:05 UTC, freben commented
@npiyush97 That's a very separate issue though, feel free to file an issue for it (or even contribute a fix if possible).

2024-01-19 03:32 UTC, closed without merging