Feature: Add latest_report_status to puppetdb backend provider #22167
backstage/backstage pull request #22195
Opened 2024-01-11 11:22 UTC by negast

This pull request is made for feature #22167
I just added the latest report status to the tags. because it is usefull info about the nodes

2024-01-11 20:39 UTC, nuritizra approved these changes

2024-01-15 13:19 UTC, negast commented
I added some stuff to pase the check. I don't really know how to fix stuff to pass the remaining checks? For the DCO check should I just create the fork again or can I rebase with the latest commit?

2024-01-20 09:33 UTC, Rugvip requested changes
Nice thank you! 👍 

Just some changeset nits.

The E2E tests should not be fixed so you don't need to worry about those. We'll need DCO to be able to merge this though, see the [check details](https://github.com/backstage/backstage/pull/22195/checks?check_run_id=20493142819) for more info on how to get that resolved.

2024-01-20 09:33 UTC, Rugvip commented on .changeset/wet-lions-crash.md
> +Added latest_report_status parameter from the puppetdb node api and added it as a tag to the nodes. The status is valuable information as it displays which nodes are compliant to your configuration a
```suggestion
Added `latest_report_status` parameter from the PuppetDB node api and added it as a tag to the nodes. The status is valuable information as it displays which nodes are compliant to your configuration and which ones are failing are making changes.
```

2024-02-01 06:53 UTC, negast commented
I'm just gonna remake the fork I dont know how to fix the previous commit DCO

2024-02-01 06:54 UTC, closed without merging