Feat/unique team reviewers
backstage/backstage pull request #22228
Opened 2024-01-12 15:35 UTC by dlaird-ovo

## Hey, I just made a Pull Request!

When creating a PR from a software template you may wish to add from Groups within the catalog AND add a default team.  But you may find that the Group you select is the default team and then you have duplicates.  

```yaml
teamReviewers:
  - Team A
  - Team B
  - Team A
```

The API then fails to add any teamReviewers to the PullRequest.  This change makes the array unique before calling API so that this use-case is handled.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-01-12 18:05 UTC, awanlin approved these changes
Thanks for this @dlaird-ovo, looks good!

2024-01-15 13:34 UTC, benjdlambert requested changes
Just a small change on the changeset, but this looks good! 

`patch` is used as `minor` when the version of the package is 0.x

2024-01-15 13:34 UTC, benjdlambert commented on .changeset/fair-spies-rescue.md
> +'@backstage/plugin-scaffolder-backend-module-github': minor
```suggestion
'@backstage/plugin-scaffolder-backend-module-github': patch
```

2024-01-15 15:19 UTC, benjdlambert approved these changes
Nice! Thanks :tada:

2024-01-15 15:19 UTC, merged