some a11y fixes
backstage/backstage pull request #22237
Opened 2024-01-14 16:27 UTC by npiyush97

## Hey, I just made a Pull Request!
#19339 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-01-14 16:40 UTC, npiyush97 commented
ping @emmaindal @adamdmharvey 
fixes also include for blog and plugin ribbon.

2024-01-15 11:39 UTC, npiyush97 commented
@awanlin changed the theme monokai to chalk lighthouse seems to be happy with this.

2024-01-15 13:09 UTC, awanlin requested changes
Thanks for the corrections, I've looked this over the best I can, the SCSS changes I'm unsure about.

Just a heads up as the owner of the DevTools plugin I got tagged on this. Ideally it would be great to have broken this up into two PRs, the issue you linked doesn't mention these other items and as you provided no description it was and is confusing. 👍

2024-01-15 13:09 UTC, awanlin commented on docs/overview/what-is-backstage.md
> +<img src="https://backstage.io/img/cncf-white.svg" alt="cncf logo" width="400" />
```suggestion
<img src="https://backstage.io/img/cncf-white.svg" alt="CNCF logo" width="400" />
```

2024-01-15 13:09 UTC, awanlin commented on docs/overview/background.md
> +<img src="https://backstage.io/img/cncf-white.svg" alt='cncf logo' width="400" />
```suggestion
<img src="https://backstage.io/img/cncf-white.svg" alt="CNCF logo" width="400" />
```

2024-01-15 13:09 UTC, awanlin commented on .changeset/quick-months-clap.md
> +Refactored code to improve accessibility by moving elements outside the `ul` tag and placing them appropriately.
```suggestion
Refactored code to improve accessibility by moving elements outside the `ul` tag and placing them appropriately. Also adjusted theme to offer better contrast.
```

2024-01-15 13:32 UTC, awanlin commented on plugins/devtools/src/components/Content/ConfigContent/ConfigContent.tsx
> +          theme={theme.palette.type === 'dark' ? 'chalk' : 'rjv-default'}
Thinking about this more: does Lighthouse test the Dark theme? Or you tested the Dark theme and then changed it to `chalk` based on your testing? My assumption is that the Lighthouse test failure in https://github.com/backstage/backstage/issues/19339 is using the Light theme which would be `rjv-default`, right?

2024-01-15 13:48 UTC, npiyush97 commented on plugins/devtools/src/components/Content/ConfigContent/ConfigContent.tsx
> +          theme={theme.palette.type === 'dark' ? 'chalk' : 'rjv-default'}
as far as I know i use Lighthouse as well as Axetool they check contrast based on size and foreground color and background color in run test on dark mode only.
axetool is not happy with light theme contrast issue in light mode.
yes i changed to chalk and ### checked with both and they were happy with it 😂.

2024-01-15 13:52 UTC, npiyush97 commented on plugins/devtools/src/components/Content/InfoContent/InfoContent.tsx
> +        <Button
old 
![Screenshot from 2024-01-15 19-05-49](https://github.com/backstage/backstage/assets/43876655/056273c8-d516-4f35-9303-077dfb3c728f)
new
![Screenshot from 2024-01-15 18-59-25](https://github.com/backstage/backstage/assets/43876655/3af947dc-9bdb-41a8-adf1-ddbeb5ff5f82)
old
![Screenshot from 2024-01-15 19-05-25](https://github.com/backstage/backstage/assets/43876655/e6412dc8-2a2f-443b-ad99-f2766c611d34)
new
![Screenshot from 2024-01-15 18-58-54](https://github.com/backstage/backstage/assets/43876655/a54bc98d-4661-408a-a16d-847067b44120)

2024-01-15 13:53 UTC, awanlin commented on plugins/devtools/src/components/Content/ConfigContent/ConfigContent.tsx
> +          theme={theme.palette.type === 'dark' ? 'chalk' : 'rjv-default'}
Ah, I assumed they tested with Light theme as the default, interesting that it's Dark. Thanks for following up 👍 

I do still think going the custom theme path would be better, gives the Adopter more options as to how they want to handle this

2024-01-15 13:55 UTC, awanlin commented on plugins/devtools/src/components/Content/InfoContent/InfoContent.tsx
> +        <Button
Thanks for the images. Seeing as the button get the boarder I think it's fine the way you have it.

For the theme, the "old" seems better to me, the text stands out better, what do your think looking at those images?

2024-01-15 14:07 UTC, npiyush97 commented on plugins/devtools/src/components/Content/InfoContent/InfoContent.tsx
> +        <Button
so adding a divider and button is okay?
or add a divider and change back to an avatar?

2024-01-15 14:18 UTC, awanlin commented on plugins/devtools/src/components/Content/InfoContent/InfoContent.tsx
> +        <Button
The way you have it with a button is fine with me 👍 

I'm less sure on the theme change though

2024-01-15 14:20 UTC, awanlin commented on plugins/devtools/src/components/Content/ConfigContent/ConfigContent.tsx
> +          theme={theme.palette.type === 'dark' ? 'chalk' : 'rjv-default'}
Looking at the images you shared the old looks better than the new so I'm not sure what to do 🤔 

I'm getting pretty busy with my work day. If I have some time I'll pull the changes down and run them locally

2024-01-19 14:53 UTC, closed without merging

2024-01-19 15:18 UTC, npiyush97 commented
shifted to #22384