fix some resolutions in create-app template
backstage/backstage pull request #22247
Opened 2024-01-15 18:58 UTC by jamieklassen

## Hey, I just made a Pull Request!

I'm not confident about the decisions underlying #12252 or the answer to @Pike's question [here](https://github.com/backstage/backstage/issues/22142#issuecomment-1888991931), but I wanted to see this PR run through the CI checks and hopefully prompt some discussion about what kinds of resolutions are suitable for these templates. Each commit contains a bit of justification, but summarized here:
* I used the react 18 type definitions, which seemed to work around mui/material-ui#40427 and fix `yarn tsc:full` on a fresh app
* I added some `swagger-ui-react`-specific resolutions following the advice in [their wiki](https://github.com/swagger-api/swagger-ui/wiki/Using-older-version-of-React)

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-01-16 08:10 UTC, Rugvip requested changes
Resolutions are tricky : /

They don't apply to existing projects, and it is best to remove them when they are no longer needed, so they cause a lot of manual updates. They can also mess up existing projects that try to apply them with older dependencies or other resolutions in place. So far we've aimed to use them at a minimum and instead aim to have issues fixed upstream instead. The `@types/react` is just one of those where it actually makes sense to have a resolutions in place to select the version of React used in the repo.

2024-01-17 17:49 UTC, jamieklassen commented on packages/create-app/templates/default-app/package.json.hbs
> +    "@types/react-dom": "^18",
When you say "...along with any test utils", do you mean the template app should use test utils from React 18, or any Backstage test utils should use React 18?

Intuitively this seems like a big enough undertaking that I won't be able to fix it all in the scope of this PR; are these remaining "React 18" tasks ("update `src/index.tsx`", "update dependency ranges", etc) tracked somewhere? This [React 18 milestone](https://github.com/backstage/backstage/milestone/41) looks to be complete, but I also see comments like [this](https://github.com/backstage/backstage/issues/18433#issuecomment-1612669974) suggesting that React 18 and MUI 5 are a bit intertwined.

If it helps get PRs unblocked, I'd probably want to contribute to such an initiative!

2024-01-17 17:51 UTC, jamieklassen commented on packages/create-app/templates/default-app/package.json.hbs
> +    "swagger-ui-react/react-redux": "^8"
Yeah this was a bit of a blind effort to get around #22142. Re-reading the wiki article [here](https://github.com/swagger-api/swagger-ui/wiki/Using-older-version-of-React) it looks like this should not be required for React 18, provided we use a new enough version of `swagger-ui-react`.

2024-01-17 20:06 UTC, jamieklassen commented on packages/create-app/templates/default-app/package.json.hbs
> +    "@types/react-dom": "^18",
Hey, looks like you already handled it with #22297; nice!

2024-01-17 20:07 UTC, jamieklassen commented
Redundant to #22297

2024-01-17 20:07 UTC, closed without merging

2024-01-17 20:36 UTC, Rugvip commented on packages/create-app/templates/default-app/package.json.hbs
> +    "@types/react-dom": "^18",
Yep, those where the missing bits 😁 - in particular the migration guide