Updated readme terraform
backstage/backstage pull request #22269
Opened 2024-01-17 05:42 UTC by AmbrishRamachandiran

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-01-17 13:26 UTC, benjdlambert approved these changes

2024-01-18 12:32 UTC, Rugvip requested changes
I think the original terminology is more accurate tbh.

2024-01-18 13:09 UTC, AmbrishRamachandiran commented
> I think the original terminology is more accurate tbh.

@Rugvip modified a bit , look if its ok or else will close the request TIA .

2024-01-20 15:28 UTC, Rugvip approved these changes
Alright, it's an improvement 😅

2024-01-20 15:28 UTC, merged