score-card bumped to 0.8.0
backstage/backstage pull request #22454
Opened 2024-01-22 21:22 UTC by jvilimek

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-01-22 21:55 UTC, jvilimek commented
Is this error related? Does not seem to: <https://github.com/backstage/backstage/actions/runs/7617519966/job/20746820135?pr=22454>

Can you please re-run?

2024-01-22 21:58 UTC, freben commented
Nope that seems like a case of flakiness, retriggered

2024-01-23 09:44 UTC, tudi2d requested changes
Thanks for updating this - good to keep in sync! It would be nice to add a small changeset, which can be [similar to a `renovate` Changeset](https://github.com/backstage/backstage/pull/22452/files#diff-d6893e05da790ea8fb1807e7f2c7e62b98338fbfdc0dba11eacf5ee234fc7d02).

2024-01-25 09:19 UTC, tudi2d requested changes
almost there - just a small fix to the changeset.

2024-01-25 09:19 UTC, tudi2d commented on .changeset/dirty-mirrors-retire.md
> +'example-app': patch
`example-app`* packages can be excluded as they are really just for debugging purposes in the main repository & not versioned/packaged - could have highlighted that in the review earlier, sorry.

```suggestion
```

2024-01-25 09:20 UTC, tudi2d approved these changes

2024-01-25 09:21 UTC, tudi2d commented on .changeset/dirty-mirrors-retire.md
> +'example-app': patch
ok - just going to quickly apply the change to unblock this.

2024-01-25 13:44 UTC, freben approved these changes
Yepyep us maintainers have to do that.

Thanks for this!

2024-01-25 13:44 UTC, merged