Allow @types/react 18 as a peer dep for @backstage/theme
backstage/backstage pull request #22539
Opened 2024-01-26 14:21 UTC by fshowalter

## Hey, I just made a Pull Request!

Looks like this was missed during the React 18 upgrade. 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-01-26 15:04 UTC, tudi2d requested changes
Thanks! Interestesting - not sure if this was on purpose - Patrik will know.

You would need to attach a `patch` changelog for the package & also commit the `yarn.lock` changes - thanks!:)

2024-01-29 13:51 UTC, fshowalter commented
> Thanks! Interestesting - not sure if this was on purpose - Patrik will know.
> 
> You would need to attach a `patch` changelog for the package & also commit the `yarn.lock` changes - thanks!:)

Done.

2024-01-30 11:35 UTC, Rugvip requested changes
Looks good, thank you! 👍 

This does apply to a lot more packages though, although as regular dependencies. Do you want to update this PR to include all packages that currently declare a 16^ | 17^ range, since it's best to do them all at once?

2024-01-30 19:38 UTC, fshowalter commented
@Rugvip I can do that. 😄

2024-01-30 19:45 UTC, fshowalter commented
@Rugvip done.

2024-02-02 12:06 UTC, Rugvip approved these changes
Sweet, thank you! 👍 

E2E test failures are unrelated, gonna :shipit:

2024-02-02 12:06 UTC, Rugvip commented on .changeset/olive-boats-agree.md
> +Widen @types/react range to include 18.
```suggestion
Widen `@types/react` dependency range to include version 18.
```

2024-02-02 12:50 UTC, merged