feat(docs): Add documentation & example that AsyncApi 3 is supported
backstage/backstage pull request #22536
Opened 2024-01-26 13:22 UTC by Lazzaretti

## Hey, I just made a Pull Request!

Add documentation & example that AsyncApi 3 is supported.
The same way as it is done with OpenApi.

I also updated the example to the new version.

#22534 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-01-26 19:57 UTC, awanlin commented on packages/catalog-model/examples/apis/streetlights-api.yaml
> +    - url: https://github.com/asyncapi/spec/master/examples/streetlights-mqtt-asyncapi.ymlhttps://github.com/asyncapi/spec/blob/master/examples/streetlights-mqtt-asyncapi.yml
```suggestion
    - url: https://github.com/asyncapi/spec/blob/master/examples/streetlights-mqtt-asyncapi.yml
```

2024-01-26 20:16 UTC, awanlin requested changes
Thanks for this @Lazzaretti, always good to keep things up to date, left 1 comment

2024-01-30 14:01 UTC, awanlin requested changes
Getting there, just a small adjustment to the changeset

2024-01-30 14:01 UTC, awanlin commented on .changeset/cool-walls-applaud.md
> +'@backstage/plugin-api-docs': minor
```suggestion
'@backstage/catalog-model': patch
'@backstage/plugin-api-docs': patch
```

These should just be patch as they are just updates to documentation, you might not even need the one for `@backstage/catalog-model` but I'll let the Maintainers make the call on that 👍

2024-02-08 14:29 UTC, awanlin approved these changes
Awesome, thanks again @Lazzaretti 🚀 

Now we just need a review from the maintainers

2024-02-13 11:09 UTC, Rugvip approved these changes
Thank you! 👍 

Just a slight changeset tweak since the dev/examples aren't part of the published packages.

2024-02-13 11:09 UTC, Rugvip commented on .changeset/cool-walls-applaud.md
> +Add documentation & example that AsyncApi 3 is supported
```suggestion
---
'@backstage/plugin-api-docs': patch
---

Updated README to list AsyncApi v3 as supported
```

2024-02-13 12:24 UTC, merged

2024-02-13 12:50 UTC, awanlin commented
Thanks again for this @Lazzaretti and looks like the demo site is now up to date too! 🚀 https://demo.backstage.io/catalog/default/api/streetlights/definition

Thanks for the review and merge @Rugvip 👍