Adding plugin via revision.yaml
backstage/backstage pull request #22587
Opened 2024-01-29 14:17 UTC by riha

## Added a revision.yaml file to the list of plugins

2024-01-29 21:24 UTC, vinzscam requested changes
Nice 👏
Let's fix the DCO check making sure your commits are signed off properly and we are ready to go 🚀

2024-01-30 10:56 UTC, riha commented
@vinzscam Thanks - fixed the sign-off commit. Hope it looks ok now 😊

2024-01-30 13:29 UTC, vinzscam approved these changes

2024-01-30 15:58 UTC, freben approved these changes

2024-01-31 14:27 UTC, merged