feat: Add gitlab group visibility to group entity via annotation
backstage/backstage pull request #22889
Opened 2024-02-13 09:37 UTC by markussiebert

## Hey, I just made a Pull Request!

This PR adds an annotation to groups ingested by gitlab org provider and annotates them with their visibility level:

fixes #22887

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-02-13 11:02 UTC, tudi2d requested changes
Thanks for your contribution - heads-up that requiring the `visibility` annotation currently breaks the types. Is there a chance to make it optional? Otherwise it seems reasonable & let's get some 2nd eyes on it to ship it:)

2024-02-13 12:11 UTC, markussiebert commented on plugins/catalog-backend-module-gitlab/src/lib/types.ts
> +  visibility: string;
I extended the nested group graphql call, so I think there should be no further problem

2024-02-20 20:49 UTC, markussiebert commented
Not stale :-)

2024-02-21 12:12 UTC, benjdlambert commented
Anyone that's consuming the `GitLabGroup` type that's exported is now going to have to provide `visibility` in that now, which would be a breaking change. Not sure what the impact of that is though, maybe it's fine to just accept that this is a breaking change,  otherwise @tudi2d is correct, that we should make this optional instead, even though the producer of this would always make sure its set.

2024-02-27 13:38 UTC, benjdlambert submitted a review, later dismissed

2024-02-27 15:24 UTC, markussiebert commented
I changed the visibility to optional - you are right, it is totally fine to make it optional and set it all the time

2024-02-28 15:04 UTC, mikeyhc approved these changes

2024-03-05 11:28 UTC, tudi2d approved these changes
thanks for adjusting to the review. looks good from my side ✅

2024-03-05 12:24 UTC, benjdlambert approved these changes
Nice thanks! :tada:

2024-03-05 12:25 UTC, merged