Update docs to add profile
backstage/backstage pull request #22905
Opened 2024-02-13 22:31 UTC by tylerwray

Adding table for profile fields.

## Hey, I just made a Pull Request!

I noticed `spec.profile` docs were missing a nice table for their fields.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-02-13 22:49 UTC, awanlin commented on docs/features/software-catalog/descriptor-format.md
> +| `picture` (optional)     | String | A URL pointing to an image that's representative of the group. |
```suggestion
| `picture` (optional)     | String | A URL pointing to an image that's representative of the user. |
```

2024-02-13 22:49 UTC, awanlin commented on docs/features/software-catalog/descriptor-format.md
> +| `email` (optional)       | String | An email the group may wish to be used for contacting them.    |
```suggestion
| `email` (optional)       | String | An email the user may wish to be used for contacting them.    |
```

2024-02-13 22:50 UTC, awanlin commented on docs/features/software-catalog/descriptor-format.md
> +| `displayName` (optional) | String | A human-readable name for the group.                           |
```suggestion
| `displayName` (optional) | String | A human-readable name for the user.                           |
```

2024-02-13 22:50 UTC, awanlin requested changes
Thanks for this improvement @tylerwray, just a couple of small related comments/suggested changes.

2024-02-14 02:20 UTC, tylerwray commented
Thank you for catching those @awanlin 🙇🏻‍♂️

2024-02-14 15:11 UTC, awanlin approved these changes
Awesome! Thanks again for this @tylerwray 🚀

2024-02-14 15:11 UTC, awanlin commented
Ah, shoot, I always miss the builds. Looks like you need to run prettier in the `/docs` folder 👍

2024-02-21 12:23 UTC, merged

2024-02-24 16:12 UTC, tylerwray commented
Thanks @benjdlambert 🙇🏻