Documented the way to add a new KubernetesAuthStrategy
backstage/backstage pull request #22902
Opened 2024-02-13 20:21 UTC by andmagom

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-02-21 22:07 UTC, jamieklassen requested changes
Got through about half and suggested some ways to address the vale errors. Beyond the in-line discussions, you can get this new page to appear in the sidebar by adding an entry here:

https://github.com/backstage/backstage/blob/61c7686961b3116c0784e60bb0eab1980d742596/microsite/sidebars.json#L96-L107

2024-02-26 22:31 UTC, vinzscam reviewed
wow fantastico!

2024-02-26 22:31 UTC, vinzscam commented on docs/features/kubernetes/authenticationstrategy.md
> +id: authenticationstrategy
```suggestion
id: authentication-strategies
```

2024-02-29 06:22 UTC, vinzscam approved these changes
:shipit:

2024-03-04 15:23 UTC, andmagom commented
It looks like the pipeline error is on a file that I didn't modify

2024-03-06 14:41 UTC, vinzscam commented
> It looks like the pipeline error is on a file that I didn't modify

it's fine we'll fix it

2024-03-06 14:49 UTC, benjdlambert approved these changes

2024-03-06 14:59 UTC, merged