Add support for custom variables on creating unified theme
backstage/backstage pull request #22975
Opened 2024-02-15 12:51 UTC by IlyaSavich

## Hey, I just made a Pull Request!

Noticed current implementation cuts off all the custom variables and even some supported ones, like `shapes`. So added support for that cases

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-02-15 13:09 UTC, benjdlambert commented
Gonna bring in @tudi2d here also for some extra :eyes:

2024-02-15 14:12 UTC, IlyaSavich commented on .changeset/polite-geckos-bathe.md
> +'@backstage/theme': patch
I guess we can return export of `createBaseThemeOptions` for BC

2024-02-21 14:21 UTC, IlyaSavich commented
@awanlin, @benjdlambert, @camilaibs ping :)

2024-03-05 11:42 UTC, tudi2d requested changes
Thanks for raising this issue @IlyaSavich! First of all sorry for the delay. I think I get the idea from the PR, but want to challenge the current implementation a bit:

Currently we differentiate between "base" & "unified" theme. How I see the difference is that `BaseTheme` is really the minimal "intersection" of theme options and the `UnifiedTheme`is the "union" of theme options. Currently theme options always refers to MUI `v4` & `v5` - but keep in mind that this does not have to be the case in the future (e.g. `v6` is on the horizon). So with this it is tricky to allow `createBaseThemeOptions` to accept all `UnifiedThemeOptions`. What could be interesting is to implement an equivalent for the `UnifiedTheme`.

2024-03-05 11:42 UTC, tudi2d commented on packages/theme/src/base/createBaseThemeOptions.ts
> +export type BaseThemeOptionsInput = UnifiedThemeOptions;
e.g. this is tricky & would break the current seperation of concerns.

2024-03-05 16:23 UTC, IlyaSavich commented
@tudi2d ok, I get the idea of separation Unified theme and Base theme, so now I have only one thing to propose then, to add extra options directly in unified theme:
```ts
export function createUnifiedTheme(options: UnifiedThemeOptions): UnifiedTheme {
  const {
    components: componentOptions,
    typography,
    palette,
    pageTheme,
    defaultPageTheme,
    fontFamily,
    htmlFontSize,
    ...rest
  } = options;

  const themeOptions = createBaseThemeOptions(options);
  const components = { ...defaultComponentThemes, ...componentOptions };
  const v5Theme = createV5Theme({ ...themeOptions, components, ...rest });

  const v4Overrides = transformV5ComponentThemesToV4(v5Theme, components);
  const v4Theme = { ...createTheme(themeOptions), ...v4Overrides, ...rest };
  return new UnifiedThemeHolder(v4Theme, v5Theme);
}
```

2024-03-06 10:18 UTC, tudi2d commented
What would `...rest` be? Do you want something outside of the `v4` & `v5` `ThemeOptions`?

2024-03-06 10:19 UTC, IlyaSavich commented
MUI theme allows to create custom variables, so basically anything

2024-03-06 11:04 UTC, tudi2d commented
Ok - you are refering to this: https://mui.com/material-ui/customization/theming/#custom-variables & not custom variables on the palette, correct? That's indeed not possible at the moment. In the example above this would not work as the types of `v4` & `v5` are not adjusted to accept additional parameters. You would need to provide type safety & override the types for both themes. Feel free to propose a solution to this in a PR - would be interested in seeing how this could made be possible (e.g. through generics) :)

2024-03-07 10:27 UTC, IlyaSavich commented
I don't think we should take responsibility of theme types here, MUI provides only that approach
```ts
declare module '@mui/material/styles' {
  interface Theme {
    status: {
      danger: string;
    };
  }
  // allow configuration using `createTheme`
  interface ThemeOptions {
    status?: {
      danger?: string;
    };
  }
}
```
So it looks like it should be up to user

2024-03-15 16:47 UTC, IlyaSavich commented
@tudi2d bump :)

2024-03-15 17:03 UTC, tudi2d commented
Sorry, totally forgot to come back on this. I'm off today, but will respond on Monday!

2024-03-18 13:30 UTC, tudi2d commented
So the suggestion you make it so override the `v5` type only. This would only effect the `v5` theme & thereby only available to plugins/components consuming that. Passing `...rest` into `createTheme` of `v4` would throw an error. Additionally you are referrencing in [here](https://github.com/backstage/backstage/pull/22975#issuecomment-1979154875) that `options` is of the type `UnifiedThemeOptions`. `UnifiedThemeOptions` does not extend `ThemeOptions` so overriding `ThemeOptions` would not have any effect on `UnifiedThemeOptions`.

I don't see a perfect solution here - feel free to adjust the PR to what you feel is right & it might be easier to discuss this in real code rather than comments. Also keep in mind that MUI will release `v6` & `v7` this year. Imagine you would need to override the types for each version just to add a single variable. Maybe we find a better solution here.

2024-03-24 15:17 UTC, webark commented
was looking to add custom pallete variables, and this is the only thing that came up. @tudi2d If this PR doesn't really have a path forward, what would an acceptable path forward be for allowing custom variables.

2024-03-31 16:23 UTC, webark commented
Above question still stands. Something around this should be possible.

2024-03-31 18:04 UTC, awanlin commented
> Above question still stands. Something around this should be possible.

@webark can you create an issue for this, please?

2024-03-31 20:46 UTC, webark commented
Sure! i'll do that this week.

2024-04-08 14:14 UTC, webark commented
@ahhhndre well, it's not pretty, but this is what I ended up doing..

```typescript
function extendTheme(theme: UnifiedTheme) {
  return {
    getTheme(version: SupportedVersions) {
      const muiTheme = theme.getTheme(version) as Mui5Theme;

      if (version === 'v5') {
        if (muiTheme.unstable_sxConfig) {
          muiTheme.unstable_sxConfig.backgroundImage = {
            themeKey: 'palette',
          };
        }
      }

      return muiTheme;
    },
  };
}
```

And I wasn't sure if this was the prefered way? Of it there is an easier way to handle it.

2024-04-08 14:22 UTC, webark commented
It would be nice to be able to just pass in the theme changes I would want to do. But I dont' know if that's a plan to do that for the unified theme work, or just save that for when we are off of it.

2024-04-08 14:38 UTC, awanlin commented
> It would be nice to be able to just pass in the theme changes I would want to do. But I dont' know if that's a plan to do that for the unified theme work, or just save that for when we are off of it.

That's why it would be great to have an issue logged around this so we can track this and come to some agreement on what we should do. If you could log that it would be good as I don't have a full grasp on this other than there is a clear need.

2024-04-29 14:45 UTC, closed without merging