New backend system for Azure Site backend plugin
backstage/backstage pull request #23100
Opened 2024-02-20 13:41 UTC by deepan10

## Hey, I just made a Pull Request!

Added New backend system for the Azure Sites backend plugin

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-02-20 13:49 UTC, awanlin requested changes
Cool, I had just assumed this was already one, nice work @deepan10, left some small comments just to follow the existing patterns.

Also, I noticed that in the `README` legacy backend setup section the `catalogApi` is missing from the `createRouter` call. Can you fix that as part of this PR, please? I'm referring to this: https://github.com/backstage/backstage/blob/dde9d0ae753cf1894bd80c48c3001860319255fd/plugins/azure-sites-backend/README.md?plain=1#L56

2024-02-20 13:49 UTC, awanlin commented on plugins/azure-sites-backend/src/index.ts
> +export { azureSitesPlugin } from './plugin';
```suggestion
export { azureSitesPlugin as default } from './plugin';
```

2024-02-20 13:49 UTC, awanlin commented on plugins/azure-sites-backend/README.md
> ++ import { azureSitesPlugin } from '@backstage/plugin-azure-sites-backend;
Remove this line

2024-02-20 13:49 UTC, awanlin commented on plugins/azure-sites-backend/README.md
> ++ backend.add(azureSitesPlugin);
```suggestion
+ backend.add(import('@backstage/plugin-azure-sites-backend'));
```

2024-02-20 13:54 UTC, deepan10 commented
@awanlin super fast review 🚀 👍  
I will fix the comments that you suggested.

2024-02-20 14:35 UTC, awanlin approved these changes
Awesome, glad to see this added! Many thanks again @deepan10 🚀

2024-02-26 15:33 UTC, freben approved these changes
Nice!

2024-02-26 15:33 UTC, freben commented on plugins/azure-sites-backend/README.md
> +       const catalogApi = new CatalogClient({ discoveryApi: env.discovery })
```suggestion
     const catalogApi = new CatalogClient({ discoveryApi: env.discovery })
     return await createRouter({
```

2024-02-27 09:20 UTC, merged