Make `Kind` and `Type` entity filter form fields full width
backstage/backstage pull request #23243
Opened 2024-02-26 10:01 UTC by dawitamene

## Hey, I just made a Pull Request!

This pull request addresses the issue where the **Kind** and **Type** entity filter fields on the catalog page do not occupy the full width, causing misalignment with other form fields vertically.

**Before**

<img width="1440" alt="Screenshot 2024-02-26 at 12 57 05 pm" src="https://github.com/backstage/backstage/assets/72073614/bb2c7933-5ea0-494e-82be-3460b8b3da69">

**After**

<img width="1440" alt="Screenshot 2024-02-26 at 12 58 16 pm" src="https://github.com/backstage/backstage/assets/72073614/32285a2d-cb64-423c-be71-f9d27c351c92">

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-02-26 15:37 UTC, mikeyhc approved these changes

2024-03-05 12:15 UTC, tudi2d requested changes
Thanks for your PR! I do appreciate the before/after screenshots & details in the PR description. I do believe the best here is to keep it simple & remove the current default `maxWidth`. That should fix it for now.

2024-03-05 12:15 UTC, tudi2d commented on packages/core-components/src/components/Select/Select.tsx
>          maxWidth: 300,
It should be enough to just remove the `maxWidth` here.

2024-03-05 12:17 UTC, tudi2d commented on .changeset/strange-tools-confess.md
> +Make `Kind` and `Type` entity filter form fields full width
good changeset! this would just effect `@backstage/core-components` when you would go with removing the `maxWidth`.

2024-03-17 12:38 UTC, closed without merging