Increase HTTP request timeout used by OIDC authenticator
backstage/backstage pull request #23270
Opened 2024-02-26 17:54 UTC by gusevda

## Hey, I just made a Pull Request!

Closes https://github.com/backstage/backstage/issues/23267.

This PR increases HTTP request timeout of 3500ms used by OIDC authenticator to 10000ms.

The new value is set on a per-request bases according to the [openid-client documentation](https://github.com/panva/node-openid-client/blob/main/docs/README.md#customizing-individual-http-requests). This requires to set custom HTTP options in four places for different requests but it saves us from overriding HTTP options globally which can affect other libraries.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-02-26 19:20 UTC, Rugvip requested changes
Thank you! 👍 just a nit on the approach

2024-02-26 19:20 UTC, Rugvip commented on plugins/auth-backend-module-oidc-provider/src/authenticator.ts
> +});
Could we use the approach where the `custom.http_options` symbol is set on the client instead? It's kinda hard to know what other usages there might be of `openid-client` already or in the long run, so setting this globally is a bit risky.

2024-03-04 17:20 UTC, Rugvip reviewed
Thank you! 👍 

Just a minor potential opportunity for cleanup

2024-03-06 19:57 UTC, vinzscam approved these changes

2024-03-08 15:58 UTC, Rugvip approved these changes

2024-03-08 15:58 UTC, Rugvip commented on plugins/auth-backend-module-oidc-provider/src/authenticator.ts
> +      issuer.Client[custom.http_options] = httpOptionsProvider;
Alright! Impact of having unnecessary ones here is pretty low anyway, let's :shipit:

2024-03-11 11:07 UTC, Rugvip commented
Commits have DCO, so gonna merge even though the check is stuck

2024-03-11 11:07 UTC, merged