Create dev-friends-day.yaml
backstage/backstage pull request #23299
Opened 2024-02-27 22:11 UTC by piatkiewicz

Added plugin reference to Plugins' Directory

2024-02-27 22:22 UTC, awanlin requested changes
This seems like a fun plugin @piatkiewicz :)

I would say that perhaps it might be best to wait till this is further along based on this message in the docs: "Made for learning purposes mainly, very early stage of development and may contain weird changes in future."

Will leave final say to the Maintainers though. There are some things that need to be corrected either way.

2024-02-27 22:22 UTC, awanlin commented on microsite/data/plugins/dev-friends-day.yaml
> +npmPackageName: '@https://www.npmjs.com/package/backstage-dev-friends-days'
```suggestion
npmPackageName: 'backstage-dev-friends-days'
```

2024-02-27 22:22 UTC, awanlin commented on microsite/data/plugins/dev-friends-day.yaml
> +iconUrl: /img/dev-friends-days-logo.png
This file will need to be included in this PR

2024-02-27 22:22 UTC, awanlin commented on microsite/data/plugins/dev-friends-day.yaml
> +description: Be informed if there is the Programmer, Tester or SysAdmin day today so you will know when to celebrate that special day with your team!
```suggestion
description: Be informed if there is a Programmer, Tester or SysAdmin day today so you will know when to celebrate that special day with your team!
```

2024-03-06 10:21 UTC, tudi2d submitted a review, later dismissed
agree with andré's message above - let us know when you feel happy to move on with this.

2024-03-06 10:39 UTC, piatkiewicz commented
I did some changes like extended description and added scope to the package name according to tips mentioned in backstage.io docs. I'd like to add it to plugins list on backstage.io already if it's possible. In future I'll add more dates to display and some configuration possibilities.

2024-03-13 14:30 UTC, piatkiewicz commented
`<gently-unstaling>`

2024-03-21 09:48 UTC, awanlin approved these changes
Thanks for adding this fun plugin to the directory @piatkiewicz 🚀

2024-03-28 12:03 UTC, awanlin commented
@tudi2d @benjdlambert can you give this a quick look, please? Good to go on my end! 🚀

2024-03-28 12:41 UTC, tudi2d approved these changes
:shipit:

2024-03-28 12:42 UTC, merged