fix: `OwnershipCard` could be unscrollable when using together with `react-grid-layout`
backstage/backstage pull request #23345
Opened 2024-03-01 07:04 UTC by JounQin

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
  
  <img width="998" alt="image" src="https://github.com/backstage/backstage/assets/8336744/635e33d6-1e81-46a8-88c0-8dbc267936aa">

- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-03-01 19:59 UTC, vinzscam requested changes
Thank you 🙏
Just a tiny suggestion on the changeset

2024-03-01 19:59 UTC, vinzscam commented on .changeset/unlucky-apricots-call.md
> +fix: `OwnershipCard` could be unscrollable when using together with `react-grid-layout`
```suggestion
Fixed an issue where the `OwnershipCard` component failed to scroll properly when used alongside `react-grid-layout`.
```

2024-03-04 04:23 UTC, JounQin commented
@vinzscam Any luck to review again?

2024-03-05 12:22 UTC, benjdlambert approved these changes
Thanks

2024-03-05 12:22 UTC, merged