Support env var parameter substitution
backstage/backstage pull request #23464
Opened 2024-03-11 05:52 UTC by solimant

## Hey, I just made a Pull Request!

This PR adds the support for parameter substitution in environment variables. For example, `foo ${MISSING:-default-value}` becomes `foo default-value` if `MISSING` is an unset environment variable, or is declared but has no value. This is useful in situations where an environment variable is defined in `app-config.yaml` (e.g. in a proxy block), but a fallback value is desired when the environment variable is not set. For example:
```yaml
proxy:
  endpoints:
    '/foo':
      headers:
        authorization: 'token ${FOO_TOKEN:-my-local-dev-token}'
      target: ${FOO_PROXY_TARGET:-http://localhost:9000}
```
When `FOO_TOKEN` and/or `FOO_PROXY_TARGET` are unset, they will be substituted with `my-local-dev-token` and `http://localhost:9000`, respectively.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [X] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-03-12 00:42 UTC, solimant commented
@freben, @tudi2d, @Rugvip - does this look good to you?

2024-03-12 13:20 UTC, freben commented
One more note. This needs the docs to be updated in https://backstage.io/docs/conf/writing#environment-variable-substitution as part of the PR.

Adding @Rugvip for info too

2024-03-12 14:48 UTC, solimant commented on packages/config-loader/src/sources/transform/substitution.ts
> +          const subparts = part.split(':-', 2);
Good points 👍🏼 Done.

2024-03-12 14:49 UTC, solimant commented
@freben - hey Fredrik, thank you for the review! I've addressed your comments, and also have updated the docs. Happy to address any further comments.

2024-03-12 15:14 UTC, Rugvip requested changes
Thank you for the suggestions! 👍 

Wanna perhaps push back a little bit on this as it has quite a bit of overlap with the `APP_CONFIG_*` env vars. It's ofc doesn't quite handle the case of substitution within a value, but I'm not quite sure how much of a problem that is in practice.

The `proxy.endpoints` isn't really something that we'd want to be designing the config system around tbh. Long-term it's something that I hope we're able to redesign into something that provides more out of the box and is more secure. Do you happen to have any other other example where this might be useful?

2024-03-12 15:14 UTC, Rugvip commented on docs/conf/writing.md
> +  baseUrl: https://${HOST:-http://localhost:3000}
```suggestion
app:
  baseUrl: ${HOST:-https://localhost:3000}
```

Something like this instead right?

2024-03-12 15:56 UTC, solimant commented
> Thank you for the suggestions! 👍
> 
> Wanna perhaps push back a little bit on this as it has quite a bit of overlap with the `APP_CONFIG_*` env vars. It's ofc doesn't quite handle the case of substitution within a value, but I'm not quite sure how much of a problem that is in practice.
> 
> The `proxy.endpoints` isn't really something that we'd want to be designing the config system around tbh. Long-term it's something that I hope we're able to redesign into something that provides more out of the box and is more secure. Do you happen to have any other other example where this might be useful?

Thank you, Patrik. Yeah, in practice, we want to be able to define env vars in `app-config.yaml`, while reducing the amount of friction in asking our developers to declare them in their local dev environments, or introduce scripts to set them. Keeping the env var fallback values in `app-config.yaml` helps with that. Also, specifically for the proxy endpoints use-case, the `APP_CONFIG_*` override can't handle that use-case. This means that you'd need to do something like this:

```yaml
proxy:
  endpoints:
    '/foo':
      target: ${PROXY_FOO}
```
In such use-case, you'll have to set `PROXY_FOO` somehow for local dev environment via a script. Otherwise, it will break, especially when people forget to update that script, which creates friction.

Similar use-cases are when we're dealing with array-like configurations; for example:
```yaml
catalog:
  locations:
    - type: file
      target: ${CATALOG_INFO_YAML}
      rules:
        - allow: [Component, Resource, User, Group]
```
`APP_CONFIG_*` can't handle that use-case as well; i.e. something like `APP_CONFIG_catalog_locations_0_target` isn't supported, and even if it was, it won't work nicely with arrays because you'll need to target the array element by its index, which can become annoying and hard to maintain.

So, with parameter substitution, use-cases can be addressed with less code on the developer's end:
```yaml
proxy:
  endpoints:
    '/foo':
      target: ${PROXY_FOO:-http://dev.foo.test}

catalog:
  locations:
    - type: file
      target: ${CATALOG_INFO_YAML:-local-catalog-info.yaml}
```

2024-04-01 12:34 UTC, Rugvip approved these changes
Thank you! 👍 

Let's :shipit:, this is standard enough and close enough to our current capabilities that I'm not seeing too much risk wrt complexity.

2024-04-01 12:34 UTC, merged