[GCP Cloudbuild plugin] Add Trigger Name
backstage/backstage pull request #23508
Opened 2024-03-13 09:21 UTC by DaisukeHirabayashi

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-03-13 12:55 UTC, vinzscam requested changes
nice!

2024-03-13 13:46 UTC, DaisukeHirabayashi commented on .changeset/sour-snails-thank.md
> +Add Trigger Name
Thank you for suggesting, accepted ！

2024-03-13 14:32 UTC, DaisukeHirabayashi commented on .changeset/sour-snails-thank.md
> +Added a new column to `EntityCloudbuildContent` displaying the trigger name for each build.
```suggestion
Added a new column to `EntityCloudbuildContent` displaying the trigger name for each build.
```

2024-03-13 15:42 UTC, DaisukeHirabayashi commented
I performed the sign-off and suggestion, but the DCO CI is not running. I tried to trigger the CI by adding a merge commit, but it did not work😢

2024-03-19 02:08 UTC, DaisukeHirabayashi commented
@vinzscam 
When you have a moment, could you please review the changes again? 
I have signed all the commits.

2024-03-19 23:26 UTC, vinzscam approved these changes
let's :shipit:

2024-03-22 11:15 UTC, DaisukeHirabayashi commented
DCO...

2024-03-22 13:27 UTC, vinzscam commented
> DCO...

let me check...

2024-03-22 17:54 UTC, merged

2024-03-23 13:50 UTC, DaisukeHirabayashi commented
@vinzscam 
I really appreciate your help! I can’t thank you enough.

2024-03-26 19:53 UTC, vinzscam commented
> @vinzscam I really appreciate your help! Thank you for merging！

oh no problem, happy to help!