Hide `EntityAutocompletePicker` only if there are zero available options
backstage/backstage pull request #23724
Opened 2024-03-20 17:19 UTC by zhammer

## Hey, I just made a Pull Request!

I noticed some odd behavior in the `EntityAutocompletePicker`. If there is one available option, the picker will be hidden. This can make sense in *some* cases, but in others be quite confusing.

Let's say I have a new catalog and have just begun using tags on my entities. Right now I only use one tag, "critical", to distinguish entities in a critical path. 5 of my 20 components have `tags: ['critical']`. _The tag picker won't render on the catalog page._ As a user I expect that I can filter by my one "critical" tag.

It seems like `EntityAutocompletePicker` evolved from the `EntityNamespacePicker` (see: https://github.com/davidan01/backstage/commit/9b3ab37e1e9b75a9b68e82c92e6c7456ea1dce32), which would explain this: `metadata.namespace` is a required field; if there's only one available option, that means that there's "nothing to pick from" (every entity has the same value, `default`).

On string fields like namespace, one option would be to have `/api/catalog/entity-facets?facet=metadata.namespace` return the number of entities where the value is unset. Then the picker could distinguish between these two cases: 

```json
{
    "facets": {
        "metadata.namespace": [
            {
                "value": "default",
                "count": 2325
            },
            {
                "value": null,
                "count": 0
            },
        ]
    }
}
```

```json
{
    "facets": {
        "metadata.labels.language": [
            {
                "value": "typescript",
                "count": 8
            },
            {
                "value": null,
                "count": 4
            },
        ]
    }
}
```

This would be a *bit* trickier with tags though, as the facets endpoint returns counts of individual tags, vs. the entire tag list on an entity.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [X] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-03-20 17:20 UTC, zhammer commented
No rush on this. Curious about people's thoughts. This'd affect the namespace picker too, as that'd show `default` where it's currently hidden.

2024-03-27 14:43 UTC, tudi2d requested changes
Hey Zach - thanks for you contribution! This totaly make sense as it could look to end users like it might be deactivated for other reasons than just containing a single option.

2024-03-27 14:43 UTC, tudi2d commented
Ah & DCO needs to be fixed.

2024-04-01 13:42 UTC, Rugvip requested changes
Thank you! 👍 

As mentioned we should be able to just drop the line in the component implementation.

Needs DCO before we're able to merge

2024-04-01 21:10 UTC, zhammer commented on plugins/catalog-react/src/components/EntityAutocompletePicker/EntityAutocompletePicker.test.tsx
> +    };
what do you think of 44652dea070e

2024-04-03 13:52 UTC, tudi2d approved these changes
looks good - let's get this in:)

2024-04-03 13:52 UTC, tudi2d commented on plugins/catalog-react/src/components/EntityAutocompletePicker/EntityAutocompletePicker.test.tsx
> +  return {
looks good to me - hope this is a bit cleaner:)

2024-04-10 14:03 UTC, zhammer commented
no stale! merge! lol

2024-04-14 16:08 UTC, Rugvip approved these changes
Thank you! 🎉 

Let's :shipit:

2024-04-14 16:08 UTC, merged