Add ESLint Rule to github-issues Plugin
backstage/backstage pull request #23749
Opened 2024-03-21 06:05 UTC by AmbrishRamachandiran

Adds the no-top-level-material-ui-4-import ESLint rule to the github-issues plugin to aid with the migration to Material UI v5.

Issue: https://github.com/backstage/backstage/issues/23467

2024-03-21 10:01 UTC, awanlin requested changes
Thanks @AmbrishRamachandiran just a small nit

2024-03-21 10:01 UTC, awanlin commented on plugins/github-issues/.eslintrc.js
Please make sure the file has a newline at the end. You can setup you editor to check for this automatically so you don't have this problem going forward 👍

2024-03-21 12:24 UTC, awanlin approved these changes
✅ looks good, thanks @AmbrishRamachandiran

2024-03-22 11:33 UTC, freben approved these changes

2024-03-22 11:33 UTC, merged