Added ESLint Rule to Nomad Plugin
backstage/backstage pull request #23752
Opened 2024-03-21 06:33 UTC by grvpandey11

## Hey, I just made a Pull Request!

Added an optional ESLint rule - no-top-level-material-ui-4-imports -in good plugin which has an auto fix function to migrate the imports and used it to migrate the Material UI imports for plugins/gocd.

Issue for reference: https://github.com/backstage/backstage/issues/23467

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-03-21 09:58 UTC, awanlin requested changes
Thanks @grvpandey11 just a few nits

2024-03-21 09:58 UTC, awanlin commented on .changeset/unlucky-clouds-wash.md
> +Added an optional ESLint rule - no-top-level-material-ui-4-imports -in gocd plugin which has an auto fix function to migrate the imports and used it to migrate the Material UI imports for plugins/goc
```suggestion
Added an optional ESLint rule - no-top-level-material-ui-4-imports - which has an auto fix function to migrate the imports and used it to migrate the Material UI imports.
```

2024-03-21 09:58 UTC, awanlin commented on plugins/gocd/.eslintrc.js
Please make sure the file has a newline at the end

2024-03-21 13:30 UTC, awanlin approved these changes
✅ looks good, thanks @grvpandey11

2024-03-22 11:32 UTC, freben approved these changes

2024-03-22 11:32 UTC, merged