Added ESLint Rule to New Relic Dashboard Plugin
backstage/backstage pull request #23750
Opened 2024-03-21 06:15 UTC by grvpandey11

## Hey, I just made a Pull Request!

Added an optional ESLint rule - no-top-level-material-ui-4-imports -in new relic dashboard plugin which has an auto fix function to migrate the imports and used it to migrate the Material UI imports for plugins/newrelic-dashboard.

Issue for reference: https://github.com/backstage/backstage/issues/23467

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-03-21 09:59 UTC, awanlin requested changes
Thanks for this @grvpandey11 just a small nit

2024-03-21 09:59 UTC, awanlin commented on plugins/newrelic-dashboard/.eslintrc.js
Make sure there is a newline at the end of the file

2024-03-21 13:30 UTC, awanlin approved these changes
✅ looks good, thanks @grvpandey11

2024-03-22 11:32 UTC, freben approved these changes

2024-03-22 11:33 UTC, merged