Add ESLint Rule to firehydrant Plugin
backstage/backstage pull request #23771
Opened 2024-03-21 12:57 UTC by AmbrishRamachandiran

Adds the no-top-level-material-ui-4-import ESLint rule to the firehydrant plugin to aid with the migration to Material UI v5.

Issue: https://github.com/backstage/backstage/issues/23467

2024-03-21 15:47 UTC, awanlin requested changes
Thanks @AmbrishRamachandiran, left a comment that should help get the build green 👍

2024-03-21 15:47 UTC, awanlin commented on plugins/firehydrant/src/components/ServiceDetailsCard/ServiceDetailsCard.tsx
> +import MaterialButton from '@material-ui/core/MaterialButton';
```suggestion
import Button from '@material-ui/core/Button';
```

I'm not sure why this was initially added using `Button as MaterialButton`. Can you make the suggestion and see what else might need to be changes as well? Thanks!

2024-03-22 20:39 UTC, vinzscam approved these changes

2024-03-24 12:21 UTC, freben approved these changes

2024-03-24 12:21 UTC, merged