Add auth-backend-module-azure-easyauth-provider
backstage/backstage pull request #23909
Opened 2024-03-31 10:46 UTC by yaegashi

## Hey, I just made a Pull Request!

Add the azure-easyauth provider plugin for the new auth backend system.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-04-11 20:10 UTC, yaegashi commented
@Rugvip @freben @camilaibs Thanks for reviewing this PR.

I have refactored the legacy auth-easyauth provider and I believe it's ready to merge.

2024-04-12 19:11 UTC, awanlin requested changes
Thanks for this @yaegashi, haven't done a full review but just wanted to mention can you please make sure to update the related auth docs as well, these ones: https://github.com/backstage/backstage/blob/master/docs/auth/microsoft/azure-easyauth.md. All you should need to do is update the config example at the beginning with the proper `signIn.resolvers`

2024-04-14 07:28 UTC, yaegashi commented
@awanlin Thanks, updated auth docs as requested.

2024-04-16 09:56 UTC, freben commented
Took the liberty of rebasing this one after another pull request made it required to do so

2024-04-16 10:02 UTC, freben commented on plugins/auth-backend-module-azure-easyauth-provider/src/module.ts
> +    env.WEBSITE_AUTH_DEFAULT_PROVIDER?.toLowerCase() !== 'azureactivedirectory'
all of these should probably be `.toLocaleLowerCase('en-US')` but let's not block on that perhaps (it was just moved from elsewhere, can improve separately)

2024-04-16 10:02 UTC, freben commented on plugins/auth-backend-module-azure-easyauth-provider/src/module.ts
> +  if (process.env.WEBSITE_AUTH_TOKEN_STORE?.toLowerCase() !== 'true') {
```suggestion
  if (env.WEBSITE_AUTH_TOKEN_STORE?.toLowerCase() !== 'true') {
```

again, not blocking

2024-04-16 10:02 UTC, Rugvip approved these changes
Nice, thank you! 👍 

Let's :shipit:

2024-04-16 10:11 UTC, Rugvip commented on plugins/auth-backend-module-azure-easyauth-provider/src/module.ts
> +          providerId: 'azureEasyAuth',
Added an extra note about this in the changeset though

2024-04-16 10:33 UTC, merged

2024-04-16 13:06 UTC, awanlin commented
Thanks for including the doc updates @yaegashi 🚀