Upgrading to doc v3
backstage/backstage pull request #23988
Opened 2024-04-04 11:48 UTC by npiyush97

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-04-05 04:17 UTC, npiyush97 commented
@awanlin I don't understand why ci failing prettier:check? if there is prettier issue microsite pull should also fail. because of different versions?

2024-04-05 12:32 UTC, awanlin commented
Hi @npiyush97 CI looks fine to me, just has that CodeQL error to sort out.

2024-04-05 16:51 UTC, awanlin requested changes
Thanks for running with this @npiyush97, just left a comment related to MDX

2024-04-05 16:51 UTC, awanlin commented on microsite/package.json
We use `.mdx` files in the Blog and I think we might want to use them in the docs as well. We don't have the `"@mdx-js/react": "^3.0.0"` dependency in here at all, can we add that? And then anything else we might need from this: https://docusaurus.io/docs/migration/v3#upgrading-mdx

2024-04-09 04:02 UTC, npiyush97 commented
@Rugvip ready for review

2024-04-09 11:36 UTC, awanlin commented on microsite/package.json
@npiyush97 not sure if this got missed?

2024-04-10 08:56 UTC, npiyush97 commented
@awanlin https://www.npmjs.com/package/@mdx-js/react#when-should-i-use-this
Its a Context provides a way to pass data through the component tree without having to pass props down manually at every level.

2024-04-10 12:32 UTC, awanlin commented on microsite/package.json
But it's clearly a dependency in the Docusaurus upgrade documentation and that goes against this line here: https://docusaurus.io/docs/migration/v3#upgrading-mdx:~:text=MDX%20is%20a%20major%20dependency%20of%20Docusaurus%20responsible%20for%20compiling%20your%20.md%20and%20.mdx%20files%20to%20React%20components.

2024-04-11 06:24 UTC, npiyush97 commented
@benjdlambert for this 
https://github.com/backstage/backstage/blob/91a7e3294a4530b63717458facfb91f7ea883e44/microsite/docusaurus.config.ts#L75

2024-04-11 11:35 UTC, awanlin approved these changes
Thanks for getting this completed @npiyush97 🚀

2024-04-15 12:55 UTC, npiyush97 commented
@Rugvip if pr is alright can you merge this conflict resolve.

2024-04-16 08:46 UTC, npiyush97 commented
closing too many conflict move to #24294 24294

2024-04-16 08:46 UTC, closed without merging