feat(packages/backend-common): allow to provide authentification to DockerContainerRunner
backstage/backstage pull request #23992
Opened 2024-04-04 17:19 UTC by secustor

## Hey, I just made a Pull Request!
Introduce a new field in `DockerRunOptions` which allows to provide the credentials. 

#### :heavy_check_mark: Checklist

- [x A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-04-04 19:29 UTC, vinzscam requested changes

2024-04-12 08:34 UTC, vinzscam requested changes
nice, tweaked the changeset a bit then it's ready to go 😄

2024-04-12 08:34 UTC, vinzscam commented on .changeset/tame-pianos-hunt.md
> +Allow providing authentication which in turn allows usage of private registries
```suggestion
Added `pullOptions` to `DockerContainerRunner#runContainer` method to pass down options when pulling an image.
```

2024-04-12 10:17 UTC, vinzscam approved these changes

2024-04-13 15:26 UTC, Rugvip approved these changes
Thank you! 👍

2024-04-13 15:26 UTC, Rugvip commented on .changeset/tame-pianos-hunt.md
> +'@backstage/backend-common': minor
```suggestion
'@backstage/backend-common': patch
```

No breaking changes so bringing it down to `patch` for a `0.x` package

2024-04-13 15:46 UTC, merged