kubernetes: fixing credentials propagation for cluster suppliers
backstage/backstage pull request #24006
Opened 2024-04-05 09:18 UTC by benjdlambert

Fixes #23876

2024-04-05 13:01 UTC, Rugvip requested changes
👍, just some trouble with the `KubernetesProxy` to figure out

2024-04-05 13:01 UTC, Rugvip commented on plugins/kubernetes-backend/src/service/KubernetesProxy.ts
> +  httpAuth: HttpAuthService;
Ugh, this needs to be optional with a fallback to `createLegacyAuthAdapters` which then forces us to depend on the `DiscoveryService`. Callers of the constructor are coming from the old backend system and won't have a `HttpAuthService` instance.

2024-04-05 13:27 UTC, mclarke47 commented
Thanks for the fix, feel free to merge or I can help review next week

2024-04-05 15:05 UTC, benjdlambert commented
@mclarke47 no worries buddy! Here to help :tada:

2024-04-07 12:19 UTC, Rugvip approved these changes
👍 , :shipit:

2024-04-09 08:23 UTC, merged

2024-04-09 12:55 UTC, clementblaise commented
Thanks for providing an update so rapidly @benjdlambert working as expected

2024-04-09 13:36 UTC, swnia commented
Would it be possible to add this change to 1.25.X(3) as it fixes a now broken part? 1.26.0 is over a month away...

2024-04-09 13:46 UTC, benjdlambert commented
@swnia the next mainline release is actually 16th of April, our tooling broke a little bit when we did a bonus release. https://github.com/backstage/backstage/pull/24015/files

This will also be released part of the `-next` release train going out later today.

2024-04-09 13:51 UTC, swnia commented
That's great to hear! Thanks a lot