Mui lint more fixes
backstage/backstage pull request #24176
Opened 2024-04-10 21:13 UTC by Sarabadu

## Hey, I just made a Pull Request!

issue: #23467 

collecting current issues from closed(not merged) PR linked to #23467 

- [ ]  `import { Alert, Color } from '@material-ui/lab';` issue `Color` here is a type coming from the same `Alert` the right solution should be:
```diff
- import { Alert, Color } from '@material-ui/lab';
+ import Alert, { Color } from '@material-ui/lab/Alert';
```
event if is in theory possible to detect if `Color` is used as Type or value, I cannot imagine a way to determine that `Color` should be imported from `'@material-ui/lab/Alert'` I think we should keep a manual fix for it

- [ ]  `alpha` is resolved as `import alpha from '@material-ui/core/alpha';` but should be part of known styles along with all the exports from [colorManipulator.js](https://github.com/mui/material-ui/blob/3cde1e701aeb28bac46dc01df20b5ca53a6d0b3c/packages/mui-system/src/colorManipulator/colorManipulator.js#L4) 

- [ ] we are hardcoding `@material-ui/core/`  in some resolutions, we should use `node.source.value` instead 
- [ ] `'@material-ui/pickers'`: some components has no `default` export, the `KeyboardXPicker` should be imported from `@material-ui/pickers/XPicker` 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-04-10 21:25 UTC, Sarabadu commented
@awanlin would like your opinion on the `@material-ui/pickers` as we can create some custom logic for those, but not sure if  it worth tbh.

seems like the migration of pickers its more complex too https://mui.com/material-ui/migration/pickers-migration/

WDYT?

2024-04-27 20:30 UTC, Sarabadu commented
@awanlin do you think this is still valid? I saw most of the plugins were solved or had a PR.
But not sure if the idea is to allow this rule to be used by adopters too

2024-04-27 20:48 UTC, awanlin commented
> @awanlin do you think this is still valid? I saw most of the plugins were solved or had a PR. But not sure if the idea is to allow this rule to be used by adopters too

Sorry @Sarabadu, this has slipped past me. I'll try and take a look at this tomorrow, running out of energy today.

2024-04-28 17:17 UTC, awanlin requested changes
Thanks again for these improvements and fixes @Sarabadu, just left some minor comments on the docs 🚀 

The intention of this rule is for it to be used by the Backstage and Community Plugins repos as well as by Adopters but it's not intended to be very long lived. Once on MUI v5 you won't need this rule anymore. Give that I think some hard coded or perhaps in-perfect code is fine. 👍

2024-04-28 17:17 UTC, awanlin commented on packages/eslint-plugin/docs/rules/no-top-level-material-ui-4-imports.md
> +the fix will handle correctly 3 groups of imports:
```suggestion
The fix will handle correctly 3 groups of imports:
```

2024-04-28 17:17 UTC, awanlin commented on packages/eslint-plugin/docs/rules/no-top-level-material-ui-4-imports.md
> +this means that some types imports withouth `Props` suffix will be wrongly auto fixed to the component import, for example this fix will be wrong:
```suggestion
This means that some types of imports without `Props` suffix will be wrongly auto fixed to the component import, for example this fix will be wrong:
```

2024-04-28 17:17 UTC, awanlin commented on packages/eslint-plugin/docs/rules/no-top-level-material-ui-4-imports.md
> +the correct import should look like this:
```suggestion
The correct import should look like this:
```

2024-04-28 17:17 UTC, awanlin commented on packages/eslint-plugin/docs/rules/no-top-level-material-ui-4-imports.md
> +because `Color` is a type coming from the Alert component.
```suggestion
Because `Color` is a type coming from the Alert component.
```

2024-04-28 17:17 UTC, awanlin commented on packages/eslint-plugin/docs/rules/no-top-level-material-ui-4-imports.md
> +the fix will be wrong for this import:
```suggestion
The fix will be wrong for this import:
```

2024-04-28 17:17 UTC, awanlin commented on packages/eslint-plugin/docs/rules/no-top-level-material-ui-4-imports.md
> +the correct import should look like this:
```suggestion
The correct import should look like this:
```

2024-04-28 19:43 UTC, awanlin approved these changes
🚀

2024-05-12 19:49 UTC, freben approved these changes

2024-05-12 19:50 UTC, merged