fix(plugins/catalog-backend-module-unprocessed): correctly translate owner to string in case of nullish value
backstage/backstage pull request #24328
Opened 2024-04-17 15:19 UTC by secustor

## Hey, I just made a Pull Request!

In case no owner is provided while calling the API, then `owner` will be `undefined`. 
Currently this will be transformed to `"undefined"` as string, this leads to that the results will be filtered for entities with the owner of that value. 

This PR changes the behaviour so that `undefined` will not trigger any kind of filtering. 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-04-17 19:41 UTC, alde approved these changes

2024-04-19 21:01 UTC, vinzscam requested changes

2024-04-20 06:47 UTC, secustor commented on plugins/catalog-backend-module-unprocessed/src/UnprocessedEntitiesModule.ts
> +            owner: req.query.owner?.toString(),
Because there are no types, I have thought to make it more lenient, but enforcing strings work for me too.

2024-04-29 11:05 UTC, freben approved these changes

2024-04-30 11:00 UTC, merged