feat: generate random notifications in local development
backstage/backstage pull request #24418
Opened 2024-04-22 06:23 UTC by drodil

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-04-22 07:46 UTC, Rugvip requested changes
:+1: , just the severities bit

2024-04-22 07:46 UTC, Rugvip commented on plugins/notifications-common/api-report.md
>  export const notificationSeverities: NotificationSeverity[];
It already exists right here :p

2024-04-22 07:47 UTC, drodil commented on plugins/notifications-common/api-report.md
>  export const notificationSeverities: NotificationSeverity[];
Af fuck :D

2024-04-22 10:43 UTC, mareklibra commented
I would rather go with a predictable environment with hard-coded initial data. In general, there might be a benefit of such randomization in "unplanned testing" but I do not see that reasonable here. On the contrary, a predictable environment can simplify developer's workflows.

Just sharing my opinion. I am ok with merging this anyway as long as others agree.

2024-04-22 10:55 UTC, drodil commented
The problem with initial data is that the notifications should be created on the fly to see the actual functionality instead of having them pre-populated in the database. Having just all notifications with the title `Test notification` is not a very easy way to develop this feature in a local environment as you only get one type of notification. Generally, it's good to test with some pre-populated data but in this case, I think also random data is more than welcome to see all kinds of notifications during development.

2024-04-24 11:00 UTC, Rugvip commented
Perhaps it makes sense to move the intervall to instead be a button in the sidebar? Med a bit more wiring in the setup with a slim http API, but hopefully not too much. Thinking you could have a few different ones at that point to either send from a fixed set or random

2024-04-24 11:16 UTC, drodil commented
Yeah, that could be doable with small changes. I'll look at this at some point in near future!

2024-04-24 15:52 UTC, Rugvip approved these changes
:shipit:

2024-04-25 14:23 UTC, merged