add property ownerPickerMode to TechDocsIndexPage and DefaultApiExplorerPage
backstage/backstage pull request #24475
Opened 2024-04-23 11:42 UTC by benjidotsh

## Hey, I just made a Pull Request!

I noticed that `TechDocsIndexPage` and `DefaultApiExplorerPage` didn't contain the `ownerPickerMode` property like `CatalogIndexPage` does, so this PR adds this property to the other pages as well.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-05-10 10:32 UTC, benjidotsh commented
@Rugvip @camilaibs can someone please take a look at this? 😇

2024-05-14 09:31 UTC, vinzscam requested changes
Thank you @benjidotsh, the changes make sense 🙏

I've just suggested to expand the changesets to match the catalog ones

2024-05-14 09:31 UTC, vinzscam commented on .changeset/gentle-baboons-peel.md
> +Added property ownerPickerMode to TechDocsIndexPage
```suggestion
`TechDocsIndexPage` now accepts an optional `ownerPickerMode` for toggling the behavior of the `EntityOwnerPicker`, exposing a new mode `<TechDocsIndexPage ownerPickerMode="all" />` particularly suitable for larger catalogs. In this new mode, `EntityOwnerPicker` will display all the users and groups present in the catalog.
```

2024-05-14 09:31 UTC, vinzscam commented on .changeset/gentle-baboons-peel.md
> +'@backstage/plugin-techdocs': minor
```suggestion
'@backstage/plugin-techdocs': patch
```

2024-05-14 09:31 UTC, vinzscam commented on .changeset/tiny-pandas-return.md
> +Added property ownerPickerMode to DefaultApiExplorerPage
```suggestion
`DefaultApiExplorerPage` now accepts an optional `ownerPickerMode` for toggling the behavior of the `EntityOwnerPicker`, exposing a new mode `<DefaultApiExplorerPage ownerPickerMode="all" />` particularly suitable for larger catalogs. In this new mode, `EntityOwnerPicker` will display all the users and groups present in the catalog.
```

2024-05-14 09:53 UTC, vinzscam approved these changes

2024-05-14 17:24 UTC, squid-ney approved these changes

2024-05-16 22:11 UTC, merged

2024-05-16 22:11 UTC, squid-ney commented
Thanks for your contribution!