Documentation PR: Guide on "Start Over" & "Task List" Options available with in Backstage Software template
backstage/backstage pull request #24514
Opened 2024-04-25 17:05 UTC by subbu-raj

## Hey, I just made a Pull Request!

Adding the documentation for "Task List" & "Start Over" Options available under Software Templates. This documentation can be viewed by navigating to Docs -> Core Features -> Software Templates -> Overview in "backstage.io"

**Snap of the changes are below:**
![Screenshot 2024-04-10 185438](https://github.com/backstage/backstage/assets/142309130/64d7720c-aa7e-46e0-8d6a-72601b6cca2a)
![Screenshot 2024-04-10 185509](https://github.com/backstage/backstage/assets/142309130/90065f51-a9b1-448d-9ad5-df1803e26884)

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. 
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-04-25 19:28 UTC, awanlin requested changes
Thanks for this addition to the documentation @subbu-raj!

I've left a few comments, the text itself is very well written we just like to use backticks for code. Then I've left some comments on the images.

2024-04-25 19:28 UTC, awanlin commented on docs/features/software-templates/index.md
> +Each execution of a template is treated as a unique task, identifiable by its own unique ID. To view a list of previously executed template tasks, navigate to the `Create` page and access the `Task L
```suggestion
Each execution of a template is treated as a unique task, identifiable by its own unique ID. To view a list of previously executed template tasks, navigate to the "Create" page and access the "Task List" from the context menu (represented by the vertical ellipsis, or 'kebab menu', icon in the upper right corner).
```

2024-04-25 19:28 UTC, awanlin commented on docs/features/software-templates/index.md
> +If you wish to re-run a previously executed template, navigate to the template tasks page. Locate the desired task and select the `Start Over` option from the context menu.
```suggestion
If you wish to re-run a previously executed template, navigate to the template tasks page. Locate the desired task and select the "Start Over" option from the context menu.
```

2024-04-25 19:28 UTC, awanlin commented on docs/features/software-templates/index.md
> +In the event of a failed template execution, the `Start Over` option can be used to re-execute the template. The parameters from the original run will be pre-filled, but they can be adjusted as neede
```suggestion
In the event of a failed template execution, the "Start Over" option can be used to re-execute the template. The parameters from the original run will be pre-filled, but they can be adjusted as needed before retrying the template.
```

2024-04-25 19:28 UTC, awanlin commented on docs/assets/software-templates/template-start-over.png
Can we use screen shots from what the current state of create-app looks like? We should also use the sample template that comes with it as well. The options on the left aren't how most will see Backstages out-of-the-box so we should mimic that as best we can.

2024-04-25 19:28 UTC, awanlin commented on docs/assets/software-templates/template-task-list.png
Same here, let's use what comes out-of-the-box with create-app for the images

2024-05-03 15:20 UTC, subbu-raj commented
Hi @awanlin , Thanks for the review and feedback, Can you please review below attached images and let me know, if this is the same image that you are looking for?

**Template Task List Image:**

![template-task-list](https://github.com/backstage/backstage/assets/142309130/7a06958f-a787-436b-aa5b-9eefd9df0032)

**Template Start Over Image:**

![template-start-over](https://github.com/backstage/backstage/assets/142309130/1d751f1e-9a0f-4ce7-a8df-349c2d571467)

2024-05-08 12:14 UTC, subbu-raj commented
Hi @awanlin , 
For the screenshot images, I have took them by running the Backstage App locally using the instructions from https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#get-started

The options on the left are the ones that I see out of the box, when I launch the app locally. 
Can you let me know, if I should use a different instructions for running the app locally take screenshots from it.

2024-05-08 12:22 UTC, awanlin commented
You'll want to use a new Backstage instance created following the guide that Adopters would use to start -  https://backstage.io/docs/getting-started/ - so the results of running: `npx @backstage/create-app@latest`

2024-05-10 17:36 UTC, awanlin approved these changes
Awesome, this looks perfect IMO! 🚀

2024-05-13 09:29 UTC, merged