catalog-backend-module-github-org: fix default namespace for groups
backstage/backstage pull request #24700
Opened 2024-05-08 18:30 UTC by vinzscam

## Hey, I just made a Pull Request!

As we are suggesting adopters to use the new `catalog-backend-module-github-org` when migrating to the new backend system, this PR fixes an issue where the `catalog-backend-module-github-org` would create groups using the org as namespace instead of the `default` namespace.

Now the module uses the `default` namespace for groups, in case a single org has been configured.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-05-08 18:43 UTC, awanlin approved these changes
Thanks a ton for this improvement @vinzscam 🚀

2024-05-10 12:29 UTC, Rugvip requested changes
Nice! 👍 

Just a few nits

2024-05-10 12:29 UTC, Rugvip commented on docs/backend-system/building-backends/08-migrating.md
> +        orgs: ['org-a', 'org-b'],
Ah so it wasn't possible to configure this by org after all, that explains the code. Doesn't need to be done now but prolly makes sense to add support for `Array<string | { name: string, groupNamespace?: string, userNamespace?: string}>` in the future

2024-05-10 12:29 UTC, Rugvip commented on plugins/catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts
> +  defaultNamespace?: boolean;
Thinking that a good name for this could be `alwaysUseDefaultNamespace`?

2024-05-10 12:29 UTC, Rugvip commented on plugins/catalog-backend-module-github-org/src/GithubOrgEntityCleanerProvider.tsx
> +        console.error('Failed to clean up entities', error);
Grab the logger for this one :>

2024-05-10 17:22 UTC, awanlin approved these changes
Docs additions look good, thanks for adding that 🚀

2024-05-10 18:13 UTC, vinzscam commented on plugins/catalog-backend-module-github-org/src/GithubOrgEntityCleanerProvider.tsx
> +        console.error('Failed to clean up entities', error);
🤦

2024-05-13 12:41 UTC, Rugvip approved these changes
Bit awkward with the option, but that'll be cleaned up eventually as we move off the old system.

Good enough I'd say, and let's :shipit: 👍

2024-05-13 20:10 UTC, merged