Changing shrinking screen size entity title behavior
backstage/backstage pull request #24882
Opened 2024-05-23 14:51 UTC by SnowBlitzer

## Hey, I just made a Pull Request!

It seems some work done for screen sizing has been lose (ex [this PR](https://github.com/backstage/backstage/pull/6497)) and longer names get cut off for entities and the formatting of the header can become jumbled.

For both better readability and easier accessibility, I've made it so the name wraps to keep the user provided with full information and formatted the owner, lifecycle, and menu to always stay together and move as unit.

Before:
<img width="1506" alt="Screenshot 2024-05-23 at 10 44 15 AM" src="https://github.com/backstage/backstage/assets/7171310/6c75705e-2edf-4dd7-bccf-ff7471bb24ab">
<img width="964" alt="Screenshot 2024-05-23 at 10 44 43 AM" src="https://github.com/backstage/backstage/assets/7171310/1cf1b950-1e55-4c9c-8712-6eeef52065c9">
<img width="498" alt="Screenshot 2024-05-23 at 10 44 55 AM" src="https://github.com/backstage/backstage/assets/7171310/02d1df68-69ed-4e0e-9232-8693565d3046">

After:
<img width="1511" alt="Screenshot 2024-05-23 at 10 45 27 AM" src="https://github.com/backstage/backstage/assets/7171310/3d44685d-c797-433c-9ee7-4ae584572f02">
<img width="1002" alt="Screenshot 2024-05-23 at 10 45 21 AM" src="https://github.com/backstage/backstage/assets/7171310/32eacc46-be8d-472a-8cc2-b5237877f990">
<img width="506" alt="Screenshot 2024-05-23 at 10 45 15 AM" src="https://github.com/backstage/backstage/assets/7171310/6c0805c8-44c7-4499-a292-d94b853069c8">

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-05-23 17:21 UTC, joshjung commented
If I can make a suggestion, I would definitely prefer that the title show an ellipsis and have a tooltip show the full name when you roll over with the mouse. Part of the reason is that on long names like this it is hard to tell if there is an actual line-break in the name.

2024-05-23 20:23 UTC, SnowBlitzer commented
@joshjung an entity name shouldn't support line breaks in the name in the standard catalog config. Is this something that you're seen users override?

The hover tool tip still shows the full, none-wrap and none-formatted name if there is any confusion there. Seems like adding a step to a user's information consumptions for an edge case feels bad from their perspective

2024-05-28 15:08 UTC, joshjung commented
Yeah it's just a personal preference having done frontend for a long time, I don't enjoy when large titles wrap a ton within words as it can cause confusion and it causes the page layout to end up looking odd. Feel free to carry on.

2024-07-02 08:08 UTC, camilaibs requested changes
Hi @SnowBlitzer, thanks for opening a pull request 🙂 .
I would like to recommend adding an optional property to the component to disable title wrapping rather than changing the default style. Something like:
```jsx
<EntityLayoutTitle disableTitleWrapping .../>
```
What do you think?

2024-07-12 20:00 UTC, joshjung commented
@camilaibs I think this is a great compromise!

2024-08-21 13:43 UTC, closed without merging