beps(cli): modularization
backstage/backstage pull request #24904
Opened 2024-05-25 17:52 UTC by aramissennyeydd

## Hey, I just made a Pull Request!

👋 , one more BEP to add to my pile 😁 . Following up on conversation in #23818.

This BEP introduces a new initial design for CLI modularization based off of my work in #24488 which proved that some level of reuse of the backend abstractions is viable for a CLI. I also added the idea of profiles to allow for more purpose driven workflows, where a user may not want to install every plugin to their CLI and they instead just want to choose a few plugins for a certain task. That may lead itself to personalization, ie having a development CLI with `build`, `test`, `start`, and another CLI with `api [endpoint] [ref]`, `catalog search`, `pagerduty page [oncall]`, etc.

I also wanted to design with personalization in mind, once we have a modular CLI, users may want to start using this CLI outside of their Backstage repos. That isn't solved here, but I also think it's important to provide some foundation for that work to build off of when we get there.

cc: @drodil @Rugvip 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-05-27 12:32 UTC, benjdlambert commented
I like this, reminds me a lot of how golang cli's are setup and extended. I am however, gonna pass this review over to @Rugvip for some eyes too :eyes: :pray:

2024-07-09 14:04 UTC, Rugvip requested changes
RIP comments 😁

2024-07-18 01:22 UTC, aramissennyeydd commented on beps/0009-cli-modularization/README.md
> +1. CLI packaging, the ability to use this CLI outside of your local Backstage repo for personalized tasks.
Keeping this in scope, from our conversation at the Framework SIG this seems like an important (and difficult) problem to solve for.

2024-07-18 01:22 UTC, aramissennyeydd commented on beps/0009-cli-modularization/README.md
> +1. No breaking changes to the current functionality of the Backstage CLI.
Removed this for the time being, I agree that we will be able to find a backwards compatible implementation here.

2024-07-18 01:23 UTC, aramissennyeydd commented on beps/0009-cli-modularization/README.md
> +A new core for the Backstage CLI that enables modularization of the CLI. This should build off of the existing new backend system, leveraging its API wherever possible to reduce duplication of work a
Good call, I updated this to match the Google Cloud SDK which uses paths to identify commands. It still feels a little hacky, but it places commands into a sparse tree which is how they should be modeled.

2024-07-18 01:25 UTC, aramissennyeydd commented on beps/0009-cli-modularization/README.md
> +A new declarative installation method for plugins to be added to the CLI. Inspired by `Rushstack`'s [`rush-plugins` architecture](https://rushjs.io/pages/maintainer/using_rush_plugins/), users will d
I think this was related mostly to packaging for use outside of the main repo, if we tie this to workspace root disentangling it form the main repo gets more difficult.

2024-07-18 07:56 UTC, Rugvip reviewed
Thank you for the updates! 🎉 

I had a thought the other day that I wanted to chime in with: I think the best path towards modularizing the CLI is to start refactoring the existing CLI into a modularized format. Just a pure internal refactor but one where we can start experimenting with different APIs. By doing that I think we can learn a lot about what it might look like, and obviously it's work that would need to be done anyway in some form, but we don't yet need to ship any external APIs until we gain a bit of confidence in the design.

2024-07-18 14:21 UTC, aramissennyeydd commented
@Rugvip I had a similar thought around migration that that might fit into, removed it in the most recent draft but I agree it would be a good place to start. How should I proceed here? Do we want to merge this BEP and start working to understand what modularizing the existing CLI looks like, reduce the scope of this BEP to just modularizing the existing CLI, or start a PRFC/RFC instead?

2024-08-21 13:36 UTC, aramissennyeydd commented
I haven't had a chance to update this since we chatted about this last. A sparse tree approach seems best here, not leveraging the existing new backend infra and instead creating some custom set up instead.

2024-09-25 01:46 UTC, aramissennyeydd commented
Going to get an updated version of this out by this weekend 😁

2024-10-02 09:37 UTC, Rugvip reviewed
Just wanna chime in and say we haven't forgotten about this one. I do think we want this for many different reasons still as a fairly high priority. We don't have cycles to spare at this point though so I don't think it would be fair to merge this at this point as we wouldn't be able to follow up properly.

In the meantime I think a bit of lightweight refactoring of `@backstage/cli` could help us move closer to this, experimenting with small changes that might help us being it to a more modularized structure internally. I did a bit of work towards that recently by deprecating or removing some old things in the CLI

2024-10-19 17:49 UTC, Rugvip commented
@aramissennyeydd to be honest I've been doing some experimentation on my side the last few weeks as I'm finding this to be more and more of a high priority for the framework. I think I'm at a point where I have a good enough idea of the kind of communication patterns that we need that I can help drive this forward fairly efficiently. I do think we want to continue with experimentation such as #27213 as the way to move this forward for the time being though.

In fact I wouldn't mind experimenting a bit with the BEP process in the meantime as well as I don't find the `provisional` -> `implementable` move to work that well right now. What do you think about keeping this BEP open with comments and changes here while we iterate and tweak the design, and eventually merge it straight into the `implementable` state?

2024-10-19 18:13 UTC, aramissennyeydd commented
@Rugvip Sounds good 😁

2025-07-07 22:54 UTC, closed without merging