Fix: Autocomplete component overlapping sidebar
backstage/backstage pull request #24903
Opened 2024-05-25 10:34 UTC by JeevaRamanathan

## Hey, I just made a Pull Request!
Fixes #21781 

Screenshot:
![image](https://github.com/backstage/backstage/assets/64531160/ba3490ce-e70f-4b57-b517-2583c63ee86a)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info]
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-05-25 14:58 UTC, JeevaRamanathan commented
Hi @freben,  `plugins/proxy-backend/src/service/router.credentials.test.ts` the pipeline fails here but that backend part was untouched...your inputs on this please?

2024-06-04 08:58 UTC, jeem5110 commented
Hi @freben @Rugvip, could you please have a look into this PR and add your suggestions

2024-06-05 09:33 UTC, vinzscam requested changes

2024-06-05 09:33 UTC, vinzscam commented on .changeset/pretty-spoons-knock.md
> +'@backstage/plugin-catalog-react': minor
```suggestion
'@backstage/plugin-scaffolder-react': patch
'@backstage/plugin-catalog-react': patch
```

2024-06-05 12:46 UTC, JeevaRamanathan commented
Hi [vinzscam](https://github.com/vinzscam), i have modified the requested changes

2024-06-05 13:31 UTC, freben approved these changes
alright

2024-06-05 13:31 UTC, freben commented
@vinzscam You ok too?

2024-06-05 14:03 UTC, vinzscam approved these changes

2024-06-05 14:11 UTC, merged