Updating SupportButton title ui characteristics
backstage/backstage pull request #24943
Opened 2024-05-28 08:48 UTC by suniljose25

## Hey, I just made a Pull Request!

When the title prop is provided for `SupportButton` it is rendered as a `MenuItem` which by default has the ui characteristics of a Button(has cursor as `pointer`, has click animation).

This change passes `false` as value to the button prop of `MenuItem`, which prevents the button UI characteristics from being included.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-05-29 19:18 UTC, vinzscam requested changes
Hi @suniljose25, is it possible to attach the screenshot of the proposed changes? It makes the review easier 🙏

2024-05-31 05:00 UTC, suniljose25 commented
> Hi @suniljose25, is it possible to attach the screenshot of the proposed changes? It makes the review easier 🙏

I have added the before and after screen recordings.

This change that we see in the recording is only effective when the text is passed as the title prop.

In all of Backstage, the text is only passed to the SupportButton as children. I made a change to pass it as text in local specifically to record the effect.

2024-05-31 10:49 UTC, suniljose25 commented
Also @vinzscam any ideas why the E2E tests are failing? How do we resolve them?

2024-06-03 14:23 UTC, vinzscam approved these changes
oh amazing thank you!

2024-06-03 14:23 UTC, vinzscam commented on .changeset/twenty-masks-dance.md
> +Fixed bug in SupportButton where the title was rendered with the characteristics of a button.
```suggestion
Fixed a bug in `SupportButton` where the title was rendered with the characteristics of a button.
```

2024-06-03 15:05 UTC, merged