feat: run mkdocs via Docker Engine API
backstage/backstage pull request #24954
Opened 2024-05-28 20:40 UTC by terinjokes

Hey :wave:!

I wanted to create a draft PR to gauge interest in this approach from the Backstage devs before fixing all the tests I've broken.

My goal was to migrate from calling the Docker CI to making calls against the Engine API, such that nothing changes for existing users, but `techdocs-cli serve` starts working for users that have a different engine implementation at the docker socket path, or have `DOCKER_HOST` set in their environment.

Is this something you'd be interested in merging, or is there a preference for a different implementation?

---

The system may not have the Docker CLI installed while still having access to an implementation of the Docker Engine API. For example, if the daemon is running in a VM with shared folders, or when another container runtime is being used.

This changeset modifies techdocs-cli to interact with Docker via the Engine API instead of the Docker CLI. The local Docker Engine UDS is used by default, but another location can be specified with the `DOCKER_HOST` environment variable.

Fixes: #12028

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-06-11 21:53 UTC, terinjokes commented
I'm still waiting for feedback, _any_ feedback.

2024-06-12 12:28 UTC, awanlin commented
Hi @terinjokes, I'll try and take a look at the end of the week. The TechDocs team is pretty small and also busy right now so that might be why they haven't given it a look yet 👍

2024-06-26 13:22 UTC, awanlin requested changes
This looks good to me @terinjokes, though would for sure like others to review. Left a pair of small comments.

Will this change work for the `generate` command? I don't see any updates there.

2024-06-26 13:22 UTC, awanlin commented on .changeset/modern-cobras-cry.md
> +Connect to Docker socket instead of invoking docker's CLI.
```suggestion
Connect to Docker socket instead of invoking Docker's CLI.
```

That should make Vale happy

2024-06-26 13:22 UTC, awanlin commented on packages/techdocs-cli/src/lib/run.ts
> +          if (status.StatusCode != 0) {
Is there anything helpful in `status` that we could include in the error? Is the status code helpful?

2024-07-30 12:58 UTC, closed without merging