Display labels in AboutContent.tsx
backstage/backstage pull request #25033
Opened 2024-06-03 13:27 UTC by Mortefal

## Hey, I just made a Pull Request!
In the Entity model its described that labels is a common [part of a entity ](https://backstage.io/docs/features/software-catalog/descriptor-format/), but its not displayed, so this PR adds the labels in the view.
<img width="633" alt="Screenshot 2024-06-03 at 14 49 37" src="https://github.com/backstage/backstage/assets/22368613/99479a67-03e4-46a2-9c77-98bea392bb4c">
<img width="748" alt="Screenshot 2024-06-03 at 15 10 47" src="https://github.com/backstage/backstage/assets/22368613/974fca6d-d041-4cc1-a706-d66d8750909d">

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-06-05 09:43 UTC, vinzscam requested changes

2024-06-05 09:43 UTC, vinzscam commented on .changeset/gentle-grapes-run.md
> +'@backstage/plugin-catalog': minor
Marking this change as patch 😄

```suggestion
'@backstage/plugin-catalog': patch
```

2024-06-05 11:40 UTC, Mortefal commented on .changeset/gentle-grapes-run.md
> +'@backstage/plugin-catalog': minor
Fixed! :)

2024-06-10 09:10 UTC, Mortefal commented
Np @vinzscam, that solves our problem ;) Thanks!

2024-06-10 09:10 UTC, closed without merging