Add testid to Select component
backstage/backstage pull request #25382
Opened 2024-06-24 20:21 UTC by simonedstrom96

Currently the data-testid for the Select component is hardcoded to "select" which creates problems for testing. I modified the Select component to take in a testid parameter that sets the data-testid of the material ui Select sub-component, ensuring backwards compatibility with default value corresponding to previously hardcoded data-testid of "select".

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
-  [ ] N/A: Added or updated documentation
- [ ]  N/A: Tests for new functionality and regression tests for bug fixes
- [ ]  N/A:  Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-07-02 08:51 UTC, camilaibs requested changes
Thanks for opening this pull request, left just minor comments 🙌🏻

2024-07-02 08:51 UTC, camilaibs commented on packages/core-components/src/components/Select/Select.tsx
> +  testid?: string;
Just a minor renaming comment 🙂 :
I would recommending renaming the property to `data-testid` as it is a convention used by components libraries such as Material UI and React testing library, so it feels a intuitive pattern.

2024-07-02 08:51 UTC, camilaibs commented on packages/core-components/src/components/Select/Select.tsx
> +          data-testid={testid}
Could you please help us add a test for this new property? The test will fail if someone accidentally remove the property in the future 🙏🏻

2024-07-03 10:21 UTC, simonedstrom96 commented
Thank you for your comments @camilaibs , I have now pushed these requested changes

2024-07-03 12:02 UTC, camilaibs commented on .changeset/new-sheep-arrive.md
> +Modified the Select component to take in a testid parameter that sets the data-testid of the material ui Select sub-component, ensuring backwards compatibility with default value corresponding to pre
```suggestion
Modified the `Select` component to take in a `data-testid` parameter that sets the `data-testid` of the material ui `Select` sub-component. Ensuring backwards compatibility with default value corresponding to previously hardcoded `data-testid` of "select".
```

2024-07-03 12:03 UTC, camilaibs commented on .changeset/new-sheep-arrive.md
> +Modified the Select component to take in a testid parameter that sets the data-testid of the material ui Select sub-component, ensuring backwards compatibility with default value corresponding to pre
Fixing vale validation errors.

2024-07-03 12:04 UTC, camilaibs approved these changes
🙌🏻

2024-07-03 13:05 UTC, simonedstrom96 commented
Fixed the failing error now @camilaibs , should be ready to merge

2024-07-03 13:08 UTC, camilaibs commented on plugins/scaffolder/src/components/fields/RepoUrlPicker/RepoUrlPickerHost.test.tsx
> +    fireEvent.mouseDown(getByTestId('host-select'));
Was it changed accidentally 🤔 ?

2024-07-03 13:10 UTC, camilaibs commented on plugins/scaffolder/src/components/fields/RepoUrlPicker/RepoUrlPickerHost.test.tsx
> +    fireEvent.mouseDown(getByTestId('host-select'));
Ah ok, the RepoUrlPickerHost sets a `data-testid`, never mind.

2024-07-03 13:10 UTC, merged