fix: enable support for account and org level urls
backstage/backstage pull request #25423
Opened 2024-06-26 22:08 UTC by cjlee01

## Hey, I just made a Pull Request!

enable support for account and org level urls for harness code

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-06-27 07:30 UTC, benjdlambert commented
@OrkoHunter can I get a review here, or tag someone that can review this? :pray:

2024-06-27 11:47 UTC, OrkoHunter approved these changes
This looks good to me! cc @sandeepa-kv-jois @jenil-harness

2024-06-27 18:59 UTC, cjlee01 commented
@freben

2024-06-28 18:38 UTC, cjlee01 commented
@OrkoHunter  @camilaibs  @freben  @Rugvip any reason why checks are failing on this pr?

2024-07-02 09:04 UTC, OrkoHunter commented
everything looks good now

2024-07-04 16:22 UTC, cjlee1 commented
@camilaibs @freben @Rugvip can i get reviews on this

2024-07-12 19:48 UTC, cjlee01 commented
@camilaibs @freben @Rugvip @benjdlambert  can i get reviews on this

2024-07-18 12:54 UTC, OrkoHunter commented
@backstage/maintainers Please merge this! 🙏

2024-07-18 16:27 UTC, benjdlambert commented on .changeset/witty-bears-behave.md
> +Updated functions for getHarnessEditContentsUrl, getHarnessFileContentsUrl, getHarnessArchiveUrl, getHarnessLatestCommitUrl and parseHarnessUrl to handle account and org level urls
```suggestion
Updated functions for `getHarnessEditContentsUrl`, `getHarnessFileContentsUrl`, `getHarnessArchiveUrl`, `getHarnessLatestCommitUrl` and `parseHarnessUrl` to handle account and org level urls
```

2024-07-18 16:28 UTC, benjdlambert requested changes
Sorry, summer vacations are in full swing so this has been waiting for people to come back from them! Just a comment about the changeset, you could even remove the specificity a little bit and just simplify it overall instead.

2024-07-22 13:33 UTC, cjlee01 commented
@benjdlambert fixed comment

2024-07-22 14:13 UTC, benjdlambert approved these changes

2024-07-22 14:13 UTC, merged