Allow custom implementation of OAuthCookieManager
backstage/backstage pull request #25529
Opened 2024-07-05 12:28 UTC by allegro-dbargowski

## Hey, I just made a Pull Request!

`OAuthCookieManager` class was slightly refactored - previous implementation was renamed to `DefaultOAuthCookieManager`, interface based on public methods was created under old name and previous implementation now implements newly created interface - it was also exported so that it can be used as a base class for custom implementation.  Factory function creating `OAuthCookieManager` interface implementation was added as an optional parameter in `createOAuthProviderFactory` function (if it's not provided default implementation is initialized). It's possible to provide custom implementation of that manager after those changes (we need those changes in our project that uses backstage - currently we had to fork the whole plugin just to customize this class). 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-07-08 08:10 UTC, allegro-dbargowski commented
`PR / sync` workflow run failed, but I don't think that it's related to the changes in this PR. @camilaibs - can you, as a reviewer, schedule a rerun somehow?

2024-07-16 09:08 UTC, Rugvip requested changes
Thank you!

What kind of customizations are you looking to make and why? The `OAuthCookieManager` isn't designed in a way for it to be exposed right now, and we'd need some further refactoring to be able to a good API surface.

The existing place to customize cookies is the `cookieConfigurer` option of `createOAuthRouteHandlers`, is it possible to implement the customizations you're looking for through that?

2024-07-16 09:41 UTC, allegro-dbargowski commented
@Rugvip Thank you for your review. 

Sadly `cookieConfigurer` won't work for our case. We're encountering problem with persisting refresh token in cookies for certain users in our organization (it's caused by a fact that said token is > 4kb in size for those individuals - and it's difficult to change it at organization level as this change can have some unforeseen consequences). As a temporary fix we've copied whole `node-auth` plugin source into our new 'internal' plugin and we've modified `OAuthCookieManager` implementation to store refresh tokens bigger than 4kb in chunks - but unfortunately that's not a feasible long term approach as `node-auth` package is subject to change and maintaining our 'forked' code will be challenging. That's why we thought that the option to inject our custom implementation into `node-auth` package is the way to go. 

Do you have any suggestions that can help us solve this issue?

2024-07-25 07:46 UTC, allegro-dbargowski commented
Hey, @Rugvip,
We would appreciate any suggestions or recommendations regarding the problem described in my previous comment, as it's making the adoption of Backstage in our organization problematic.

Perhaps a contribution implementing cookie chunking (for cookies greater than 4kb in size) in the `OAuthCookieManager` class would be a more acceptable solution? If so, let me know, and I'll close this PR and create a new one implementing this approach.

2024-08-08 16:00 UTC, allegro-dbargowski commented
Pull request with cookie splitting/chunking alternative solution to a problem described above can be found [here](https://github.com/backstage/backstage/pull/25952)

2024-09-02 12:24 UTC, closed without merging