Update the SearchBar to make use of the useApp hook to retrieve the search icon specified in the createApp call
backstage/backstage pull request #25611
Opened 2024-07-13 10:10 UTC by RikClaessens

## Hey, I just made a Pull Request!

The goal of this PR is to make use of the useApp hook in the SearchBar to retrieve the specified custom search icon provided to the Backstage `createApp` function. While implementing this change I noticed that all test cases of SearchBar as well as SearchAutocomplete were failing. This was due the test cases being wrapped by renderWithEffects instead of renderInTestApp. Finally, in order to test the implementation of the new search icon, I added the `icons` option to the `renderInTestApp` function. With this change I can verify that the custom search icon gets rendered when it is specified from `createApp`.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [X] Tests for new functionality and regression tests for bug fixes
- [X] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

<img width="1840" alt="image" src="https://github.com/user-attachments/assets/4bafe338-cdfa-44d6-bfcf-728e9f1f2a46">
In the screenshot you're able to notice the Backstage icon now appearing in the search bar instead of the magnifying glass icon.

2024-07-30 12:47 UTC, RikClaessens commented
Awaiting review, so I wouldn't consider the PR to be stale. Please let me know if the PR is OK or if any changes are required. Thanks!

2024-08-07 12:01 UTC, awanlin requested changes
Thanks for this @RikClaessens, just a pair of comments that should help resolve the Vale issues.

2024-08-07 12:01 UTC, awanlin commented on .changeset/sixty-rabbits-cheat.md
> +Make use of the useApp hook to retrieve the specified search icon in the SearchBar
```suggestion
Make use of the `useApp` hook to retrieve the specified search icon in the SearchBar
```

Same here, that should make Vale happy

2024-08-07 12:42 UTC, RikClaessens commented
Thanks @awanlin for your comments, I've updated the PR with your suggestions.

2024-08-18 20:06 UTC, awanlin approved these changes
Thanks for the contribution @RikClaessens 🚀 

Just needs a review form the Maintainers now 👍

2024-08-20 09:50 UTC, freben approved these changes

2024-08-21 08:47 UTC, merged