docs: Add GlobalLogic Terraform plugin to Plugin Directory
backstage/backstage pull request #25669
Opened 2024-07-17 10:18 UTC by himeshladva

## Hey, I just made a Pull Request!

Added the GlobalLogic Terraform plugin to the Plugin Directory.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-08-07 13:19 UTC, Rugvip requested changes
Nice, thank you! 👍 

Just need to figure out the logo

2024-08-07 13:19 UTC, Rugvip commented on microsite/static/img/terraform-logo.svg
Do the terms for this logo allow us to commit it to this repo? Otherwise, could you find a separate place to link it from or alternatively provide your own logo?

2024-08-08 16:03 UTC, BillyMichael commented on microsite/static/img/terraform-logo.svg
Within the logo download link on that site, they provide both the terraform logo with text, and without it.

2024-08-15 22:08 UTC, BillyMichael commented on microsite/static/img/terraform-logo.svg
@Rugvip @awanlin - What are your thoughts on this?

2024-08-19 11:54 UTC, himeshladva commented on microsite/static/img/terraform-logo.svg
@awanlin It seems to be a bit ambiguous.

I think the part you are referring to is specifically when to use the attributed logos (whether the word "HashiCorp" is included or not). As @BillyMichael mentioned, they also provide a thumbnail logo (with no attribution or product name) for which there is no mention of when you should/should not use it.

2024-08-20 12:54 UTC, awanlin commented on microsite/static/img/terraform-logo.svg
Yeah, still seems a bit ambiguous to me. Sorry @Rugvip, but going to leave this one to you.

2024-08-22 15:29 UTC, himeshladva commented on microsite/static/img/terraform-logo.svg
@awanlin @Rugvip have renamed the plugin to `Hashicorp Terraform` now instead of just `Terraform`. Hopefully that makes things a bit clearer!

2024-08-30 13:20 UTC, merged