Fix issue 25690 update Getting started-logging in page with missing screenshot
backstage/backstage pull request #25702
Opened 2024-07-19 19:42 UTC by rghara

## Hey, I just made a Pull Request!

In https://backstage.io/docs/getting-started/logging-in there is a reference to an image of the login screen but the image was missing.
1- Added an image of the login screen to docs/assets/getting-started/login-screen.png
2- Added reference to image to docs/getting-started/logging-in.md

![expected](https://github.com/user-attachments/assets/a2b31c16-e2cc-46ef-9f6b-091178d6a1f6)

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [X] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-07-19 20:06 UTC, awanlin requested changes
Good catch @rghara, thanks for helping get this fixed. Just left a comment about the image itself. 👍

2024-07-19 20:06 UTC, awanlin commented on docs/assets/getting-started/login-screen.png
We should use a screen shot from what you see after using `npx @backstage/create-app@latest`, this isn't what most people will see at that stage.

2024-07-19 20:09 UTC, rghara commented on docs/assets/getting-started/login-screen.png
Sounds good. I just have the getting started version. I haven't deployed a standalone backstage yet. I will be working on that and will update.

Sorry, my very first contribution :)

2024-07-19 20:13 UTC, awanlin commented on docs/assets/getting-started/login-screen.png
No worries, happy to help you along 👍  

The getting started version should be from using `npx @backstage/create-app@latest`. You should only see the Guest option at this point.

2024-07-19 20:14 UTC, awanlin commented on docs/assets/getting-started/login-screen.png
Sorry, you should have GitHub and Guest, now I feel like I need to double check this myself 🤔

2024-07-19 20:31 UTC, rghara commented on docs/assets/getting-started/login-screen.png
Working on it right now using "npx @backstage/create-app@latest". Yes, you are right. We should see the Github option.

2024-07-19 22:25 UTC, rghara commented on docs/assets/getting-started/login-screen.png
@awanlin For some reason if I follow the instructions and add the Github option in packages/app/src/App.tsx it doesn't show Guest anymore. Below is what I ended up with. Does this look more like it?

![image](https://github.com/user-attachments/assets/ba1767d7-20bf-4c15-a5bc-7b98e0161cf9)

2024-07-20 13:26 UTC, awanlin approved these changes
Awesome work, again thanks for catching and fixing this @rghara 🚀

2024-07-20 13:26 UTC, awanlin commented on docs/assets/getting-started/login-screen.png
Perfect, thanks!

2024-07-20 13:27 UTC, awanlin commented
@rghara we just need a review from one of the maintainers now, they will also merge it 👍

2024-07-20 13:33 UTC, rghara commented
@awanlin I appreciate your support!

2024-07-22 14:14 UTC, benjdlambert approved these changes
Thanks!

2024-07-22 14:14 UTC, merged