Fix error handling using auth redirect flow
backstage/backstage pull request #25823
Opened 2024-07-29 19:50 UTC by stephenglass

## Hey, I just made a Pull Request!

### Background

Fixes issue #24856 which causes the user to be stuck on a blank screen if there is any error in authentication process or exception thrown in a custom a `signInResolver` or `profileTransform` when using auth redirect flow enabled by `enableExperimentalRedirectFlow` config. There is only code to handle errors when using popup flow but none when using the redirect flow hence why nothing happens and user is stuck on the blank screen.

I have a requirement to use auth redirect flow and have an email based whitelist for accessing Backstage which is implemented using a custom `profileTransform` in the auth provider. Having a user stuck on the blank page without letting them know the error reason won't be accessible.

### Solution

1. If there is an error caught in authentication and using redirect flow, redirect the user back to app origin with `?error=true` query parameter. In the redirect, we set an `httpOnly` secure cookie to hold the error message.
2. Create a new endpoint `/.backstage/error` in auth backend i.e. `/api/auth/.backstage/error` that returns any error from the `httpOnly` cookie (and clear it) if it exists.
3. Create a new api `AuthErrorApi` which implements `getSignInAuthError()` which simply is a wrapper for calling the `/.backstage/error` endpoint from the frontend. This allows Backstage users to also display auth errors in any custom sign in page they have if they are using auth redirect flow. See changeset on usage example.
4. In the sign in page component, we check if `?error=true` query param is set and if it is then use the `AuthErrorApi` to get the error so we can display to the user.

This is the cleanest possible way I could think to fix this and should be totally safe and secure. Please let me know any comments, feedback or suggestions! 

Pics on displaying the error (same as it would show using popup flow):

Single Provider
<img width="843" alt="Screenshot 2024-07-29 at 2 43 16 PM" src="https://github.com/user-attachments/assets/a6c6f1d4-11f3-4da1-9c01-bd59f2457501">

Multi Providers
<img width="836" alt="Screenshot 2024-07-29 at 2 44 10 PM" src="https://github.com/user-attachments/assets/83defb75-ee50-40d4-98c9-63bea6a804da">

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-08-06 14:44 UTC, benjdlambert commented
Hey :wave: sorry this has taken a while to get around to :pray:

What's the motivation for cookie over querystring? I appreciate its pretty ugly, but it's a pretty common pattern with authenticating proxies, and trying to understand the pros/cons to make a better decision on the best path forward.

2024-08-06 15:54 UTC, stephenglass commented
> Hey 👋 sorry this has taken a while to get around to 🙏
> 
> What's the motivation for cookie over querystring? I appreciate its pretty ugly, but it's a pretty common pattern with authenticating proxies, and trying to understand the pros/cons to make a better decision on the best path forward.

Thanks for taking a look @benjdlambert !

1. **User experience**: In addition to it just not looking nice and possibly confusing, what if a user shares `http://mybackstage.net/?error="{message:'hello'}''` link to a co-worker. Then the error message would also show to the other user when there is actually no error. What if user refreshes the page with the error message - it would keep showing when most users would expect it to be cleared after a refresh. With enough error redirects, browsers may also cache and suggest the url with error query params when the user types into the address bar (this is an annoyance with sharepoint and servicenow). I could probably go on about the UX.
2. **Security**: Storing error message in a `httpOnly` cookie is not accessible with JS which reduces risk of XSS attacks. Error message in url can be manipulated by user and could lead to vulnerability if not properly sanitized. The error messages in query param url will also be logged in browser history which is bad if there is potentially sensitive data in the error message. There are also url length limits to be mindful of if users have large error messages. 

Imo, using a `httpOnly` cookie adds complexity compared to a stateless solution like url query params but offer better UX, security, and potentially some easier scalability if the auth flow changes over time.

2024-08-12 18:10 UTC, stephenglass commented
Hey @benjdlambert any update on if this will be an acceptable approach?

2024-08-13 07:38 UTC, benjdlambert commented
@stephenglass sorry - haven't forgotten, let me bring this up internally today and get back to you!

2024-08-13 13:47 UTC, Rugvip reviewed
Yep I see the benefits on the cookie flow, but it does introduce a lot of complexity 😅. It's a bit extra unfortunate due to the redirect flow being a non-standard flow for sign-in.

The first thing that comes to mind for me is if we could solve most of the same issues with ´location.replace(...)´? That might avoid the history entry and the nuisance of auto-completing to weird URLs. So we'd return the full error message, but the frontend would immediate grab the error message, render it, and then remove it from the location using `location.replace(...'` or `react-router` equivalent.

When it comes to the sign-in error API, I'm not sure there's too much benefit to having that be a utility API tbh? Perhaps that could just be a function exported for re-use if we feel that it's needed in the end

2024-08-14 04:00 UTC, stephenglass commented
> Yep I see the benefits on the cookie flow, but it does introduce a lot of complexity 😅. It's a bit extra unfortunate due to the redirect flow being a non-standard flow for sign-in.
> 
> The first thing that comes to mind for me is if we could solve most of the same issues with ´location.replace(...)´? That might avoid the history entry and the nuisance of auto-completing to weird URLs. So we'd return the full error message, but the frontend would immediate grab the error message, render it, and then remove it from the location using `location.replace(...'` or `react-router` equivalent.
> 
> When it comes to the sign-in error API, I'm not sure there's too much benefit to having that be a utility API tbh? Perhaps that could just be a function exported for re-use if we feel that it's needed in the end


@Rugvip  I've tried messing with this today and was not successful in manipulating the history to be single entry without the error message. As for the sign-in error API, I agree with you and that's a great idea. I've pushed some changes that removes the API and instead creates a new `useSignInAuthError` hook in the `auth-react` plugin. I think it makes the contribution a little more straightforward.

2024-08-26 13:31 UTC, stephenglass commented
@Rugvip @benjdlambert any chance this can get another review? 🙏

2024-09-03 08:42 UTC, benjdlambert commented
@stephenglass sorry it's taking a while to get this through - @Rugvip is out until next week, will pick it up again when he's back next week if that's OK? :pray:

2024-09-03 14:20 UTC, stephenglass commented
@benjdlambert great, thank you for the update. Just wanting to make sure this is in the queue 👍

2024-09-16 15:30 UTC, stephenglass commented
Hey @Rugvip just checking in to see when this will be able to get picked up to review?

2024-09-30 09:02 UTC, Rugvip commented
> > Yep I see the benefits on the cookie flow, but it does introduce a lot of complexity 😅. It's a bit extra unfortunate due to the redirect flow being a non-standard flow for sign-in.
> > The first thing that comes to mind for me is if we could solve most of the same issues with ´location.replace(...)´? That might avoid the history entry and the nuisance of auto-completing to weird URLs. So we'd return the full error message, but the frontend would immediate grab the error message, render it, and then remove it from the location using `location.replace(...'` or `react-router` equivalent.
> > When it comes to the sign-in error API, I'm not sure there's too much benefit to having that be a utility API tbh? Perhaps that could just be a function exported for re-use if we feel that it's needed in the end
> 
> @Rugvip I've tried messing with this today and was not successful in manipulating the history to be single entry without the error message. As for the sign-in error API, I agree with you and that's a great idea. I've pushed some changes that removes the API and instead creates a new `useSignInAuthError` hook in the `auth-react` plugin. I think it makes the contribution a little more straightforward.

Alright, I think we'll just stick to URL parameters that show up to the user then. We want to avoid adding too much complexity to support this.

2024-10-02 03:29 UTC, stephenglass commented
> > > Yep I see the benefits on the cookie flow, but it does introduce a lot of complexity 😅. It's a bit extra unfortunate due to the redirect flow being a non-standard flow for sign-in.
> > > The first thing that comes to mind for me is if we could solve most of the same issues with ´location.replace(...)´? That might avoid the history entry and the nuisance of auto-completing to weird URLs. So we'd return the full error message, but the frontend would immediate grab the error message, render it, and then remove it from the location using `location.replace(...'` or `react-router` equivalent.
> > > When it comes to the sign-in error API, I'm not sure there's too much benefit to having that be a utility API tbh? Perhaps that could just be a function exported for re-use if we feel that it's needed in the end
> > 
> > 
> > @Rugvip I've tried messing with this today and was not successful in manipulating the history to be single entry without the error message. As for the sign-in error API, I agree with you and that's a great idea. I've pushed some changes that removes the API and instead creates a new `useSignInAuthError` hook in the `auth-react` plugin. I think it makes the contribution a little more straightforward.
> 
> Alright, I think we'll just stick to URL parameters that show up to the user then. We want to avoid adding too much complexity to support this.

@Rugvip @benjdlambert Updated the code to use URL parameters instead of cookies - its a lot more simple now. Also updated the PR description with new screenshots. Appreciate getting another check when you get a chance, thanks!

2024-10-08 09:52 UTC, Rugvip requested changes
Nice, thank you! 👍 

Just some small bits

2024-10-08 09:52 UTC, Rugvip commented on packages/core-components/src/layout/SignInPage/providers.tsx
> +          name: 'Error',
Could you make the second arg a regular error object? `new Error(decodeURIComponent(errorParam))`

2024-10-08 09:52 UTC, Rugvip commented on plugins/auth-node/src/oauth/createOAuthRouteHandlers.ts
> +          redirectUrl.searchParams.set('error', encodeURIComponent(message));
`searchParams` already encodes the value, so I think you're double encoding here and double decoding in the frontend

2024-10-14 13:38 UTC, stephenglass commented
@Rugvip Any chance this can make it to the upcoming main or next release? 🤞

2024-10-14 14:23 UTC, Rugvip approved these changes
Thank you, let's :shipit:! 🎉

2024-10-14 14:26 UTC, merged