feat: add possibility to whitelist and blacklist email addresses
backstage/backstage pull request #25854
Opened 2024-07-31 04:48 UTC by drodil

## Hey, I just made a Pull Request!

Notification email processor config to support whitelisting and blacklisting email addresses who can receive notifications in email. This is required to be able to test this in test environments with real production data and not send unnecessary notifications.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-07-31 07:03 UTC, benjdlambert requested changes
Thinking that we should move to inclusive terms for this 👍

2024-07-31 07:03 UTC, benjdlambert commented on plugins/notifications-backend-module-email/config.d.ts
> +        whitelistEmailAddresses?: string[];
```suggestion
        allowlistEmailAddresses?: string[];
```

2024-07-31 07:03 UTC, benjdlambert commented on plugins/notifications-backend-module-email/config.d.ts
> +        blacklistEmailAddresses?: string[];
```suggestion
        denylistEmailAddresses?: string[];
```

2024-07-31 07:03 UTC, benjdlambert commented on plugins/notifications-backend-module-email/src/processor/NotificationsEmailProcessor.ts
> +  private readonly blacklistEmailAddresses?: string[];
```suggestion
  private readonly allowlistEmailAddresses?: string[];
  private readonly denylistEmailAddresses?: string[];
```

2024-07-31 07:48 UTC, benjdlambert approved these changes
Nice! Good from my side :praty:

2024-07-31 07:52 UTC, drodil commented
@benjdlambert have you discussed who will merge, especially notification related, PRs? I think I have a few open but @mareklibra seems to be still on vacation. 

Also some issues with `yarn install` (I think in the master as this doesn't introduce any new or changed dependencies)?

2024-08-07 11:17 UTC, drodil commented
Can we get this merged? Ping @Rugvip / @mareklibra

2024-08-07 13:10 UTC, mareklibra approved these changes

2024-08-07 13:11 UTC, merged