Add alpha exports to notifications and signals
backstage/backstage pull request #25945
Opened 2024-08-08 12:25 UTC by mareklibra

Adding missing alpha.ts exports to notifications and signals.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-08-08 12:45 UTC, mareklibra commented
Cc @freben

2024-08-20 11:48 UTC, mareklibra commented
@davidfestal Can you please have a look at this PR?

The point is in being able to export this plugin as a dynamic one via 
`${JANUS_OR_BACKSTAGE_CLI}  package export-dynamic-plugin` without additional code changes.

Side question: Do we need to update `files` section of the `package.json`?

2024-08-20 12:34 UTC, gashcrumb commented on plugins/notifications-backend-module-email/src/alpha.ts
> +export const dynamicPluginInstaller: BackendDynamicPluginInstaller = {
No problem having this in place for now, but eventually this shouldn't be needed except for very specific circumstances.

2024-08-20 12:37 UTC, gashcrumb commented
> The point is in being able to export this plugin as a dynamic one via `${JANUS_OR_BACKSTAGE_CLI} package export-dynamic-plugin` without additional code changes.
> 
> Side question: Do we need to update `files` section of the `package.json`?

This should not be necessary.  If I recall this was previously a requirement because an npm registry was being used to distribute dynamic plugins at runtime, however there's better ways to do this runtime distribution.

2024-08-21 09:38 UTC, Rugvip requested changes
Nope sorry, this is not something we're adding to packages. We've settled on the pattern of using the `default` export as they way to export features from packages.

2024-09-27 10:44 UTC, closed without merging