Create kubelog.yaml, Add Kubelog plugin
backstage/backstage pull request #26198
Opened 2024-08-25 00:00 UTC by jfvilas

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-08-25 19:50 UTC, awanlin requested changes
Thanks for the contribution, this looks like a helpful plugin, I left one comment @jfvilas 

Generally speaking please don't close the PR but make the requested changes and update the PR as needed. This makes it easy for you and reviewers to keep track of things 👍

2024-08-25 19:50 UTC, awanlin commented on microsite/data/plugins/kubelog.yaml
> +npmPackageName: '@jfvilas/plugin-kubelog'
You package still points to the other account, here:

https://github.com/jfvilas/kubelog/blob/f462bd0f54c1cb07320916ca0c5dd4c4e9adab17/package.json#L24

And also here:

https://github.com/jfvilas/kubelog/blob/f462bd0f54c1cb07320916ca0c5dd4c4e9adab17/package.json#L32

Can you correct those please?

2024-08-26 06:39 UTC, jfvilas commented
Hi @awanlin , I've closed the PR in order to have this new PR associated to my new username, sorry for the inconvenience. I've already changed the package.json references to new repository, pushed everything a publish a new version of the NPM packages. Thanks.

2024-08-26 12:07 UTC, awanlin approved these changes
Awesome! 🚀

2024-08-26 12:08 UTC, awanlin commented
@freben @camilaibs this is good to go, just need your review 👍

2024-08-26 14:07 UTC, freben approved these changes

2024-08-26 14:07 UTC, merged