[NBS Docs]: Migrate auth0 provider to new backend system
backstage/backstage pull request #26421
Opened 2024-09-03 06:51 UTC by camilaibs

## Hey, I just made a Pull Request!

Closes: https://github.com/backstage/backstage/issues/26408

Migrate the `Auth0` provider to a new auth module and update its documentation to use the new Backend System.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-09-03 11:59 UTC, awanlin requested changes
Thanks @camilaibs, just a few comments 👍

2024-09-09 08:09 UTC, Rugvip reviewed
Nice! 🎉 👍 

Just a few minor bits

2024-09-09 08:09 UTC, Rugvip commented on .changeset/fair-seals-burn.md
> +'@backstage/plugin-auth-node': minor
```suggestion
'@backstage/plugin-auth-node': patch
```

Not a breaking change and 0.x

2024-09-09 08:30 UTC, camilaibs commented on plugins/auth-backend-module-auth0-provider/api-report.md
> +}
Oh, you're right! Just removed it.

2024-09-09 09:29 UTC, camilaibs commented on plugins/auth-backend-module-auth0-provider/src/strategy.ts
> +import { StateStore } from 'passport-oauth2';
Fixed 🙏🏻

2024-09-09 11:01 UTC, Rugvip approved these changes
🎉

2024-09-09 11:26 UTC, camilaibs commented on plugins/auth-backend-module-auth0-provider/package.json
> +    "passport-oauth2": "^1.6.1"
No because of this:
![image](https://github.com/user-attachments/assets/c4643da5-9b67-4abc-b1a6-b4da35ea3492)

2024-09-09 14:57 UTC, awanlin approved these changes

2024-09-09 14:58 UTC, awanlin commented on plugins/auth-backend/src/providers/auth0/provider.ts
Looks like this is good then, thanks 👍

2024-09-09 14:58 UTC, merged