feat: add overrideable FavoriteToggle to core-components
backstage/backstage pull request #26484
Opened 2024-09-05 08:40 UTC by callebstrom

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-09-05 08:51 UTC, callebstrom commented on plugins/catalog/src/components/CatalogTable/CatalogTable.tsx
> -            <Typography style={visuallyHidden}>{title}</Typography>
Typography not required as tooltip achieves the same for SR:s

2024-09-05 12:22 UTC, benjdlambert requested changes
Think that this is looking pretty good, but we just need to include a changeset for `core-components` :tada:

2024-09-05 13:29 UTC, callebstrom commented
@benjdlambert strange, `yarn changset` did not include `core-components` for some reason. Added it now :+1:

2024-09-05 14:48 UTC, benjdlambert approved these changes
Nice! Just cleaned a few things up and skipped the prop type export for now to just inline it, less API surface.

2024-09-05 15:04 UTC, merged

2024-09-08 11:31 UTC, callebstrom commented
@benjdlambert thank you!