Add 'includeUsersWithoutSeat' to enable ingestion of Gitlab users without seat
backstage/backstage pull request #26677
Opened 2024-09-13 20:03 UTC by hghtwr

## Hey, I just made a Pull Request!

Referencing #26438 this PR implements a custom configuration field called `includeUsersWithoutSeat` that allows ingesting users without paid seats in Gitlab. 

This enables
- users of Gitlab Free and
- Guest Users in Gitlab Ultimate to be processed and imported into the catalog as well.

It comes with the drawback that some technical users cannot be avoided to be imported as well, especially service accounts as there usernames can be freely chosen and there's no field to identify them. Group & Project access tokens (also users in Gitlab) are automatically filtered by a regular expression.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-09-16 07:18 UTC, jhaals requested changes
Great work with this PR! 👏 

Small tweaks but otherwise looking great!

2024-09-16 07:18 UTC, jhaals commented on docs/integrations/gitlab/org.md
> +        includeUsersWithoutSeat: true # Optional: Include users without paid seat, only valid for SaaS
```suggestion
        includeUsersWithoutSeat: false # Optional: Include users without paid seat, only valid for SaaS
```
Perhaps we should show `false` in this example as it's likely what most people want but copy paste of config is a good way of getting started for many :)

2024-09-16 07:18 UTC, jhaals commented on plugins/catalog-backend-module-gitlab/src/lib/client.ts
> +        const regex = /^(?:project|group)_(\w+)_bot_(\w+)$/;
Perhaps we can move this const further up to not have to redefine it every time.

2024-09-17 08:45 UTC, jhaals commented on .changeset/spotty-jokes-boil.md
> +Added includeUsersWithoutSeat allows to import users without paid seat, e.g. for Gitlab Free on SaaS. Defaults to false
```suggestion
Added a `includeUsersWithoutSeat` config option that allow import users without paid seat, e.g. for Gitlab Free on SaaS. Defaults to false
```

2024-09-17 09:00 UTC, jhaals approved these changes
Thanks for this fix @hghtwr!

2024-09-17 11:22 UTC, benjdlambert approved these changes
🚢

2024-09-17 11:22 UTC, merged