fix(catalog-backend-module-gerrit): add schedule in config.d.ts
backstage/backstage pull request #26778
Opened 2024-09-18 20:46 UTC by tcardonne

## Hey, I just made a Pull Request!

Add missing `schedule` key in `config.d.ts` for `catalog-backend-module-gerrit` plugin.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] ~Added or updated documentation~
- [X] ~Tests for new functionality and regression tests for bug fixes~
- [X] ~Screenshots attached (for UI changes)~
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-09-24 08:38 UTC, deejay1 approved these changes

2024-09-27 14:05 UTC, camilaibs approved these changes
Thank you 🙏🏻

2024-09-27 14:16 UTC, vinzscam requested changes
good catch! Added just a small suggestion

2024-09-27 14:55 UTC, tcardonne commented
Done! 👌

2024-09-30 10:02 UTC, benjdlambert approved these changes

2024-09-30 10:02 UTC, merged