Fixes #26503 Add skipUserProfile flag to Microsoft authenticator
backstage/backstage pull request #26885
Opened 2024-09-27 20:17 UTC by jslott2sigma

## Hey, I just made a Pull Request!

Add skipUserProfile to Microsoft authenticator as login performance optimization

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-09-27 20:18 UTC, jslott2sigma commented on plugins/auth-backend-module-microsoft-provider/src/strategy.ts
> +  private shouldSkipUserProfile: boolean = false;
Unfortunately I cannot name this variable `skipUserProfile` because of a method of the same name. This name was the best I could come up with.

2024-10-01 09:09 UTC, vinzscam requested changes

2024-10-01 09:09 UTC, vinzscam commented on plugins/auth-backend-module-microsoft-provider/src/strategy.ts
> +  private shouldSkipUserProfile: boolean = false;
```suggestion
  private shouldSkipUserProfile = false;
```

2024-10-01 09:09 UTC, vinzscam commented on plugins/auth-backend-module-microsoft-provider/src/strategy.ts
> +    if (this.shouldSkipUserProfile || this.skipUserProfile(accessToken)) {
perhaps move this check inside `skipUserProfile()`

2024-10-01 13:35 UTC, jslott2sigma commented on docs/auth/microsoft/provider.md
@vinzscam My apologies -- I accidentally left this documentation update out of the first revision of this PR.

2024-10-01 14:19 UTC, jslott2sigma commented
@vinzscam Thanks for the helpful comments, I updated the PR.

2024-10-02 10:28 UTC, freben approved these changes
Alright!

2024-10-02 10:28 UTC, freben commented on docs/auth/microsoft/provider.md
> +- `skipUserProfile` (optional): If true, skips loading the user profile even if the `User.Read` scope is present. This is a performance optmization during login and can be used with resolvers that on
```suggestion
- `skipUserProfile` (optional): If true, skips loading the user profile even if the `User.Read` scope is present. This is a performance optimization during login and can be used with resolvers that only needs the email address in `spec.profile.email` obtained when the `email` OAuth2 scope is present.
```

2024-10-02 10:28 UTC, freben commented on .changeset/heavy-ties-tell.md
> +Add skipUserProfile config flag to Microsoft authenticator
```suggestion
Add `skipUserProfile` config flag to Microsoft authenticator
```

2024-10-02 11:32 UTC, vinzscam approved these changes
🚀

2024-10-02 11:39 UTC, merged