[scaffolder-react] Move template buttons from right to left
backstage/backstage pull request #26959
Opened 2024-10-03 22:12 UTC by nikolarAutodesk

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist
Our design team has mentioned this to us developers on many instances:
"[There is research to support that left alignment is better](https://adamsilver.io/blog/where-to-put-buttons-on-forms/)" 
Though there are many opportunities to improve this through out, we saw Templates as an easy win 🤞 

We are hoping others agree with this update 🙏 
<img width="1389" alt="Screenshot 2024-10-03 at 2 24 12 PM" src="https://github.com/user-attachments/assets/8c0dcde0-175c-495b-ad99-ac0fc796e272">

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-10-04 14:13 UTC, Rugvip requested changes
Sorry this is mostly down to opinion and consistency, and we generally try to keep action buttons to the right.

2024-10-04 14:17 UTC, Rugvip commented
See "Placement" at https://m2.material.io/components/buttons#text-button as well

2024-10-04 18:12 UTC, nikolarAutodesk commented
Fair enough @Rugvip! What are your thoughts on just adding an overridable class? I'm hoping this is a good compromise?

2024-10-08 06:50 UTC, benjdlambert commented
@nikolarAutodesk think that this is a better approach, but you'll need to update the `api-reports` using `yarn build:api-reports` and then commit and push the changes :tada:

2024-10-10 13:08 UTC, vinzscam commented
Closing and re-opening as DCO check went bananas 😅

2024-10-10 20:28 UTC, nikolarAutodesk commented on plugins/scaffolder-react/src/next/components/Stepper/Stepper.tsx
> +export type BackstageTemplateStepperClassKey =
thank you! That seemed to work

2024-10-11 06:14 UTC, benjdlambert approved these changes
Nice thanks :tada:

2024-10-11 06:15 UTC, merged