[Scaffolder] Test new pages header navigation
backstage/backstage pull request #26972
Opened 2024-10-04 14:01 UTC by camilaibs

Signed-off-by: Camila Belo <camilaibs@gmail.com>

## Hey, I just made a Pull Request!

Add tests for the new pages header navigation.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-10-07 06:29 UTC, benjdlambert requested changes
Just one thing thats failing the build :pray:

2024-10-07 06:29 UTC, benjdlambert commented on plugins/scaffolder/src/alpha/components/TemplateEditorPage/TemplateIntroPage.test.tsx
> +  it('Should have an action to open the custom fields explorer', async () => {
This test needs an assertion :pray:

2024-10-07 07:17 UTC, camilaibs commented on plugins/scaffolder/src/alpha/components/TemplateEditorPage/TemplateIntroPage.test.tsx
> +  it('Should have an action to open the custom fields explorer', async () => {
Oops, just fixed that 🙌🏻

2024-10-07 09:01 UTC, vinzscam approved these changes

2024-10-08 09:04 UTC, benjdlambert approved these changes

2024-10-08 09:04 UTC, merged