feat: render nested metadata as yaml
backstage/backstage pull request #26971
Opened 2024-10-04 13:18 UTC by clanghout

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

old: 
<img width="846" alt="image" src="https://github.com/user-attachments/assets/109b9dcc-477d-46b6-945e-bc4006f07e78">

new:
<img width="842" alt="image" src="https://github.com/user-attachments/assets/5274938e-5cc6-4431-bdb5-bb0cf7e42a97">

2024-10-04 19:28 UTC, vinzscam requested changes
I love it 😍

2024-10-04 19:28 UTC, vinzscam commented on .changeset/eight-cougars-collect.md
> +better rendering of nested data; rendered as yaml now
`StructuredMetadataTable` now renders data as yaml, improving readability.

2024-10-04 19:29 UTC, vinzscam requested changes

2024-10-04 19:29 UTC, vinzscam commented on .changeset/eight-cougars-collect.md
> +better rendering of nested data; rendered as yaml now
```suggestion
`StructuredMetadataTable` now renders data as yaml, improving readability.
```

2024-10-04 21:05 UTC, clanghout commented
I saw that the StructuredMetadataTable is also used in the scaffolder in the review step. The use case I showed and tested was mainly focussed on usage the kubernetes plugin. 
I do think the readability improvements will probably also hold for the scaffolder review step.

I also have to take a look at the failing tests 😓

2024-10-07 13:10 UTC, mclarke47 commented
LGTM so far!

2024-10-08 12:13 UTC, clanghout commented
Tests are green. I had to change some tests since the text formatting is now no longer applied to nested fields. The changes in the tests should show what is changing.

2024-10-08 12:21 UTC, benjdlambert commented
I'd be interested in seeing what this does in the Scaffolder Review step, and does it actually make sense, otherwise it might be worth having this as a prop to toggle the behaviour.

2024-10-10 07:07 UTC, clanghout commented
For a simple case, nothing changes:
<img width="962" alt="image" src="https://github.com/user-attachments/assets/1e927ca4-7c1d-48e1-9360-06ad63d1e0ab">


Arrays looked like this:
<img width="771" alt="image" src="https://github.com/user-attachments/assets/5f2db04c-748e-4e94-878b-fe830d618c4f">

and will look like this:
<img width="519" alt="image" src="https://github.com/user-attachments/assets/a6740f55-4832-40e8-81ce-f07c1c86ddb1">
I do spot an issue with non-wrapping text there 😓

2024-10-10 11:22 UTC, vinzscam approved these changes
🚀

2024-10-15 19:29 UTC, mclarke47 approved these changes

2024-10-29 21:20 UTC, clanghout commented
IMO ready to review

2024-11-13 13:51 UTC, clanghout commented
should I add a prop to toggle this to not impact the scaffolder?

2024-11-20 09:02 UTC, LegendSebastianoL commented
this is very cool 😊

I wonder if this could be applied to the Ingress panel as well.

![back](https://github.com/user-attachments/assets/08f8f2ef-1de0-493c-bbed-661011fc5216)

2024-11-30 17:52 UTC, sebalaini commented
Hey 👋 I was taking a look at how to fix this bug https://github.com/backstage/backstage/issues/27782 and apparently, the component you are changing is also used inside the `ContainerCard`

```
          <Grid item xs={12}>
            <Typography variant="subtitle2">Container health</Typography>
          </Grid>
          <Grid item xs={12}>
            <StructuredMetadataTable
              metadata={getContainerHealthChecks(
                containerSpec,
                containerStatus,
              )}
            />
          </Grid>
```

especially to build the Container health table

<img width="554" alt="image" src="https://github.com/user-attachments/assets/b8688b37-85d3-419d-a851-96aaef55b66b">

Have you checked what it looks like with the new change?

2024-12-13 14:22 UTC, vinzscam requested changes
can we have this feature as optional, so that we can toggle it where we want?

2024-12-13 21:07 UTC, clanghout commented
I can do it with a prop and enable it everywhere in the kubernetes plugin where it makes sense. I will make some time in the coming days for this.

2024-12-29 23:02 UTC, clanghout commented
busy times 😓

2025-01-08 14:09 UTC, clanghout commented
> can we have this feature as optional, so that we can toggle it where we want?

I added it now as a prop (as part of the options prop). I could also make it a separate prop or make a new component. Let me know what you think.

2025-01-08 17:03 UTC, benjdlambert commented
Nice! Think that this is looking pretty good, just need a changeset for the two kubernetes packages.

https://github.com/backstage/backstage/pull/26971#issuecomment-2393691189

2025-01-09 11:49 UTC, vinzscam commented on .changeset/eight-cougars-collect.md
> +`StructuredMetadataTable` now renders data as yaml, improving readability.
```suggestion
Added option to `StructuredMetadataTable` to render data as yaml.
```

2025-01-16 13:03 UTC, benjdlambert approved these changes

2025-01-16 19:01 UTC, vinzscam approved these changes
🙏

2025-01-23 18:37 UTC, acierto commented
@clanghout there are some conflicts left in the PR 😅

2025-01-23 18:38 UTC, acierto commented
We have already 3 approvals so far, who is final boss to merge it? 😆

2025-01-23 19:15 UTC, mclarke47 commented
There is a conflict

2025-01-24 07:53 UTC, benjdlambert commented
@clanghout I was just about to fix this :joy:

2025-01-24 07:54 UTC, benjdlambert commented
Should be updated now :tada:

2025-01-24 07:55 UTC, benjdlambert approved these changes

2025-01-24 08:09 UTC, merged