Fix ItemCardHeader override
backstage/backstage pull request #27106
Opened 2024-10-14 13:13 UTC by jacri901

This fixes a bug where custom themes could not override `ItemCardHeader`.
It is related to this issue [#26970 ](https://github.com/backstage/backstage/issues/26970)

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-10-29 07:02 UTC, jacri901 commented
@Rugvip, I need some more time to fix the things that blocking CI to pass. 

I try to do this
![image](https://github.com/user-attachments/assets/6ac72c4d-4352-4b59-9e88-e43e86bded03)
 
I'm having problems to generate the api-report. I can build backstage with `yarn build:all` but when I try

2024-10-29 08:04 UTC, camilaibs requested changes
Thank you for the fix @jacri901 🎉 
Could you please update the `api-reports` to resolve the conflicts?

2024-10-30 09:12 UTC, jacri901 commented
> Thank you for the fix @jacri901 🎉 Could you please update the `api-reports` to resolve the conflicts?

Yes sorry, I'll fix that later this week 😃

2024-10-30 09:35 UTC, camilaibs approved these changes
Hi @jacri901,
I tested the changes locally and it is working like a charm. So I'm going to approve and merge the pull request! Thanks again for contributing with us 🙌🏻 

![image](https://github.com/user-attachments/assets/18fca523-f20a-4b53-9564-98198ad78c74)

![image](https://github.com/user-attachments/assets/85a640cc-247f-48d3-a08b-017ae05474c7)

2024-10-30 10:14 UTC, jacri901 commented
@camilaibs thank you!

Unfortunally I got remined now that there was a test that did not pass. The previous implementation created a variable that was used as a type in the export of 'ItemCardHeaderProps'. However, this may possibly been the casue of why the overrides did not work previously. At least the way of how arguments was used in the 'makesStyles' function.

When I looked around in similar components they do not use types in the export like the previous implementaion of  'ItemCardHeaderProps' did. I tried to find a workaround previously but was unsuccesful. 

I'm open for suggestions 😄

2024-10-30 12:47 UTC, camilaibs commented
> @camilaibs thank you!
> 
> Unfortunally I got remined now that there was a test that did not pass. The previous implementation created a variable that was used as a type in the export of `ItemCardHeaderProps`. However, this may possibly been the cause of why the overrides did not work previously. At least the way of how arguments was used in the `makesStyles` function.
> 
> When I looked around in similar components they do not use types in the export like the previous implementaion of `ItemCardHeader` did. I tried to find a workaround previously but was unsuccesful.
> 
> I'm open for suggestions 😄

I think you can try something like this:
```tsx
function ItemCardHeader(props: ItemCardHeaderProps) {
  const { title, subtitle, children } = props;
  const classes = useStyles();
  return (
    <Box className={classNames(classes.root, props.classes?.root)}> 👈🏻 
      ...
    </Box>
  );
}

2024-11-06 11:24 UTC, jacri901 commented
I have looked at this a bit more.
The suggestion you had @camilaibs makes the test pass but it breaks the override again.

When I looked in /report.api.md `ItemCardGridProps` was the only thing that used `Partial<WithStyles<typeof` `styles>>` like `ItemCardHeaderProps `. I tested overrides with `ItemCardGridProps` and that implementation works, eventhough it is more or less identical to the previous version of `ItemCardHeaderProps` where the override does not work.

2024-12-27 00:28 UTC, awanlin commented
Hi @camilaibs @jacri901, any chance you can look into this early in the new year? Would be great to have this fixed. 👍

2025-01-14 08:48 UTC, mpsanchis commented
Don't stale 😄

2025-02-04 08:54 UTC, closed without merging