Add Mend Plugin
backstage/backstage pull request #27148
Opened 2024-10-15 17:16 UTC by NormanWenzelWSS

Add Mend plugin

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-10-18 14:04 UTC, vinzscam requested changes
nice! Let's wait until the plugin gets published

2024-10-18 14:04 UTC, vinzscam commented on microsite/data/plugins/mend.yaml
> +documentation: https://github.com/backstage/backstage-community-plugins/tree/main/workspaces/mend/plugins/mend
```suggestion
documentation: https://github.com/backstage/community-plugins/tree/main/workspaces/mend/plugins/mend
```

2024-10-31 13:54 UTC, NormanWenzelWSS commented
> nice! Let's wait until the plugin gets published

@vinzscam @awanlin The plugin was merged into the community plugins repo last Friday. Can you please merge this and publish the plugin package, so that the links in the portal marketplace can be updated (https://backstage.spotify.com/marketplace/mend-io/plugin/mend-io/)?

2024-11-06 06:39 UTC, dariuszsobkowicz commented
Hi @awanlin @NormanWenzelWSS, created PR to remove the private flag https://github.com/backstage/community-plugins/pull/1841

2024-11-19 18:51 UTC, awanlin approved these changes
Package has been published on NPM and the CI is green 🚀

2024-11-19 19:06 UTC, vinzscam approved these changes
let's gooo welcome 🤩

2024-11-19 19:06 UTC, merged