fix(catalog-backend-module-github): update parent to not send a object with empty value
backstage/backstage pull request #27192
Opened 2024-10-16 14:54 UTC by angeliski

## Hey, I just made a Pull Request!

Fix #26109 

When a team is created without a parent, we are sending a object with empty value and the entity created is invalid.

This PR should fix this behavior.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-10-18 14:34 UTC, vinzscam requested changes

2024-10-18 14:34 UTC, vinzscam commented on .changeset/rotten-mangos-hug.md
> +Fix bug when receive a `team.creted` github event without parent
```suggestion
Fixed an issue in `GithubOrgEntityProvider` that caused an error when processing teams without a parent.
```

2024-10-22 17:49 UTC, vinzscam approved these changes
🚀

2024-10-25 15:03 UTC, pjungermann approved these changes

2024-11-08 16:21 UTC, angeliski commented
@vinzscam could you please Merge this PR?

2024-11-15 13:02 UTC, freben approved these changes

2024-11-15 13:02 UTC, merged