feat: add i18n support for scaffolder-react plugin
backstage/backstage pull request #27193
Opened 2024-10-16 15:19 UTC by JounQin

Signed-off-by: JounQin <admin@1stg.me>## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-10-31 06:40 UTC, JounQin commented
ping

2024-11-14 09:07 UTC, JounQin commented
ping

2024-11-28 10:29 UTC, JounQin commented
ping

2024-12-11 09:57 UTC, JounQin commented
@Rugvip I've simplify this PR into only adding `Translation` component which is based on `i18next` `Trans` component.

2024-12-25 10:53 UTC, JounQin commented
ping

2025-01-16 18:49 UTC, vinzscam requested changes
could you describe how this new component should be used?

2025-01-17 05:31 UTC, JounQin commented
> could you describe how this new component should be used?

```tsx
const { Translation } = useTranslationRef(translationRef)

<Translation i18nKey="component">
  prefix <span data-testid="content">default content</span> suffix
</Translation>
```

## messages

### en:

```
component: 'prefix <1>en content</1> suffix',
```

### de:

```
component: 'prefix <1>de content</1> suffix',
```

2025-02-05 11:40 UTC, benjdlambert commented
So I wonder if we should actually change the type for the i18n library so that you can provide a `ReactNode` as the interpolation value.

So you could have a message like: `Hello {{ something }} here` and then allow for something like `t('my.message', { something: <h1>{t('my.other.message')}</h1> })` instead. 

I'm not really feeling that the solution in this PR is strong enough that we can evolve it over time. /cc @Rugvip what's your thoughts on this?

2025-02-05 12:52 UTC, vinzscam commented
> > could you describe how this new component should be used?
> 
> @vinzscam
> 
> ```tsx
> const { Translation } = useTranslationRef(translationRef)
> 
> <Translation i18nKey="component">
>   prefix <span data-testid="content">default content</span> suffix
> </Translation>
> ```
> 
> ## messages
> ### en:
> ```
> component: 'prefix <1>en content</1> suffix',
> ```
> 
> ### de:
> ```
> component: 'prefix <1>de content</1> suffix',
> ```

sorry, I'm troubles understanding what's the advantage over doing:

```ts
const { t } = useTranslationRef(translationRef)

return <>prefix {t('content')} suffix</>`;
```

🤔

2025-02-05 13:15 UTC, JounQin commented
> sorry, I'm troubles understanding what's the advantage over doing:

@vinzscam 

Oh, sorry, `prefix`/`suffix` can be different in different languages.

Something like

<img width="788" alt="image" src="https://github.com/user-attachments/assets/af8a04ab-ffbc-49a7-8058-9b3aead1f333" />

But we can manage the translation in one key.

2025-02-19 13:34 UTC, JounQin commented
ping

2025-04-02 08:53 UTC, JounQin commented
ping...

2025-04-16 09:10 UTC, JounQin commented
Oh, no...

2025-04-17 20:01 UTC, vinzscam commented
> > sorry, I'm troubles understanding what's the advantage over doing:
> 
> @vinzscam
> 
> Oh, sorry, `prefix`/`suffix` can be different in different languages.
> 
> Something like
> 
> <img alt="image" width="788" src="https://private-user-images.githubusercontent.com/8336744/410000388-af8a04ab-ffbc-49a7-8058-9b3aead1f333.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ5MjAwNzUsIm5iZiI6MTc0NDkxOTc3NSwicGF0aCI6Ii84MzM2NzQ0LzQxMDAwMDM4OC1hZjhhMDRhYi1mZmJjLTQ5YTctODA1OC05YjNhZWFkMWYzMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MTdUMTk1NjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTkyOTNmNGEzYjVhOGE4YTBjMThjNzdmYjNmZTAyMzg0NzI2MzI1NGQzNzYzY2VjY2Y3NDZlOTg4YWQ2OGU2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Fk3RamDskSAKbQDhQ-_N7Dg7-duEd9LfRrUlLZIIL7o">
> But we can manage the translation in one key.

Sorry for being slow. Could you show me how this exact example would look with the new component you're suggesting?

2025-04-17 23:46 UTC, JounQin commented
@vinzscam

English:

```jsx
Something whatever {{ prefix }} <1>en content</1> {{ suffix }}
```

Chinese:

```jsx
{{ suffix }} <1>中文内容</1> 随便什么{{ prefix }} 
```

The order or `prefix` and `suffix` can be different in different languages.

2025-04-29 12:20 UTC, vinzscam commented
> @vinzscam
> 
> English:
> 
> ```js
> Something whatever {{ prefix }} <1>en content</1> {{ suffix }}
> ```
> 
> Chinese:
> 
> ```js
> {{ suffix }} <1>中文内容</1> 随便什么{{ prefix }} 
> ```
> 
> The order or `prefix` and `suffix` can be different in different languages.

ooooh I see now, thank you! 🙏

but currently you can define the translations as: 

```
// translation.ts
key: {
  content: 'Something whatever {{ prefix }} content {{ suffix }}',
  prefix: 'prefix',
  suffix: 'suffix'
}
```

where you basically can change where prefix and suffix should be rendered.

Then you render everything with:

```ts
t('key.content', { prefix: t('key.prefix'), suffix: t('key.suffix') })'
```

Does this work, or is there anything else I've missed?

2025-04-30 01:13 UTC, JounQin commented
@Rugvip Great! Thanks for your efforts!

2025-05-07 08:43 UTC, JounQin commented
close in favor of #29786

2025-05-07 08:43 UTC, closed without merging

2025-05-07 08:43 UTC, JounQin commented
close in favor of #29786