Add proxyEndpointsExtensionPoint
backstage/backstage pull request #27257
Opened 2024-10-18 19:33 UTC by mbenson

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

IDK how to test an extension point, although I have exercised it in the `dev` mode of `@backstage/plugin-proxy-backend`.

2024-10-21 16:09 UTC, mbenson commented
The `backstage-cli repo fix --publish --check` thing _seems_ to have to do with the fact that `plugins/proxy-node` is new :/

2024-10-23 22:58 UTC, aramissennyeydd commented
@mbenson 👋 Can you share some more context on this change? Curious if there's a config-first way of going about this.

I was also having issues with the check, if you just run `yarn fix` locally, the problem was autofixed.

2024-10-23 23:15 UTC, mbenson commented
In this case I am attempting to support the pattern of: "plugin wants to support integration with a third-party application in such a way as to set up a proxy alongside some other customizations," which might share config values and thus violate DRY/present opportunity for misconfiguration if the user is forced to apply related configuration in multiple places.

2024-10-23 23:22 UTC, aramissennyeydd commented
One thing that comes to mind here might be using YAML anchors in the config files. You define the anchor once and can use it in a bunch of places. (example)[https://www.linode.com/docs/guides/yaml-anchors-aliases-overrides-extensions/]. Looks like we use https://www.npmjs.com/package/yaml under the hood which supports that.

2024-10-24 01:29 UTC, mbenson commented
Still requires the user to do it

2024-11-05 12:23 UTC, Rugvip reviewed
Thank you! 👍 

Been seeing a need for this too so happy to make this addition. Just looking to refine it a bit to keep the API a bit more narrow and well defined.

2024-11-07 21:23 UTC, mbenson commented on plugins/proxy-node/src/alpha/index.ts
> +  addProxyEndpoints(endpoints: JsonObject): void;
I'm not opposed; I'll try to have a look by next week

2024-11-16 18:38 UTC, mbenson commented on plugins/proxy-backend/src/service/router.ts
> +  additionalEndpoints?: JsonObject;
As a contributor I was of course only trying to change what was immediately relevant; also does this not represent any undesirable breakage of backward comnpatibility? If this is still desired after addressing these points, I don't mind making the change or for a maintainer to do so.

2024-12-07 02:31 UTC, awanlin requested changes
Thanks for this contribution @mbenson, my review is focused on the docs and I left a pair of comments related to that.

2024-12-07 02:31 UTC, awanlin commented on docs/plugins/proxying.md
> +            '/foo': 'http://foo.org',
Two closely related questions:

1. How does one add headers with variables?
2. How does one add credentials?

If we can add examples for both of these that would be great.

2024-12-07 02:31 UTC, awanlin commented on docs/plugins/proxying.md
> +### New backend extension
```suggestion
### Proxy Extension Endpoint
```

2025-01-03 15:21 UTC, mbenson commented on plugins/proxy-backend/src/service/router.ts
> +  additionalEndpoints?: JsonObject;
@benjdlambert thoughs?

2025-01-14 07:01 UTC, benjdlambert approved these changes

2025-01-14 07:30 UTC, merged