Add custom column example for existing Kind
backstage/backstage pull request #27353
Opened 2024-10-25 09:54 UTC by jescalada

## Hey, I just made a Pull Request!

Related Issue: #27238

**Note:** I might have completely missed the point with my example. Should the user only be able to modify the `App.tsx`, in which case we want to pass in a `CatalogTableColumnsFunc` which checks for the User entity and adds the columns instead of an array to the `CatalogIndexPage` component? Or is what I wrote a valid approach too? In both cases the desired behaviour can be achieved.

Implemented User Email column based on example code:
![image](https://github.com/user-attachments/assets/e72defef-2566-42ea-82a9-90d622b2abc8)

### Changelog
- Added new examples to `software-catalog/catalog-customization.md` doc on how to create or modify columns for existing Kinds.
- Clarified/reworded existing sections

2024-11-06 19:55 UTC, vinzscam requested changes
Thank you for your work on this, @jescalada 🙏
Would it be possible to adapt this procedure to a Backstage app layout created using npx @backstage/create-app? This is the recommended approach for creating Backstage apps, and users will not have a /plugins/catalog/* folder.

2024-11-07 04:16 UTC, jescalada commented
> Thank you for your work on this, @jescalada 🙏 Would it be possible to adapt this procedure to a Backstage app layout created using npx @backstage/create-app? This is the recommended approach for creating Backstage apps, and users will not have a /plugins/catalog/* folder.

I suspected this was the case 😅 Thankfully it only required redefining the email column definition on the `App.tsx`! Now the whole example only requires editing the `App.tsx` file.

2024-11-15 13:09 UTC, vinzscam requested changes
this looks great @jescalada 🙏

added just some minor suggestions

2024-11-15 13:09 UTC, vinzscam commented on docs/features/software-catalog/catalog-customization.md
> +      CatalogTable.columns.createTagsColumn(),
```suggestion
    return [
      // Render existing columns
      ...CatalogTable.defaultColumnsFunc(entityListContext),
```

2024-11-15 13:09 UTC, vinzscam commented on docs/features/software-catalog/catalog-customization.md
> +
I'm thinking we could skip this

```suggestion
```

2024-11-15 13:09 UTC, vinzscam commented on docs/features/software-catalog/catalog-customization.md
> +      CatalogTable.columns.createTagsColumn(),
```suggestion
    return [
      // Render existing columns
      ...CatalogTable.defaultColumnsFunc(entityListContext),
```

2024-11-19 03:30 UTC, jescalada commented
Thanks for the review! I committed the requested changes.

2024-12-04 00:33 UTC, jescalada commented
Pinging @vinzscam for visibility :)

2024-12-20 14:14 UTC, awanlin approved these changes
Thanks for adding this @jescalada 🚀

2024-12-20 14:15 UTC, merged