feat(lint): Add `--max-warnings -1` option to package lint
backstage/backstage pull request #27456
Opened 2024-11-04 14:22 UTC by Glenf

## Hey, I just made a Pull Request!

Add `--max-warnings -1` support to `backstage-cli package lint`. This reflects ESLint behaviour.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-11-05 08:09 UTC, Glenf commented
Should there be an option to pass `--max-warnings` on `repo lint` level also? This would overwrite same option passed on `package lint`.

2024-11-05 10:01 UTC, jhaals requested changes
Thanks for the PR, minor tweak needed :)

2024-11-05 10:01 UTC, jhaals commented on .changeset/loud-plants-dream.md
> +'@backstage/cli': minor
```suggestion
'@backstage/cli': patch
```

Package is 0.x so patch is enough for new features

2024-11-06 10:27 UTC, jhaals approved these changes
Thanks!

2024-11-08 07:20 UTC, Rugvip approved these changes
thank you!  :+1:

2024-11-08 07:20 UTC, merged