fix: @typescript-eslint incompatible versions with eslint@8.x.x
backstage/backstage pull request #27501
Opened 2024-11-05 17:19 UTC by danielfigueiredo

## Hey, I just made a Pull Request!

This issue is happening when running `yarn backstage-cli versions:bump`, a full detailed explanation of the error can be found in [this issue](https://github.com/backstage/backstage/issues/27500).

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation N/A
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes) N/A
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-11-18 21:25 UTC, andrewthauer approved these changes

2024-11-18 22:46 UTC, awanlin requested changes
Thanks @danielfigueiredo, left a few comments. Seems other reports of this so let's try to push this forward. 👍

2024-12-03 15:58 UTC, danielfigueiredo commented on packages/cli/package.json
> +    "@typescript-eslint/parser": "^7.18.0",
I think 8 has more changes required in the tool chain, but I can try and see if anything comes up!

2024-12-04 17:06 UTC, danielfigueiredo commented on packages/cli/package.json
> +    "@typescript-eslint/parser": "^7.18.0",
Upgraded all eslint and plugins to latest! 🎉

2024-12-04 17:32 UTC, danielfigueiredo commented
@awanlin, apologies for the delay, but I've addressed the comments and bumped every lint plugin down to the latest!

2024-12-23 13:35 UTC, andrewthauer commented
Any chance you could re-review this @awanlin? Thanks!

2024-12-23 15:07 UTC, awanlin approved these changes
Thanks @danielfigueiredo, looks good to me now. You'll still need the maintainers to review.

2024-12-23 15:09 UTC, awanlin commented
Hi @benjdlambert, any chance you can give this one a look, please? Got a few reports of this being an issue and this looks to be something we'd want to do anyway. Now would also be a good time to get it in as we are at the start of the monthly release cycle.

2024-12-24 09:50 UTC, benjdlambert approved these changes

2024-12-24 09:50 UTC, merged

2025-01-07 16:09 UTC, danielfigueiredo commented
> Hmm, ok, happy to try this out seen as it didn't seem to break anything in the build. Still a little unsure on the impact to other users, but let's test this internally in the `-next` release too.

@benjdlambert let me know if it causes any undesired side-effect, happy to investigate and patch!

Usually, the plugins and the eslint version need be kept up-to-date together as newer versions can be incompatible with older plugin ones