Logout errors with multiple providers
backstage/backstage pull request #2751
Opened 2020-10-05 10:36 UTC by ebarriosjr

## Hey, I just made a Pull Request!

I was having the problem that when you use multiple logins (in my case google and github) on Sign out the githubSession key on the local storage does not get deleted. This causes that on the next logging the auth system gets confused. I thought about clearing the entire local storage but this will remove user preferences for the page too (like the dark mode selection, pinned bar, etc)

Maybe this is not the right way to do it. But it does work :)

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

2020-10-05 11:10 UTC, Rugvip requested changes
Yep, not the way to do it x)

Seems like `AuthSessionStore` should be removing this key, which in turn should be called via the `signOut` method in the `SignInPage` provider.

Do you have some steps to reproduce the issue?

2020-10-05 11:18 UTC, ebarriosjr commented
I tried @Rugvip  jejejeje... I can tell you exactly how it happens:
1. Log in with google from the main login page.
2. Log in with github via the side navbar.
3. Sign out via the button on the side navbar.
4. Log back in with google from the main login page.
5. If you check the localstorage you can still see the gitbubSession key there, but the login indicator in the nav bar is not active.
6. If you try to use any plugin that uses github (it may work depending if your token expired or not)

2020-10-05 13:37 UTC, ebarriosjr commented
@Rugvip I added the refresh token to the github app. Could you take a look and give me your opinion?

2020-10-09 08:41 UTC, Rugvip reviewed
👍 , Think backend should be good, but comments on the frontend bit

2020-10-09 08:41 UTC, Rugvip commented on packages/core-api/src/apis/implementations/auth/github/GithubAuth.ts
> +    const sessionManager = new RefreshingAuthSessionManager({
Not sure about removing the `StaticAuthSessionManager` tbh, I'm thinking we either want to make this client-side implementation support both GitHub Apps and OAuth Apps, or to have a client for each.

I think a first attempt could be whether we can `GithubAuth` instance can have both a `refreshingSessionManager` and a `staticSessionManager`, and then switch which one is being used automatically. It's likely that doesn't work though, and then I'd prolly try making it either an option to the static factory method, or two different static factory methods depending on the use-case.

If we do end up with having to configure the client in the app, then I think we should stick to OAuth by default, and then switch over to GitHub App by default once we build out support for that in the project.

2020-10-09 08:41 UTC, Rugvip commented on packages/core-api/src/apis/implementations/auth/github/GithubAuth.ts
> +    defaultScopes = ['read:user'],
Don't think this is needed?

2020-10-09 08:41 UTC, Rugvip commented on packages/core-api/src/apis/implementations/auth/github/GithubAuth.ts
> +    this.sessionManager = options.sessionManager;
Keep this as it was

2020-10-09 08:47 UTC, freben commented on plugins/auth-backend/src/providers/github/provider.ts
> +          'github.com/email': profile.email,
specifically this https://github.com/spotify/backstage/blob/master/docs/features/software-catalog/well-known-annotations.md#githubcomuser-login

2020-10-22 12:51 UTC, benjdlambert commented
@ebarriosjr is this still something that you could fix up for us?

2021-01-12 20:56 UTC, freben commented
one more ping - @ebarriosjr is this something you'd be able to continue on?

2021-01-18 18:15 UTC, Rugvip commented
Gonna close this as I believe #3770 fixed the underlying issue. Let's reopen if that's not the case

2021-01-18 18:15 UTC, closed without merging