feat(notifications): add title to the Notifications' table
backstage/backstage pull request #27568
Opened 2024-11-09 21:36 UTC by mareklibra

## Hey, I just made a Pull Request!

Notifications' table has newly a title with count of filtered records.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-11-09 21:37 UTC, mareklibra commented
![unread](https://github.com/user-attachments/assets/b787b9e9-79ad-4893-bdfd-cde174569000)

---

![saved](https://github.com/user-attachments/assets/a33b9e1c-dfe2-4a3c-b204-04b9e6523bed)

2024-11-12 10:20 UTC, jhaals requested changes
Looking good! Minor tweaks and this should be good to go 👏

2024-11-12 10:20 UTC, jhaals commented on .changeset/khaki-pugs-perform.md
> +Added title to the Notifications' table. The title clearly states the filter selectino and total count of messages. This change aligns the look and fel closer to other tables.
```suggestion
Added title to the Notifications' table. The title clearly states the filter selectin and total count of messages. This change aligns the look and feel closer to other tables.
```

2024-11-12 10:20 UTC, jhaals commented on .changeset/khaki-pugs-perform.md
> +'@backstage/plugin-notifications': minor
```suggestion
'@backstage/plugin-notifications': patch
```
Package is below 1.x so a `patch` changeset is enough for introducing new non breaking features.

2024-11-13 07:39 UTC, mareklibra commented on .changeset/khaki-pugs-perform.md
> +Added title to the Notifications' table. The title clearly states the filter selectino and total count of messages. This change aligns the look and fel closer to other tables.
done

2024-11-13 08:33 UTC, jhaals approved these changes
Great!

2024-11-13 08:33 UTC, merged