Create jenkins-actions.yaml
backstage/backstage pull request #28008
Opened 2024-12-06 12:22 UTC by robertonav20

Add microsite configuration for @backstage-community/plugin-scaffolder-backend-module-jenkins

Hi,
i would publish the microsite configuration to publish on backstage plugins site the plugin @backstage-community/plugin-scaffolder-backend-module-jenkins.
At the moment is missing a reference to that plugin.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2025-01-14 07:52 UTC, benjdlambert requested changes

2025-01-14 07:52 UTC, benjdlambert commented on microsite/data/plugins/jenkins-actions.yaml
> +iconUrl: https://img.icons8.com/color/1600/jenkins.png
Is there a better place for us to link out to an image here? Or can we just copy the jenkins logo into this repo? :pray:

2025-01-15 12:18 UTC, robertonav20 commented on microsite/data/plugins/jenkins-actions.yaml
> +iconUrl: https://img.icons8.com/color/1600/jenkins.png
I don't know how the site is working... In case we decide to proceed with store locally the logo how could I reference, just with relative path? There is an example?

2025-01-28 08:30 UTC, benjdlambert commented on microsite/data/plugins/jenkins-actions.yaml
> +iconUrl: https://img.icons8.com/color/1600/jenkins.png
Here's an example: https://github.com/backstage/backstage/blob/master/microsite/data/plugins/score-card.yaml#L8

2025-02-01 10:14 UTC, robertonav20 commented on microsite/data/plugins/jenkins-actions.yaml
> +iconUrl: https://img.icons8.com/color/1600/jenkins.png
Hi @benjdlambert,
now should be ok

2025-02-18 07:54 UTC, benjdlambert approved these changes
Nice thanks! :tada:

2025-02-18 07:54 UTC, merged

2025-02-18 08:04 UTC, robertonav20 commented
It was a pleasure there is also this pr https://github.com/backstage/community-plugins/pull/2903 which introduce other actions