Add scaffolderPermissionsExtensionPoint
backstage/backstage pull request #28053
Opened 2024-12-09 15:16 UTC by CptnFizzbin

Adds a scaffolder permissions extension point to allow permission policy writers add custom rules and permissions for scaffolder actions and parameters

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2024-12-09 18:45 UTC, CptnFizzbin commented
@vinzscam @benjdlambert, I'v extracted this subfeature from #27748 after finding out that additional work would be needed there.

2025-01-03 12:38 UTC, vinzscam requested changes
thanks, really good stuff! 🙏

2025-01-06 15:46 UTC, CptnFizzbin commented on plugins/scaffolder-backend/src/deprecated.ts
> + * @deprecated Use `ActionPermissionRuleInput` from `@backstage/plugin-scaffolder-node/alpha` instead
It's used as part of the API surface for the new extension point. The catalog plugin follows a similar structure

2025-01-10 14:50 UTC, Rugvip requested changes
Update since the framework SIG: the permissions registry service as it ended up being called is now more or less ready: https://github.com/backstage/backstage/pull/28400. Unless something pops up we'll ship it soon after the release next week, so best build on top of it instead, removing the permission extension points altogether.

The main thing to do to add support for it is to migrate the scaffolder backend itself away from using the permission integration router, there are a few migration docs in the new service docs in the PR.

2025-01-13 18:07 UTC, CptnFizzbin commented
@Rugvip, rebased atop your branch.

2025-01-15 09:17 UTC, closed without merging