Add enhancements to entitypickers
backstage/backstage pull request #28124
Opened 2024-12-12 19:11 UTC by thomastriplett

## Hey, I just made a Pull Request!

The UI configuration for the EntityTagPicker, EntityAutocompletePicker, and UserListPicker didn't include an option to hide the UI from users like some of the other pickers.  Additionally, the EntityTagPicker didn't include an option to add an initial filter and the UserListPicker assumed that setting the filter to "all" when no matching entities are found is always the desired behavior.

I added addtional props to these components to enhance their functionality.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2025-01-06 14:27 UTC, thomastriplett commented
@Rugvip @vinzscam does this look ready to merge?

2025-01-07 09:40 UTC, Rugvip requested changes
Thank you! 👍 

Looks good in general, just a naming nit on the new prop

2025-01-07 09:40 UTC, Rugvip commented on plugins/catalog-react/src/components/UserListPicker/UserListPicker.tsx
> +    resetFiltersWhenNoResultsFound = true,
I'd rather flip the logic of this one around so that it becomes a boolean flag that you set to true to change the behavior, it avoids an awkward `flag={false}` prop instead of just `flag`.

Perhaps `alwaysKeepFilters` or something like that?

2025-01-13 20:44 UTC, thomastriplett commented
@Rugvip @vinzscam I made the requested changes.  Is there anything else I need to do or is this PR good to go now?

2025-01-22 14:05 UTC, thomastriplett commented
@Rugvip @vinzscam Bumping again to see if there's any more changes I should make

2025-01-22 20:28 UTC, vinzscam requested changes
I think this is good! Just a tweak to the changeset and we can ship

2025-01-22 20:28 UTC, vinzscam commented on .changeset/fuzzy-worms-beg.md
> +The EntityTagPicker will now include the "hidden" and "initialFilter" props. The EntityAutocompletePicker will now include the "hidden" prop. The UserListPicker will now include the "hidden" and "res
```suggestion
Added `hidden` prop to `EntityTagPicker`, `EntityAutocompletePicker` and `UserListPicker`.
Added `initialFilter` prop to `EntityTagPicker` to set an initial filter for the picker.  
Added `alwaysKeepFilters` prop to `UserListPicker` to prevent filters from resetting when no entities match the initial filters.
```

2025-01-22 22:33 UTC, thomastriplett commented
One of the checks failed but it appears to be unrelated to the changeset, unless I'm mistaken.  Can you re-run the action on your end?

2025-02-03 22:06 UTC, thomastriplett commented
@vinzscam @Rugvip I've fixed the issue with the checks, so this PR should be ready to go!

2025-02-11 16:05 UTC, closed without merging