Add DevPod plugin to plugins marketplace
backstage/backstage pull request #28320
Opened 2024-12-30 16:24 UTC by vrabbi

## Hey, I just made a Pull Request!
Add DevPod plugin to plugins marketplace

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2025-01-02 21:43 UTC, awanlin requested changes
Thanks for this one as well @vrabbi, left one comment.

2025-01-02 21:43 UTC, awanlin commented on microsite/data/plugins/devpod.yaml
> +iconUrl: https://devpod.sh/docs/media/devpod-logo.png
Do you have permission to use this logo?

2025-01-03 11:49 UTC, vrabbi commented on microsite/data/plugins/devpod.yaml
> +iconUrl: https://devpod.sh/docs/media/devpod-logo.png
changed the image to use the image from the public OSS GitHub repo

2025-01-04 20:15 UTC, awanlin commented on microsite/data/plugins/devpod.yaml
> +iconUrl: https://devpod.sh/docs/media/devpod-logo.png
Just because it's public doesn't mean we can use it any way we like, that's been my experience. Can you share some documentation from them allowing this use, please?

2025-01-05 15:59 UTC, vrabbi commented on microsite/data/plugins/devpod.yaml
> +iconUrl: https://devpod.sh/docs/media/devpod-logo.png
as its under an OSS repo i would think it is allowed, but in any event i opened an issue on the DevPod repo to get clarification from their end

2025-01-07 12:31 UTC, benjdlambert commented
Cross posting the issue from devpod https://github.com/loft-sh/devpod/issues/1519

2025-01-07 13:53 UTC, vrabbi commented on microsite/data/plugins/devpod.yaml
> +iconUrl: https://devpod.sh/docs/media/devpod-logo.png
The approval has been given in the linked issue from the devpod team at loft

2025-01-07 16:21 UTC, vrabbi commented
Is there anything else left from my side to help push this forwards?

2025-01-10 08:09 UTC, vrabbi commented
@benjdlambert @vinzscam could i get a review on this.
Thanks in advance!

2025-01-14 20:10 UTC, awanlin approved these changes

2025-01-16 19:08 UTC, vinzscam commented on microsite/data/plugins/devpod.yaml
> +iconUrl: https://github.com/loft-sh/devpod/blob/main/docs/static/media/devpod-logo.png?raw=true
```suggestion
iconUrl: https://raw.githubusercontent.com/loft-sh/devpod/refs/heads/main/docs/static/media/devpod-logo.png
```

2025-01-17 14:00 UTC, vrabbi commented
@vinzscam i made the change requested. Anything else needed from my side?

2025-01-20 12:55 UTC, vinzscam approved these changes
thank you!

2025-01-20 12:56 UTC, merged