Add ScaleOps plugin to plugins marketplace
backstage/backstage pull request #28321
Opened 2024-12-30 16:30 UTC by vrabbi

## Hey, I just made a Pull Request!
Add ScaleOps plugin to plugins marketplace

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2025-01-02 21:41 UTC, awanlin requested changes
Thanks for this contribution @vrabbi, left a pair of comments.

2025-01-02 21:41 UTC, awanlin commented on microsite/data/plugins/scaleops.yaml
> +documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/scaleops-frontend
The [documentation here](https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/scaleops-frontend#configuration) is a little worrisome. When will you have a proper secured version ready? Maybe it would be best to wait for that to be in place.

2025-01-02 21:41 UTC, awanlin commented on microsite/data/plugins/scaleops.yaml
> +iconUrl: https://parsers.vc/logo/71a9c12c-230f-4f96-8d2a-70c637b024ef-3.png
Do you have permission to use this logo?

2025-01-03 12:08 UTC, vrabbi commented on microsite/data/plugins/scaleops.yaml
> +documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/scaleops-frontend
the docs were outdated and support was already added for scaleops auth but not for all of the auth methods. i updated the docs with supported auth methods. currently i dont plan on adding additional auth methods proactively and am waiting for community feedback and requests to add them in, as we do not utilize the other methods in our environments.

2025-01-03 12:09 UTC, vrabbi commented on microsite/data/plugins/scaleops.yaml
> +iconUrl: https://parsers.vc/logo/71a9c12c-230f-4f96-8d2a-70c637b024ef-3.png
updated the icon URI to a public github image

2025-01-04 20:16 UTC, awanlin commented on microsite/data/plugins/scaleops.yaml
> +iconUrl: https://parsers.vc/logo/71a9c12c-230f-4f96-8d2a-70c637b024ef-3.png
Just because it's public doesn't mean we can use it any way we like, that's been my experience. Can you share some documentation from them allowing this use, please?

2025-01-04 20:18 UTC, awanlin commented on microsite/data/plugins/scaleops.yaml
> +documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/scaleops-frontend
This part in the proxy config is still a concern: `credentials: dangerously-allow-unauthenticated`. Do the other options now work? Ideally the default for this should be `require` that way you need at minimum a Backstage token to call this endpoint.

2025-01-04 20:25 UTC, vrabbi commented on microsite/data/plugins/scaleops.yaml
> +documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/scaleops-frontend
ive checked and that is no longer needed. i removed that setting. thanks for the pointer. indeed this was there initially but is not needed anymore so good to get rid of it

2025-01-04 20:26 UTC, vrabbi commented on microsite/data/plugins/scaleops.yaml
> +iconUrl: https://parsers.vc/logo/71a9c12c-230f-4f96-8d2a-70c637b024ef-3.png
i will talk to them tomorrow and get approval from them. i will then just add the image to my plugin repo and link from there or give the URL they prefer.

2025-01-07 11:41 UTC, vrabbi commented on microsite/data/plugins/scaleops.yaml
> +iconUrl: https://parsers.vc/logo/71a9c12c-230f-4f96-8d2a-70c637b024ef-3.png
Ive discussed with them and have approval from them to use the logo

2025-01-07 16:21 UTC, vrabbi commented
Is there anything else left from my side to help push this forwards?

2025-01-10 08:08 UTC, vrabbi commented
@benjdlambert @vinzscam could i get a review on this.
Thanks in advance!

2025-01-14 20:11 UTC, awanlin approved these changes

2025-01-16 19:05 UTC, vinzscam approved these changes
🙏

2025-01-17 14:01 UTC, vrabbi commented
Is there something wrong with the automated checks? It seems one of the checks has not finished for over 18 hours.

2025-01-20 21:56 UTC, vrabbi commented
@vinzscam do you know if there is something wrong with the actions here? I see both approvals and one action still running now for multiple days and dont know what i can do to fix it

2025-01-23 09:24 UTC, vrabbi commented
@awanlin do you know what could cause the DCO check to be stuck or how this can be fixed? not sure how to fix this and get this merged. any help would be greatly appreciated!

2025-01-23 13:24 UTC, benjdlambert commented
@vrabbi if you rebase and repush it should fix it :pray:

2025-01-23 14:30 UTC, vrabbi commented
thanks @benjdlambert for the tip. all looks green now!

2025-01-27 04:55 UTC, vrabbi commented
Now that everything looks green, could you help merge this? @benjdlambert @vinzscam 
Thanks in advance for your help!

2025-01-30 21:58 UTC, vrabbi commented
@awanlin can you help with merging this?

2025-02-03 06:43 UTC, freben approved these changes
Alright for now. But note that you are asking the system to send passwords [to the frontend](https://github.com/TeraSky-OSS/backstage-plugins/blob/9c5fe65b1193b7f7ef25642814ee548a27b3f1c6/plugins/scaleops-frontend/config.d.ts#L55), which is a security problem. If you are sending traffic to the proxy you can transparently inject an authorization header there. Or make a dedicated backend plugin that exposes only what's needed and requires backstage auth to call.

2025-02-03 06:44 UTC, merged