feat(plugin): glean
backstage/backstage pull request #28324
Opened 2024-12-30 17:40 UTC by beejiujitsu

## Hey, I just made a Pull Request!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2025-01-02 21:29 UTC, awanlin requested changes
Thanks for sharing this plugin @beejiujitsu, left a few small comments 👍

2025-01-02 21:29 UTC, awanlin commented on microsite/data/plugins/glean.yaml
> +addedDate: '2024-12-30'
Small nit: can you add a line break, please?

2025-01-02 21:29 UTC, awanlin commented on microsite/data/plugins/glean.yaml
> +documentation: https://github.com/beejiujitsu/wealthsimple-backstage-plugins/tree/master/plugins/glean-backend
Would it be possible to share Wealthsimple's involvement with this plugin? It looks to be under your GitHub Org and NPM scope - `beejiujitsu` - but the repo is called `wealthsimple-backstage-plugins`.

2025-01-02 21:29 UTC, awanlin commented on microsite/static/img/glean-logo-circular-white.png
Do you have permission to use the Glean logo?

2025-01-02 21:30 UTC, awanlin commented
Oh, and to get the CI green you need to run `yarn prettier:fix` in the `/microsite` folder.

2025-01-08 09:13 UTC, benjdlambert commented
@beejiujitsu there's a separate prettier config in the microsite directory. So you'll need to do `cd microsite && yarn install &&  yarn prettier --write .`

2025-01-09 15:02 UTC, beejiujitsu commented
@benjdlambert @awanlin fixed and ready for review

2025-01-14 06:46 UTC, benjdlambert approved these changes
Nice, let's go with this! :tada:

2025-01-14 06:46 UTC, merged