Adopt an open governance model
backstage/backstage pull request #3183
Opened 2020-10-30 14:20 UTC by stefanalund

## Hey, I just made a Pull Request!

As part of [donating](https://github.com/cncf/toc/issues/530) Backstage the CNCF we are adopting an open governance model:

https://github.com/opengovernance/opengovernance.dev

This PR adds a first revision of the Backstage governance model. It borrows from other CNCF projects like:

https://github.com/cortexproject/cortex/blob/master/GOVERNANCE.md
https://github.com/linkerd/linkerd2/blob/main/GOVERNANCE.md

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/spotify/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

2020-10-30 14:28 UTC, Fox32 commented on MAINTAINERS.md
> +- Oliver Sand - SDA-SE (GitHub: @Fox32)
```suggestion
- Oliver Sand - SDA SE (GitHub: @Fox32)
```
Just a minor change, but that's the right company name 😉

2020-10-30 14:57 UTC, Rugvip approved these changes
🎉

2020-10-30 16:13 UTC, adamdmharvey reviewed
🎉

2020-10-30 16:13 UTC, adamdmharvey commented on GOVERNANCE.md
> +- an explanation of why the nominee should be a committer,
```suggestion
- an explanation of why the nominee should be a maintainer,
```

maybe?

2020-10-31 14:26 UTC, andrewthauer requested changes, later dismissed
Small typo

2020-10-31 14:26 UTC, andrewthauer commented on GOVERNANCE.md
> +A new maintainer must be proposed by an existing maintainer by opening an issue (with title `Maintainer Nomination`) to the Backstage GitUub repository (https://github.com/backstage/backstage) contai
```suggestion
A new maintainer must be proposed by an existing maintainer by opening an issue (with title `Maintainer Nomination`) to the Backstage GitHub repository (https://github.com/backstage/backstage) containing the following information:
```

2020-10-31 16:09 UTC, merged