techdocs-common: Release v0.3.4
backstage/backstage pull request #4096
Opened 2021-01-15 11:50 UTC by OrkoHunter

Release a newer version of `@backstage/techdocs-common` including a bug fix https://github.com/backstage/backstage/pull/4088.

---

Reference documentation (if a package has to be released independently): (Inspiration from @backstage/silver-lining )

1. Remove all changesets inside `.changeset`.
2. Restore changesets that belong to your package.
3. Run `yarn changeset version`.
4. Restore all other changesets, except the ones that belong to your package.
5. Create PR

The version change in the package.json will trigger the publish workflow.

2021-01-15 11:52 UTC, emmaindal approved these changes

2021-01-15 11:53 UTC, Rugvip commented
Meh, so recent release workflow changes broke separate releases. Don't merge this yet and we'll figure out how to fix ^_>

2021-01-15 11:54 UTC, OrkoHunter commented
Oh, Okay!

2021-01-15 11:55 UTC, OrkoHunter commented
Requesting a review. Please approve when you think it's possible!

2021-01-15 12:27 UTC, Rugvip commented
Does having to push a branch that references the merge commit from this PR and then trigger a workflow manually seem like an alright workaround for now? ^_>

2021-01-15 12:32 UTC, Rugvip requested changes
To be clear we should really not merge this yet, would put us in a bad state :grin:

2021-01-18 10:15 UTC, Rugvip approved these changes

2021-01-18 10:16 UTC, merged