Improve frontend dockerfile
backstage/backstage pull request #4535
Opened 2021-02-15 14:48 UTC by titilambert

## Hey, I just made a Pull Request!

I added `yq` to the Frontend dockerfile to be able to read configuration from the yq file.
This permits to handle configuration with array structures (like homepage.clocks....)

#### :heavy_check_mark: Checklist

- [ ] Added or updated documentation

2021-02-15 15:03 UTC, backstage-service commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4535-nwodz2bjxx3lgnq3d9oqv09euz2jwmzg.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/602a89ad65f8172d20f0ba76

2021-02-15 15:10 UTC, Rugvip requested changes
Thanks!

Not entirely opposed to the idea of being able to load in config from a file in addition to env, but need to take a bit more caution imo. The app-config.yaml files require quite a bit of processing to be used properly, both for replacing things like `$env` keys and other substitutions, but also filter for visibility in the frontend using the config schema.

We could add something like this, but I think we should make it very clear that it will be used in unprocessed form and sent directly to the frontend, and should not be shared with backend config. Perhaps by simply calling the file `frontend-config.yaml`?

2021-02-15 15:10 UTC, Rugvip commented on contrib/docker/frontend-with-nginx/docker/run.sh
> +  # Read runtime config from yaml file (it could be the backend one)
Absolutely could not be the same as the backend one 😅 , it won't be filtered for secrets, so any secrets in the app config would be sent straight on to the frontend.

2021-03-01 10:32 UTC, Rugvip commented
@titilambert what's your thoughts on the way forward? Do you want to keep the logic and update the docs a bit?

2021-03-13 13:58 UTC, freben commented
Hi! We're closing this one for now. Let us know if you think that was in error.

2021-03-13 13:58 UTC, closed without merging