5033: (fix) adds locationAnalyzer to default-app template
backstage/backstage pull request #5037
Opened 2021-03-20 12:38 UTC by azerbe

Signed-off-by: Alexander Zerbe <alex@aqube.de>

## Hey, I just made a Pull Request!

Resolves #5033 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

2021-03-20 12:42 UTC, freben approved these changes
Yes!

2021-03-20 12:44 UTC, freben commented
Oh dang, forgot one thing. The changeset. You'll need to do `yarn changeset` and mark a patch release for this package. AND you'll write a little bit of text in that changeset file about how people can do the corresponding thing by hand in their already-created env. See previous changelog entries for that package for inspiration

2021-03-20 13:51 UTC, azerbe commented
Alright. Will add this later.

2021-03-20 18:32 UTC, freben commented
Also a minor typo build error https://github.com/backstage/backstage/pull/5037/checks?check_run_id=2155347618

2021-03-20 18:34 UTC, freben requested changes

2021-03-20 18:34 UTC, freben commented on packages/create-app/templates/default-app/packages/backend/src/plugins/catalog.ts
> +  locationAnalyzer,
This line should be on line 14-16

2021-03-24 10:57 UTC, freben commented on .changeset/curly-fishes-speak.md
> +```
I rudely added the diff here on top of your changes, to make sure that the user sees it clearly in front of them. They won't be "in the context of" this repo necessarily when reading this; they have their own private repo and won't have the create-app source easily available in front of them.

2021-03-24 10:57 UTC, freben approved these changes

2021-03-24 13:16 UTC, LEBATRUNG approved these changes

2021-03-24 13:36 UTC, merged