[plugin] Google Analytics Dashboard
backstage/backstage pull request #662
Opened 2020-04-27 19:22 UTC by marcuseide

Plugin that uses Google's [Core Reporting API](https://developers.google.com/analytics/devguides/reporting/core/v3/) for GA to display a small dashboard.

<img width="1673" alt="Screenshot 2020-04-27 at 20 58 44" src="https://user-images.githubusercontent.com/18682151/80409953-0234af80-88ca-11ea-8155-d3bfbb75f0df.png">

Features:
- Uses Google OAuth for Client-side Web Applications and provides an easy way to login with a button using `gapi.signin2`.
- Fetches all GA accounts and views associated with the current user and automatically updates the dashboard.
- Stores settings in `localStorage`. 

Todo:
- Convert the `api` to `ts` which turned out to be tricky with `gapi.client` types
- Customize which metrics to display
- Better Intro section detailing how to set up an `API_KEY` and `CLIENT_ID`
- All kinds of cleaning up and optimizations probably

2020-04-28 06:30 UTC, stefanalund requested changes
This looks like it is aiming to replicate the UX of Google Analytics. Since our goal is to create a consistent experience between plugins, I would rathe see it use a Backstage UX.

2020-04-28 12:14 UTC, freben reviewed
Sorry for the noise 🍎

2020-04-28 12:14 UTC, freben commented on plugins/google-analytics-dashboard/src/components/PageLoad/PageLoad.tsx
> +    padding: 16,
`theme.spacing(2)`

but shouldn't the surrounding grid container have a spacing prop set instead?

2020-04-28 12:14 UTC, freben commented on plugins/google-analytics-dashboard/src/components/PageLoad/PageLoad.tsx
> +    margin: '-13px 0px 7px 0px',
`theme.spacing(-2, 0, 1, 0)`

2020-04-28 12:14 UTC, freben commented on plugins/google-analytics-dashboard/src/components/Select/Select.tsx
> +    '& .MuiTextField-root': {
these are inside a card, right? maybe the card could decide the size of the contents? in that case you can set the `fullWidth` prop on the `TextField`s

2020-04-28 12:14 UTC, freben commented on plugins/google-analytics-dashboard/src/components/SingleValues/SingleValues.tsx
> +    <Grid item container spacing={8}>
remove item?

2020-04-28 12:14 UTC, freben commented on plugins/google-analytics-dashboard/src/components/SingleValues/SingleValues.tsx
> +        <SingleValueItem key={item.title} item={item} />
When you do something like this, I feel it's better if both the container and item are rendered by the same component. Essentially, it becomes a bit weird when a component returns `<Grid item>` as its root element. Instead, in my opinion, it's way clearer if this file does

```
return (
  <Grid container>
    {valueItems.map(item => (
      <Grid item key={item.title}>
        <SingleValue ... />
      </Grid>
    )}
  </Grid>
);
```

that way, the concerns are kept together

2020-04-28 12:14 UTC, freben commented on plugins/google-analytics-dashboard/src/components/TimeRanges/TimeRanges.tsx
> +  'end-date': 'today';
These could be of just type string, if you want.

2020-04-28 13:02 UTC, shmidt-i commented on plugins/google-analytics-dashboard/src/api/api.js
> +  getGaData(query) {
I believe that `async` without `await` is a bit more slim in this case?
![image](https://user-images.githubusercontent.com/5012901/80490160-3dce8880-8961-11ea-8903-89f8894d431b.png)

2020-04-28 13:24 UTC, freben commented on plugins/google-analytics-dashboard/src/api/api.js
> +  getGaData(query) {
Yeah that's kinda what I meant with the second example. Both async and await are technically redundant actually. If you do it the middle-ground way, I think the engine technically still handles it as an extra unnecessary promise resolution level. But no biggie, we're kinda in micro optimization land anyway :) Whatever is more readable wins

2020-06-04 07:18 UTC, marcuseide commented
Closing this as I can't seem to find the time to work on it. I'll see if it can be revived later on.

2020-06-04 07:18 UTC, closed without merging