Create keptn.yaml
backstage/backstage pull request #9084
Opened 2022-01-21 09:31 UTC by maurosala

## Hey, I just made a Pull Request!

Add Keptn plugin to the backstage plugin marketplace

2022-01-21 22:15 UTC, oleg-nenashev commented
FTR we are working on moving the plugin to the Keptn GitHub organization so that it becomes an official part of the project. FTR https://github.com/keptn-sandbox/contributing/issues/8 . Currently we need to confirm the license, AFAICT this is the only blocker for transfer

2022-01-25 08:31 UTC, oleg-nenashev requested changes
Suggesting changes based on moving the plugin to Keptn

2022-01-25 08:31 UTC, oleg-nenashev commented on microsite/data/plugins/keptn.yaml
> +npmPackageName: '@krateo/backstage-plugin-keptn'
Or `keptn/backstage-plugin`?

```suggestion
npmPackageName: '@keptn/backstage-plugin-keptn'
```

2022-01-25 08:31 UTC, oleg-nenashev commented on microsite/data/plugins/keptn.yaml
> +iconUrl: https://raw.githubusercontent.com/krateoplatformops/community/main/logos/white/logo_vertical.svg
```suggestion
iconUrl: https://raw.githubusercontent.com/keptn/community/master/logos/keptn-logo-square.svg
```

2022-01-25 08:31 UTC, oleg-nenashev commented on microsite/data/plugins/keptn.yaml
> +description: Keptn plugin is designed for to monitoring a project and a single service on your keptn installation. You can also post a new delivery with the sync button!
```suggestion
description: Keptn plugin is designed for to monitoring a project and a single service on your Keptn installation. You can also post a new delivery with the sync button!
```

2022-02-04 12:06 UTC, benjdlambert commented
Seems we are missing a DCO check here too! Some help over in [CONTRIBUTING.md](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) if you're unsure.

2022-02-20 15:05 UTC, closed without merging